app/models/registry.rb
spec/classes/registry_spec.rb
spec/spec_helper.rb
spec/vcr_cassettes/registry/get_image_manifest.yml
spec/vcr_cassettes/registry/get_missing_image_manifest.yml
spec/vcr_cassettes/registry/missing_credentials.yml
spec/vcr_cassettes/registry/successful_authentication.yml
spec/vcr_cassettes/registry/wrong_authentication.yml

Add Registry class. This can be used to fetch additional information
from a Docker registry v2 using its API.
Right now the Registry class can authenticate against the registry and
fetch the manifest of a Docker image available on the it.

Add class to interact with a Docker Registry server

---

app/controllers/api/v2/tokens_controller.rb
app/models/team.rb
app/models/team_user.rb
app/models/user.rb
app/observers/team_observer.rb
app/observers/user_observer.rb
app/policies/namespace_policy.rb
config/application.rb
db/migrate/20150429102443_add_role_to_team_user.rb
db/schema.rb
spec/api/v2/token_spec.rb
spec/models/user_spec.rb
spec/observers/user_observer_spec.rb
spec/policies/namespace_policy_spec.rb

This PR introduces the concept of user roles within a team, as requested by the 1st milestone (see issue #16).
A team can have three types of users:
* viewers: RO access
* contributors: RW access
* owners: like contributors, but have also access to the admin panel of the team

Team roles

---

app/assets/javascripts/teams.js.coffee
app/views/teams/index.html.slim
app/views/teams/show.html.slim

This commit also adds the 'required' attribute where needed and it sets the
focus on the element to be filled.

Reset the values of the forms for creating teams, namespaces and members

---

app/models/namespace.rb
app/models/team.rb
app/models/user.rb
spec/controllers/namespaces_controller_spec.rb
spec/factories/teams_factory.rb
spec/factories/users_factory.rb
spec/models/namespace_spec.rb
spec/models/repository_spec.rb
spec/models/user_spec.rb

The Docker daemon performs some validations for the User's username and
also for the Namespace's name. We have to apply the same policies
inside of Portus.
Fixes #42 and #44

Ensure User#username and Namespace#name are always valid

---

Gemfile

When packaging this application as for example an RPM, we need to know
which gems are needed, which means we don't want to have devel or test
gems.
While you can run "bundle install --without development test", this
does not update the Gemfile.lock, meaning the develoment and test gems
are still in Gemfile.lock.
If you infere the gem dependencies from the Gemfile.lock, you would get
the development and test gems, unless you exclude them inside the
Gemfile file.
This commits adds a "unless ENV['PACKAGING'] == 'yes'" that excludes the
gems in the Gemfile thus, if you run
PACKAGING=yes bundle list
you will get the Gemfile.lock that you need without the test and
development dependencies and thus you can use that for infering which
gems you will need in production and thus set the package …

review Gemfile for packaging

---

app/controllers/auth/registrations_controller.rb
spec/features/auth/signup_feature_spec.rb

Devise does not redirect to the 'new' page on signup error, but it renders it.
This means that on signup error the `@admin` view variable will be nil, thus
showing the "Create Admin" button. In this commit a before_filter has been
added for both the 'new' and the 'create' actions, so this case is always
handled consistently.

registrations: don't show "Create Admin" on signup error if there is an admin

---

Gemfile
Gemfile.lock
app/controllers/api/base_controller.rb
app/controllers/api/v2/tokens_controller.rb
app/models/user.rb
config/application.rb
spec/api/v2/token_spec.rb
spec/controllers/auth/registrations_controller_spec.rb
spec/models/user_spec.rb

Soon we are going to fetch informations from the registry itself (like
repositories' manifests). When doing that we have to authenticate
against the registry like all normal clients. Basically Portus is going to
authenticate against itself. :)
The client library used to interact with the registry is already merged
in master (see `app/models/registry_client.rb`). However we still have
to provide a username and password. Hence we need to send the password
as a client, and then verify itself inside of the token controller.
We are going to authenticate as 'portus' user providing a time based one
time only password (aka TOTP).
The TOTP is generated using a secret that changes every time the Rails process
starts (see `config/application.rb`).
The policy checks inside of the token controller …

Introducing the special 'portus' user

---

app/assets/stylesheets/vendor/alerts.css.less
app/helpers/devise_helper.rb
app/views/shared/_notification.html.slim
app/views/shared/_notifications.html.slim
spec/features/auth/signup_feature_spec.rb

Now flashy messages and devise errors will use the same template to render notifications. For flashy messages this is not very important (except that the `notifications.html.slim` file gets simplified), but for devise errors this is an improvement. This is how devise errors were rendered before:
And this is how they look now:

Merged the rendering of flashy messages and devise errors

---

app/models/namespace.rb
app/models/repository.rb
app/models/tag.rb
app/models/team.rb
app/models/user.rb
db/migrate/20150522140822_add_index_name_on_teams.rb
db/migrate/20150522141052_fix_index_name_on_repositories.rb
db/migrate/20150522141547_fix_index_name_on_namespaces.rb
db/migrate/20150522144027_add_index_on_tag_name_repository_id.rb
db/schema.rb
spec/models/user_spec.rb

Ensure:
* a user cannot be created when there's already a namespace with the
same name
* namespace names must be unique relatively to the registry they
belong to
* repositories names must be unique relatively to the namespace they
belong to
* tags names must be unique relatively to the repository they belong
to
* team name must be unique
We are now verifying the format of the name used by repositories and
tags. As usual we follow docker's directives.
This fixes issue #74 and issue #68

Fix db constraints

---

app/controllers/teams_controller.rb
app/models/registry.rb
app/models/team.rb
app/models/user.rb
app/observers/registry_observer.rb
app/observers/team_observer.rb
app/observers/user_observer.rb
config/application.rb
spec/controllers/teams_controller_spec.rb
spec/models/user_spec.rb
spec/observers/registry_observer_spec.rb
spec/observers/user_observer_spec.rb
spec/policies/namespace_policy_spec.rb
spec/policies/team_policy_spec.rb

When creating a new team no namespace will be automatically created.
This implments what discussed inside of #73. It also fixes #72 and
makes #53 useless.

Don't allocate automatically a namespace upon team creation

---

Gemfile.lock
app/assets/javascripts/profile.js.coffee
app/assets/stylesheets/application.scss
app/controllers/auth/registrations_controller.rb
app/views/devise/registrations/edit.html.slim
spec/controllers/auth/registrations_controller_spec.rb

As described in the issue #80, the profile page was quite broken. This PR fixes this situation. In order to do this, the `update` method from `devise` has to be re-implemented, otherwise we will face some issues regarding password fields. That being said, I've tried to use as many `devise` methods inside this new `update` method as possible, so it is as consistent as possible. The mandatory screenshot:
As you can see, I don't allow panels to fill the width, because personally I think that it looks ugly then. Moreover, I've also added some coffeescript to enable/disable buttons as needed.

Adapted the style of the profile page and fixed some bugs

---

.travis.yml

The ruby-head version is allowed to fail

travis: add ruby 2.2 and ruby-head

---

packaging/appliance/index.html.in

appliance is being built under
obs://Virtualization:containers:Portus/PortusAppliance
The appliance contains a landing page.
I don't know where to put this so I am creating a directory for it and
later on we can move it to whatever location we think is best.

add landing page for appliance

---

app/controllers/auth/registrations_controller.rb
app/controllers/auth/sessions_controller.rb
app/views/devise/registrations/new.html.slim
spec/features/auth/signup_feature_spec.rb

This PR does not address the part of #100 stating that there should be a text explaining why the first user to be created is the admin. Following the logic of #101, this should be put in the docs, and not in the page itself. So I propose to skip the second point of #100.
Fixes #100

Always redirect to the signup page if there are no users in the system

---

app/assets/javascripts/lifeitup_layout.js
app/views/namespaces/index.html.slim
app/views/team_users/_team_user.html.slim
app/views/teams/show.html.slim

Moreover, since these popovers have to appear for dynamically-generated
content, then we have to change the lifeitup code that handled popovers in
order to take this into account. Finally, I've moved all the "data-trigger"
attributes to the JS config.
Fixes #106

Replaced `alerts` for Bootstrap's popover element

---

.rubocop.yml
app/controllers/api/v2/tokens_controller.rb
app/controllers/application_controller.rb
app/controllers/auth/registrations_controller.rb
db/seeds.rb

The reported issues have been:
- Since 4.2 *_filter methods are discouraged, in favor of *_action methods.
- We should use Rails.logger instead of puts.

rubocop: added cops for rails

---

app/helpers/application_helper.rb
app/models/namespace.rb
app/views/namespaces/_namespace.html.slim
app/views/namespaces/show.html.slim
app/views/public_activity/repository/_push.html.slim
app/views/repositories/index.html.slim
app/views/repositories/show.html.slim
spec/helpers/application_helper_spec.rb
spec/models/namespace_spec.rb

I've also moved the `namespace_clean_name` method into the Namespace model,
since it makes more sense.

Show the cleaned name of the namespace in the repositories#show page

---

app/controllers/admin/users_controller.rb
app/models/registry.rb
app/models/user.rb
spec/models/registry_spec.rb
spec/models/user_spec.rb

This is a consistency fix. The idea is that the global namespace should be
owned by all the current admins. This means, that:
1. Whenever we add/remove a new admin, this should be updated.
2. When a registry gets created, all the admins should be added.

Make sure that all the admins own the global namespace

---

index.html

Hi Portus team.  Love the look of the Portus website!  Here are a few minor changes.  
+ remove `http:` from Google fonts urls (fixes mixed content warning on https)
+ Grammatical fixes / some rewording. Couple of typos fixed.
+ Removal of some extra space characters

Website formatting and grammatical changes

---

spec/api/v2/token_spec.rb
spec/controllers/admin/activities_controller_spec.rb
spec/features/teams_spec.rb
spec/spec_helper.rb

I've also fixed some weird errors regarding Timecop that were affecting these tests.

spec: implemented acceptance tests for the teams#index page

---

.dockerignore
Dockerfile
README.md
config/database-docker-compose.yml
docker-compose.yml

This commit adds the possibility to run Portus and its database using docker-compose. This is a different take for issue #81.
I'll add the documentation tomorrow. In the meantime feel free to comment on it.

Run Portus using docker-compose

---

app/models/repository.rb
spec/controllers/search_controller_spec.rb
spec/policies/repository_policy_spec.rb

This works around a regression in the search feature. Basically, MariaDB seems
to fail at some searches when the `fulltext` option has been enabled. We are
still investigating about this.

Disabling the `fulltext` option for the repository model for now

---

app/controllers/search_controller.rb
spec/policies/repository_policy_spec.rb

Right now the tag is ignored, but at least it looks for the given repo instead
of failing. This, of course, could be improved in the future.
Fixes #221

search: Support the `repo:tag` syntax

---

app/policies/namespace_policy.rb
spec/policies/namespace_policy_spec.rb

Namespaces that are both accessible to the user and public used to be repeated twice.

Fix duplicated namespaces on the GET /namespaces

---

CHANGELOG.md
Gemfile
Gemfile.lock
app/controllers/admin/activities_controller.rb
app/controllers/admin/namespaces_controller.rb
app/controllers/admin/teams_controller.rb
app/controllers/admin/users_controller.rb
app/controllers/namespaces_controller.rb
app/controllers/teams_controller.rb
app/views/admin/activities/index.html.slim
app/views/admin/namespaces/index.html.slim
app/views/admin/registries/index.html.slim
app/views/admin/teams/index.html.slim
app/views/admin/users/index.html.slim
app/views/namespaces/index.html.slim
app/views/namespaces/show.html.slim
app/views/teams/index.html.slim
app/views/teams/show.html.slim
spec/controllers/admin/activities_controller_spec.rb
spec/controllers/admin/namespaces_controller_spec.rb
spec/controllers/admin/teams_controller_spec.rb
spec/controllers/admin/users_controller_spec.rb
spec/controllers/namespaces_controller_spec.rb
spec/controllers/teams_controller_spec.rb

Add pagination

---

CHANGELOG.md
app/controllers/admin/users_controller.rb
app/controllers/auth/registrations_controller.rb
app/controllers/teams_controller.rb
app/models/team_user.rb
app/models/user.rb
app/views/admin/dashboard/index.html.slim
app/views/admin/users/index.html.slim
app/views/admin/users/toggle_admin.js.erb
app/views/auth/registrations/disabled.js.erb
app/views/devise/registrations/edit.html.slim
config/routes.rb
db/migrate/20150729153854_add_enabled_to_users.rb
db/schema.rb
spec/api/v2/token_spec.rb
spec/controllers/auth/registrations_controller_spec.rb
spec/controllers/teams_controller_spec.rb
spec/factories/teams_factory.rb
spec/features/admin/users_spec.rb
spec/features/auth/login_feature_spec.rb
spec/features/auth/profile_feature_spec.rb
spec/models/team_spec.rb
spec/models/team_user_spec.rb
spec/models/user_spec.rb

Implemented the "Disable users" feature

---

app/views/admin/users/toggle_admin.js.erb
app/views/namespaces/create.js.erb
app/views/namespaces/toggle_public.js.erb
app/views/team_users/create.js.erb
app/views/team_users/destroy.js.erb
app/views/teams/create.js.erb
spec/features/admin/users_spec.rb
spec/features/namespaces_spec.rb
spec/features/teams_spec.rb

A ton of JS expected the #notice element to exist but that was never the case.
Instead, the element to target for flashy messages is the #alert one. This must
be some leftover from a refactoring.
Moreover, I've added some acceptance tests that were missing (e.g. Team
members), since some of the alert messages referenced this features anyways.

Ported flashy messages from #notice to #alert

---

.rubocop.yml
Gemfile
Gemfile.lock
README.md
app/jobs/catalog_job.rb
app/models/namespace.rb
app/models/repository.rb
config/config.yml
config/cronotab.rb
db/migrate/20150805130722_create_crono_jobs.rb
db/schema.rb
spec/classes/registry_client_spec.rb
spec/jobs/catalog_job_spec.rb
spec/models/namespace_spec.rb
spec/models/repository_spec.rb
spec/vcr_cassettes/registry/get_registry_catalog.yml

In recent commits, the RegistryClient not only was fixed, but it also
introduced the `catalog` method. With this commit we take advantage of this new
method by calling it in a new crono job.
For managing and launching this new job we use the `crono` gem as suggested by
@lsamayoa.
Fixes #199

Take advantage of the Catalog API

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/dashboard.scss
app/controllers/dashboard_controller.rb
app/views/dashboard/index.html.slim
app/views/shared/_aside.html.slim
spec/features/auth/login_feature_spec.rb
spec/features/auth/signup_feature_spec.rb

Improve the dashboard to show both the recent activities and the starred repositories.
This addresses https://github.com/SUSE/Portus/issues/243
Mandatory screenshot:

Show starred repositories on the dashboard

---

app/models/concerns/http_helpers.rb
app/models/registry_client.rb
spec/classes/registry_client_spec.rb

This way we have a separation of:
- http_helpers: HTTP helpers and methods for the authentication process.
- registry_client: just the methods dealing with the endpoints themselves.
Moreover, the `get_request` method has been renamed to `perform_request`, since
now it's capable of performing any HTTP method. This has been done so it's
easier to implement features that are still pending to be implemented like
deleting images.

client: moved all the HTTP helpers into its own concern

---

app/assets/javascripts/dashboard.coffee
app/controllers/dashboard_controller.rb
app/views/dashboard/_repository.html.slim
app/views/dashboard/_star.html.slim
app/views/dashboard/index.html.slim
spec/features/auth/login_feature_spec.rb
spec/features/auth/logout_feature_spec.rb
spec/features/auth/signup_feature_spec.rb
spec/features/dashboard_spec.rb
spec/features/gravatar_spec.rb

It is now possible to show all the repositories an user has access to,
the personal repositories and the starred ones.
This fixes issue https://github.com/SUSE/Portus/issues/265
**NOTE WELL:** almost ready to be merged, we have to figure out why some tests are failing. Apparently it's a bug that has always been there, we simply never realized it.

Show more details on the dashboard about repos

---

docker-compose.yml

Warning: the mapping "docker/registry:/registry" in the volumes config for service "registry" is ambiguous. In a future version of Docker, it will designate a "named" volume (see https://github.com/docker/docker/pull/14242).

fixed a warning tips.

---

Gemfile
packaging/suse/Portus.spec.in

Assets are not being recompiled in production for Rails 4
http://guides.rubyonrails.org/asset_pipeline.html
Thus, we don't need any javascript engine in production (nor the gems
that requires that)
Let's remove nodejs and the gems that require that from production
(=assets gems)
However, we do need nodejs and these gems for precompiling the assets,
thus we use an env variable for enabling/disabling them.
This way we can do:
For precompiling assets in the spec file:
PACKAGING=yes IGNORE_ASSETS=no RAILS_ENV=production bundle exec rake
assets:precompile
and then, for bundling the gems:
PACKAGING=yes IGNORE_ASSETS=yes bundle install

remove nodejs as a requirement for production

---

packaging/suse/Portus.spec.in

If we install bundler gem under vendor/bundle/ruby/2.1.0 directory,
and since we had that directory as GEM_PATH in the vhost configuration,
we don't need rubygem-bundler rpm as a runtime requirement.
Bundler does not install itself if you add it at the Gemfile, thus we
need to install it with "gem install --install-dir ..."

get rid of rubygem-bundler as run-time requirement

---

packaging/suse/Portus.spec.in
packaging/suse/make_spec.sh

We are not using the provides for tracking the bundled gems, so we better don't have it because it creates noise.
I did it on a way that if we decide to get it back, we can revert the latest commit and we will have what we will probably need, that is "Provides: bundled(rubygem-foo) = XXX"

Remove explicit provides

---

config/database.yml
config/secrets.yml
packaging/suse/Portus.spec.in
packaging/suse/conf/etc.apache2.vhosts.d.portus.conf
packaging/suse/scripts/configure_portus.sh
packaging/suse/scripts/configure_registry.sh
packaging/suse/scripts/configure_ssl.sh
packaging/suse/scripts/create_db.sh

This is required for creating an RPM that can be supported.
In order to simplify the configuration when installing from an RPM, I've moved the configuration to:
* environment variables for Portus configuration for production
* scripts for generating registry, ssl, apache and db configuration
* the environment variables for Portus will be set in the apache configuration
This way, the Portus configuration for production can be reused when deploying with other ways other than the RPM. However, if you deploy with the RPM, you can set up those variables in the apache configuration.
Also, external dependencies like registry, ssl, db, apache, can be easily configured by running some scripts. These scripts will provide default configurations, thus, the user can decide not to run them. For …

Review production configuration

---

app/controllers/application_controller.rb
config/secrets.yml

If secrets have not been set or ssl, render an error page. This will
prevent running unsafely in production but also provides with a
running application.
The message needs to be rewritten. I'll do that on a separate commit.

check secrets and ssl in production

---

README.md
docker/compose-common.yml

We need 2.1 since it's the first version that supports soft deletes. This
commit also fixes a regression on the registry config as a side-effect.

Raised registry minimum version from 2.0 to 2.1

---

Gemfile.lock

It was discovered that the upstream library for uglifier Gem for Ruby,
UglifyJS, versions 2.4.23 and earlier, was affected by a vulnerability
which allows a specially crafted JavaScript file to have altered
functionality after minification. This bug was demonstrated to allow
potentially malicious code to be hidden within secure code, activated
by minification.
References:
https://github.com/mishoo/UglifyJS2/issues/751
https://zyan.scripts.mit.edu/blog/backdooring-js/

update uglifier gem for fixing a security issue (OSVDB-126747)

---

CHANGELOG.md
app/controllers/api/v2/tokens_controller.rb
spec/api/v2/token_spec.rb

**NOTE WELL:** This is some preliminary work to fix issue 276. I'm about to leave for my vacation. @mssola please take a look at the code and vet it. I can fix the broken tests once I'm back on the 1st of September (unless you really want to take care of that once you are back from your vacation). 
The authorization protocol changed with Docker 1.8:
* client does pull or push or whatever
* daemon does ping to registry i.e. https://registry.ip/v2/
* registry returns 401 along with realm and service, but not scope
* daemon asks for a token from the auth server, with
service=<registry>&scope=repository:namespace/image:push,pull
In other words, the daemon always asks for push,pull, even if you are
just doing a pull. The auth server is supposed to respond in the
following fashion:
* If …

Support auth protocol introduced by docker 1.8

---

CHANGELOG.md
Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/controllers/auth/registrations_controller.rb
app/controllers/auth/sessions_controller.rb
app/models/user.rb
app/views/devise/registrations/edit.html.slim
app/views/devise/sessions/new.html.slim
app/views/shared/_header.html.slim
config/config.yml
config/initializers/config.rb
config/initializers/devise.rb
config/initializers/ldap_authenticatable.rb
config/locales/devise.en.yml
db/migrate/20150831131727_add_ldap_name_to_users.rb
db/schema.rb
lib/portus/ldap.rb
spec/api/v2/token_spec.rb
spec/features/application_spec.rb
spec/features/auth/login_feature_spec.rb
spec/features/auth/signup_feature_spec.rb
spec/features/gravatar_spec.rb
spec/lib/portus/ldap_spec.rb
spec/models/user_spec.rb
spec/spec_helper.rb

This is an introduction to LDAP support. There are some questions that need to
be addressed, but at least the basic structure is in place now.
Fixes #150

Introducing LDAP support

---

config/config.yml
lib/portus/config.rb
lib/portus/ldap.rb
spec/lib/portus/ldap_spec.rb

If disabled, Portus won't guess the email. Otherwise, there are now two
ways in which Portus can guess the email for an LDAP user:
1. From the dc components of the dc string.
2. From a specified key.

ldap: added the `guess_email` configuration parameter

---

Gemfile.lock
app/assets/stylesheets/application.scss
app/helpers/application_helper.rb
app/views/public_activity/namespace/_create.html.slim
app/views/public_activity/namespace/_private.html.slim
app/views/public_activity/namespace/_public.html.slim
app/views/public_activity/repository/_push.html.slim
app/views/public_activity/team/_add_member.html.slim
app/views/public_activity/team/_change_member_role.html.slim
app/views/public_activity/team/_create.html.slim
app/views/public_activity/team/_remove_member.html.slim
app/views/shared/_header.html.slim
spec/helpers/application_helper_spec.rb
spec/lib/portus/config_spec.rb

I realized that in the public activities we use `gravatar_image_tag` directly,
without caring whether the current Portus instance has gravatar support enabled
or not. Therefore, I'm introducing a helper method that abstracts this away,
and I've replaced all the wrong uses of the `gravatar_image_tag` with this new
helper method.

Respect the "gravatar" configurable value everywhere

---

lib/portus/config.rb
lib/portus/hash_utils.rb
spec/fixtures/local.yml
spec/lib/portus/config_spec.rb

If we have the following configuration:
```yaml
ldap:
enabled: true
```
Now there is another way to change that besides using a `config-local.yml`
file. That's by using the proper environment variable. For the previous case,
the environment variable would be `PORTUS_LDAP_ENABLED`. Therefore, all these
environment variables start with "PORTUS", and then they follow the keys.
Moreover, now the accepted configurable values are tied to the `config.yml`
file. Therefore, any other value set by either the `config-local.yml` file or
an environment variable will be properly ignored.

Allow configurable values to be overwritten by environment variables

---

CHANGELOG.md
app/controllers/auth/registrations_controller.rb
app/views/devise/registrations/new.html.slim
config/config.yml
lib/tasks/admin_user.rake
packaging/suse/conf/etc.apache2.vhosts.d.portus.conf
spec/features/auth/signup_feature_spec.rb

set admin user from a rake task and disable first-user is admin

---

compose-setup.sh

The script is forcing the `DOCKER_HOST` value as the hostname of the current machine, but some people use a custom `DOCKER_HOST`.
This small fix will keep the `DOCKER_HOST` value if already exists or replace with the `hostname -f` if not.

[compose-setup]: Use the current DOCKER_HOST value if already exists

---

app/models/registry.rb
spec/models/repository_spec.rb
spec/vcr_cassettes/registry/get_image_manifest_another_webhook.yml
spec/vcr_cassettes/registry/get_image_manifest_namespaced_webhook.yml
spec/vcr_cassettes/registry/get_image_manifest_webhook.yml

Distribution changed the format of event notifications. In particular, the tag
is no longer provided inside the URL. This is a good move since it's safer to
point by digest. However it affected us because we retrieved tags from this
URL. From now on, we'll take advantage of this digest to call the Manifest API
and fetch the tag.
I've also submitted an issue on Docker Distribution about providing a better
solution for this (so we don't have to call the Manifest API everytime).
See docker/distribution#966

registry: fixed webhooks for distribution v2.1

---

CHANGELOG.md
app/controllers/auth/sessions_controller.rb
app/controllers/passwords_controller.rb
app/mailers/devise_mailer.rb
app/views/devise/passwords/edit.html.slim
app/views/devise/passwords/new.html.slim
app/views/devise/sessions/new.html.slim
config/config.yml
config/environments/production.rb
config/environments/test.rb
config/initializers/devise.rb
config/initializers/smtp.rb
config/routes.rb
spec/controllers/passwords_controller_spec.rb
spec/features/forgotten_password_spec.rb

When users fail at logging in, they will have access to a link asking whether
they remember their password or not. If they click this link, they will start
with the password recovery mechanism:
1. Portus will send an email with further instructions.
2. Users will receive the email and click on the given link.
3. Users will type their new password.
4. On success they will be automatically logged in.
Fixes #287

Added the "Password forgotten" option

---

config/initializers/devise.rb
lib/portus/ldap.rb
spec/api/v2/token_spec.rb

We will populate the `params[:user]` hash if there was an HTTP Basic
authentication set in the request.
Fixes #324

ldap: allow login/signup from Docker CLI

---

packaging/suse/Portus.spec.in
packaging/suse/scripts/check_reqs.include
packaging/suse/scripts/configure_apache.sh
packaging/suse/scripts/configure_database.sh
packaging/suse/scripts/configure_registry.sh
packaging/suse/scripts/configure_secrets.sh
packaging/suse/scripts/configure_ssl.sh

This way this is owned by the package, so we can update it on future
releases, but the user can still override settings in the final file

[packaging] move apache conf to /etc/apache/vhosts.d/portus.conf.sample

---

config/initializers/devise.rb
spec/api/v2/token_spec.rb
spec/lib/portus/ldap_spec.rb
spec/rails_helper.rb

There were some issues with tests requiring LDAP to be enabled. To fix that,
LDAP will be enabled always for the test suite. However, the test suite mocks
away the Portus::LDAP class so the `authenticate!` method fails gracefully for
regular tests. Tests that require the legit version of the `authenticate!`
method have to call the following inside the `before(:each)` block:
```ruby
allow_any_instance_of(Portus::LDAP).to receive(:authenticate!).and_call_original
```

ldap: fixed LDAP tests

---

packaging/suse/scripts/configure_database.sh
packaging/suse/scripts/create_database.sh

we need the create_database.sh script because you call it in the
appliance first-boot

[packaging] split create_database

---

packaging/suse/scripts/portus-firstboot

This script has been used in the appliance. However, we need this same
script for setting up some test scenarios with default vaules

add init boot script for portus

---

lib/portus/ldap.rb
spec/lib/portus/ldap_spec.rb

Thanks to @sotsy for the catch!
Fixes #324

Fixed regression on the authentication of the Portus user when LDAP is enabled

---

app/assets/stylesheets/application.scss

This fixes a regression in which suddenly the icon on the users container of
the admin page looked inconsistent with the other icons.

Only use the gray color for fa-user inside of activities

---

packaging/suse/Portus.spec.in

add apache2 as BuildRequires because we need it for installing
/etc/apache2/vhosts.d/portus.conf.sample

[packaging] fix Portus.spec

---

packaging/suse/Portus.spec.in

On a really minimal system (e.g. a Docker image) the timezone package
is usually missing, that would cause some rubygem to fail.

Add the 'timezone' requirement to the Portus rpm

---

packaging/suse/scripts/portus-firstboot

Check for the presence of /first-boot before trying to move it. Usually the file is not there, hence the script exits with an error

Fix firstboot

---

config/environments/production.rb

This is required to get rid of a deprecation warning:
> DEPRECATION WARNING: You did not specify a `log_level` in
> `production.rb`. Currently, the default value for `log_level` is
> `:info` for the production environment and `:debug` in all other
> environments. In Rails 5 the default value will be unified to `:debug`
> across all environments. To preserve the current setting, add the
> following line to your `production.rb`:

Set log level for production env

---

packaging/suse/conf/etc.apache2.vhosts.d.portus.conf
packaging/suse/scripts/configure_apache.sh

It looks like use ${HOSTNAME} does not work in the apache configuration
for portus. I realized that when trying to login with docker.
Thus, let's set the value within the configure_apache script

[packaging] fix hostname apache configuration

---

app/controllers/application_controller.rb
config/config.yml
spec/controllers/errors_controller_spec.rb
spec/spec_helper.rb

The default is to enforce ssl usage on production, however in certain circumstances (e.g.: out internal integration test suite) it's actually more convenient to not use ssl.

Make it possible to disable ssl checks on production

---

packaging/suse/scripts/portus-firstboot

in firstboot we are not calling config_apache.sh script so that the
hostname is not being set up
This is duplication, but don't worry, a PR that changes this scripts
will follow.
Meanwhile, this fixes the appliance.

[packaging] first firstboot configuration of apache

---

.rubocop.yml
config/config.yml
lib/portus/ldap.rb
spec/lib/portus/ldap_spec.rb

As expected, the Net::LDAP class supports this seamlessly. Moreover, the added
configuration is minimal: there is now the "method" configurable value with
three possible values ("plain", "simple_tls" and "starttls").
I'd say that "plain" is the best default, since it's the easiest to configure
from a server point of view. However, the recommended choice is "starttls",
as described in the documentation of this newly added value.
I've also relaxed a rubocop rule. I plan to fix this as soon as possible.
Fixes #311

ldap: added support for SSL/TLS connections

---

app/controllers/admin/registries_controller.rb
app/jobs/catalog_job.rb
app/models/registry.rb
app/views/admin/registries/index.html.slim
app/views/admin/registries/new.html.slim
app/views/admin/registries/update.js.erb
bin/client.rb
config/routes.rb
db/migrate/20150923091830_add_use_ssl_to_registries.rb
db/schema.rb
spec/controllers/admin/registries_controller_spec.rb
spec/factories/registries.rb
spec/features/admin/registries_spec.rb
spec/models/registry_spec.rb

This fixes some known issues like the setup of the appliance, in which the
Portus instance and the registry just couldn't speak to each other.
In order to do this, the `use_ssl` attribute has been introduced. This
attribute can be changed in the "registries#show" page in the form of a toggle
box. There's also a checkbox that allows the admin to set `use_ssl` as true
when creating a new registry.
Moreover, this commit also brings some needed cleaning in regards to classes
dealing with registries.
Fixes #362

Added SSL support for the communication between Portus and the registry

---

packaging/suse/scripts/portus-firstboot

We need mysql running in order to set it up with mysqladmin commands

[packaging] fix portus-firstboot: start mysql

---

index.html

When `docker-compose up` was run, it hit the following error:
Couldn't find env file: [redacted]/Portus/docker/environment

Fix broken install instructions

---

app/models/registry.rb
spec/models/registry_spec.rb
spec/models/repository_spec.rb

As noted by @morodin in the issue #338, when Portus fails the fetch the
manifest, it adds a new tag "1" into the database. This is due to a regression
introduced in 09dc052721ad560e4fb56c585f6193d3305fc578. In this case, on
failure the `get_tag_from_manifest` method returned true on error, because
that's what the logger returns. This commit makes sure that in this case nil is
returned.
Moreover, Portus will now also log the error that has happenned when fetching
the manifest.

registry: return the proper error when fetching the manifest fails

---

packaging/suse/portusctl/lib/cli.rb

This is handy for starting arbitrary scripts via bunndler exec (i.e. portusctl exec rails c production)

portusctl: add exec subcommand

---

app/jobs/catalog_job.rb
app/models/repository.rb
spec/models/repository_spec.rb

When fetching the catalog, if a given repo is supposed to belong to a namespace
that doesn't exist, do nothing. This is more likely to be a problem in the
registry, since we do not allow to create repos in namespaces that are not in
the system.
This commit also closes the possibility for the CatalogJob to be used as an
automatic migration tool.

catalog_job: skip repos belonging to a non-existing namespace

---

packaging/suse/portusctl/lib/configurator.rb

Do not attempt to start the `mysql` service unless the database is
running on the same host.

portusctl: detect when MariaDB is on the same host

---

compose-setup.sh

This avoids problems when running this on OSX

compose: use the IP of the hostname instead of the fully qualified name

---

packaging/suse/portusctl/lib/configurator.rb

Do not overwrite the secrets file if it already exists. That would
cause a discrepancy of the password of the "portus" user.
Required to fix part of the problems reported inside of issue #376

portusctl: do not overwrite secrets file

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/layout.scss
app/assets/stylesheets/mixins.scss

Closes #119
- Fixes the search placeholder while providing a mixin for future cases.
- Explicitly stating that opacity of the button to be 1. Before it was dimmed out when disabled, creating a strange style.
- Removing the outline and box-shadow to clean it up a bit.
Signed-off-by: Bryce Reitano <bryce@rocketmade.com>

Fix search placeholder color.

---

.travis.yml
packaging/suse/portusctl/lib/cli.rb
packaging/suse/portusctl/lib/configurator.rb
packaging/suse/portusctl/lib/template_writer.rb
packaging/suse/portusctl/templates/registry.yml.erb

Show a working example of Registry's configuration when the Registry is
not running on the same host of Portus.

portusctl: show example of Registry's configuration

---

CHANGELOG.md
app/assets/stylesheets/application.scss
app/assets/stylesheets/tables.scss
app/helpers/application_helper.rb
app/helpers/namespaces_helper.rb
app/helpers/teams_helper.rb
app/views/admin/namespaces/index.html.slim
app/views/admin/teams/index.html.slim
app/views/team_users/_team_user.html.slim
app/views/teams/_team.html.slim
app/views/teams/index.html.slim
app/views/teams/show.html.slim
packaging/suse/portusctl/lib/configurator.rb
spec/helpers/application_helper_spec.rb
spec/helpers/namespaces_helper_spec.rb
spec/helpers/teams_helper_spec.rb

Closes #36
Additionally, I fixed the deprecation that RuboCop was complaining about. 
Many of the icons are debatable, but I felt these fit the bill pretty well.
Signed-off-by: Bryce Reitano <bryce@rocketmade.com>

Add table icons for namespaces and teams.

---

config/secrets.yml

This is specially useful when testing setups with SSL.

config: allow developers to override some secrets

---

.rubocop.yml
config/rubocop-suse.yml

rubocop: updated SUSE's rubocop config file

---

app/models/repository.rb
app/models/team_user.rb
app/policies/public_activity/activity_policy.rb
app/policies/repository_policy.rb
spec/models/repository_spec.rb

I've also fixed a weird situation in which different elements from the
dashboard were repeated twice. I've fixed this by specifying a `distinct`.

Don't create an activity for a pushed image if the tag already exists

---

app/assets/javascripts/teams.coffee
app/controllers/concerns/change_description.rb
app/controllers/namespaces_controller.rb
app/controllers/teams_controller.rb
app/policies/namespace_policy.rb
app/policies/team_policy.rb
app/views/namespaces/index.html.slim
app/views/namespaces/show.html.slim
app/views/namespaces/update.js.erb
app/views/public_activity/namespace/_change_namespace_description.csv.slim
app/views/public_activity/namespace/_change_namespace_description.html.slim
app/views/public_activity/team/_change_member_role.csv.slim
app/views/public_activity/team/_change_team_description.csv.slim
app/views/public_activity/team/_change_team_description.html.slim
app/views/team_users/_team_user.html.slim
app/views/teams/index.html.slim
app/views/teams/show.html.slim
app/views/teams/update.js.erb
config/routes.rb
db/migrate/20150924084635_add_attribute_to_teams.rb
db/migrate/20150928112551_add_description_to_namespace.rb
db/schema.rb
spec/controllers/namespaces_controller_spec.rb
spec/controllers/teams_controller_spec.rb
spec/policies/namespace_policy_spec.rb

Added additional information for teams and namespaces pages

---

lib/portus/http_helpers.rb

Apparently some users require this in order to make crono work.
Fixes #395

lib/portus: require "net/http"

---

app/controllers/api/base_controller.rb
app/controllers/api/v2/tokens_controller.rb
app/models/namespace/auth_scope.rb
app/models/registry/auth_scope.rb

This way we can get more info about what has failed when requesting the JWT
token in production. I've reviewed all the other logged messages, and they all
seem to have the proper log level.
Note that another sensitive part is when Portus tries to fetch the manifest
after a web event has occurred. This is already handled properly by the
`Registry#get_tag_from_manifest` method.

tokens: log errors from the tokens_controller into the :info level

---

config/config.yml
lib/portus/ldap.rb
spec/lib/portus/ldap_spec.rb

I added support for general LDAP uid attribute since this is necessary in some cases. I tried to follow [Gitlab LDAP configuration](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/config/gitlab.yml.example).
Note: This is my first code in ruby so feel free to criticize.
Signed-off-by: Tomas Dohnalek <dohnto@gmail.com>

Added support for general LDAP uid attribute.

---

Gemfile
Gemfile.lock
docker-compose.yml
docker/compose-common.yml

Switch from thin to Puma. This is going to fix issues caused by thin
being stuck processing slow requests.
Fixes issue #423 and issue #376.
See this comment for more details:
https://github.com/SUSE/Portus/issues/376#issuecomment-146348415

docker-compose: switch to Puma

---

packaging/suse/portusctl/lib/configurator.rb

portusctl runs as root user when there's no log/production.log. That
causes the production.log to be created by the root user and owned by
the root group. That makes impossible for passenger to write messages
to it.
This fixes issue #409

portusctl: fix permissions of Rails' logs

---

app/views/namespaces/show.html.slim

Use the Namespace#clean_name when displaying the name of a namespace always

---

.gitignore

Allow developers to write the `bin/portus` script as a way to setup Portus with
an alternative configuration.

Ignore the `bin/portus` script

---

app/controllers/admin/registries_controller.rb
app/models/registry.rb
app/views/admin/registries/new.html.slim
bin/client.rb
lib/portus/registry_client.rb
spec/controllers/admin/registries_controller_spec.rb
spec/features/admin/registries_spec.rb
spec/lib/portus/registry_client_spec.rb
spec/models/registry_spec.rb

When creating a new registry, Portus will now check whether it's reachable or
not. If it is, it will continue as usual. However, if it's not reachable, then
Portus will redirect to the registries#new page and alert the user with some
useful message. When this redirect happens, the user will have available an
extra checkbox called "Force". If the user checks it, then it's telling to
Portus to force the creation of the registry, even if it's not reachable.
Fixes #408

Make sure that the registry is reachable when creating it

---

Dockerfile
docker-compose.yml
docker/compose-common.yml

User may use third-party mirror instead of docker.io. And those
mirrors may not support library as their default for none namespace.
Signed-off-by: depay <depay19@163.com>

Add namespace "library" for official images

---

app/views/admin/registries/new.html.slim

Since we now redirect the admins to the new_admin_registry_path when no
registry has been created yet, this button does no longer make sense.

registries: remove the "Back" button from the #new page

---

app/views/namespaces/show.html.slim

namespaces: add a space after the "Belongs to: " string

---

config/config.yml
lib/portus/ldap.rb
spec/lib/portus/ldap_spec.rb

I tried to add an authentication subsection in LDAP section to configuration and utilized this in LDAP authentication. This addresses issue #378.
I know that rubocop is failing due to too long class (is this really hard constraint? 140 lines is not really that much :) ) and some alignment in hash, which I am unable to find out what is the proper way of dealing with this. Also I think, that the testsuite is missing some tests, so maybe you can suggest which ones.
Signed-off-by: Tomas Dohnalek <dohnto@gmail.com>

Added LDAP authentication support.

---

app/helpers/application_helper.rb
app/views/public_activity/namespace/_change_namespace_description.html.slim
app/views/public_activity/namespace/_create.html.slim
app/views/public_activity/namespace/_private.html.slim
app/views/public_activity/namespace/_public.html.slim
app/views/public_activity/repository/_push.html.slim
app/views/public_activity/team/_add_member.html.slim
app/views/public_activity/team/_change_member_role.html.slim
app/views/public_activity/team/_change_team_description.html.slim
app/views/public_activity/team/_create.html.slim
app/views/public_activity/team/_remove_member.html.slim

This is how time-related stuff is supposed to be displayed on a web page.
Moreover, I've also added a title for each element so the user can read the
absolute time in which the activity was created.

Use the <time> tag in activities

---

app/controllers/api/v2/tokens_controller.rb
app/policies/namespace_policy.rb
app/views/namespaces/_namespace.html.slim
app/views/namespaces/toggle_public.js.erb
bin/client.rb
spec/api/v2/token_spec.rb
spec/policies/namespace_policy_spec.rb

Before this patch, a "public" namespace allowed pulls to any Portus user.
However, it did not allow pull access to anonymous users.
After this patch, the TokensController won't authenticate every user, but only
those that have called the `docker login` command. From now on, it's up to each
policy to allow/disallow anonymous users. In particular, the only one that
allows access to anonymous users is the Namespace policy, and it only does it
for pull requests.
Fixes #279

Allowed controlled anonymous access with public namespaces

---

lib/portus/ldap.rb
spec/lib/portus/ldap_spec.rb

This update handles when the defined LDAP attr has an array of emails not just a single string.

Add check for array of email in LDAP

---

compose-setup.sh

This is known to be problematic, since our docker compose setup expects the
portus_web container to be created. The problem that this is based on the pwd
alone. It's not possible to specify a name for this, as reported on the
following issue: https://github.com/docker/compose/issues/2092.
Thanks to @jjperezaguinaga for investigating this.
Fixes #469

compose: do not allow the pwd to be another than "portus"

---

packaging/suse/portusctl/lib/cli.rb
packaging/suse/portusctl/lib/constants.rb
packaging/suse/portusctl/lib/runner.rb

This command fetches all the logs needed for debugging purposes.
Fixes #411

portusctl: added the "logs" command

---

docker/crono-supervisord.conf

compose: don't setup the CATALOG_CRON manually, just inherit it

---

app/models/registry.rb
lib/portus/http_helpers.rb

This way we can make sure whether a registry is reachable or not faster.
Fixes #442

lib: use an open timeout of 2 seconds for HTTP requests

---

app/views/public_activity/team/_change_member_role.html.slim
app/views/public_activity/team/_remove_member.html.slim

Users can remove themselves from a team, and owners can step down as owners of
a team. In these cases, it's weird to see a message like "mssola removed user
mssola ...". Instead, now the same message will say "mssola removed itself
...".
Moreover, in the case of removing a team member, it's weird in my opinion to
state the old role of that user. So, comparing on the removal of a team member:
- before: "mssola removed user mssola with role owner from the docker team"
- after:  "mssola removed itself from the docker team"

public_activity: simplify messages of users acting upon themselves

---

app/controllers/auth/registrations_controller.rb
app/controllers/concerns/check_ldap.rb
app/controllers/passwords_controller.rb
spec/controllers/passwords_controller_spec.rb

It doesn't make sense for LDAP users to recover passwords this way, since
Portus acts just as a proxy between users and the LDAP server when it comes to
authentication.
Since this was exactly the same as for the signup page, I've put the code
inside of a concern that bith the RegistrationsController and the
PasswordsController use.

passwords: do not allow LDAP users to access the password reset procedure

---

app/controllers/namespaces_controller.rb
spec/controllers/namespaces_controller_spec.rb

Before this patch, the UI allowed the user to specify the description when
creating a namespace, but it was never actually saved. This commit fixes this
situation.

namespaces: allow the description to be saved when creating a namespace

---

config/environments/development.rb
config/initializers/mailer_url_options.rb

We guess the host and the protocol with the information we have on startup.

config: set the mailer URL options in an initializer

---

app/models/repository.rb
app/models/tag.rb
app/views/public_activity/repository/_push.csv.slim
app/views/public_activity/repository/_push.html.slim
spec/jobs/catalog_job_spec.rb

Now, when a tag gets removed by the catalog job, its activities will be updated
by saving the `tag_name` extra parameter. This parameter will be used by the
views to handle missing tags. Moreover, I've added more log messages.
Fixes #506
Fixes #443

catalog: handle the removal of tags gracefully

---

compose-setup.sh

fix #473
DOCKER_HOST could be set by user or docker-machine.
ps: i'm unsure if this should be mentioned in changelog.

parse DOCKER_HOST when already set

---

config/config.yml
lib/portus/jwt_token.rb
spec/lib/portus/jwt_token_spec.rb

config: added a configurable option for the expiration time of a JWT token

---

app/controllers/application_controller.rb
app/helpers/application_helper.rb
app/views/devise/registrations/edit.html.slim
db/migrate/20151029145958_remove_not_null_constraint_on_users_email.rb
db/schema.rb
lib/portus/ldap.rb
spec/helpers/application_helper_spec.rb
spec/lib/portus/ldap_spec.rb

This way we avoid problems with two consecutive LDAP users trying to sign up
with no email. In order to do this, I've had to enable null values in the email
field, which needed some small modifications here and there.
Fixes #514

ldap: set the email to null if it couldn't be guessed

---

Gemfile
Gemfile.lock
app/views/errors/_status_title.html.slim
app/views/namespaces/show.html.slim
app/views/teams/show.html.slim

Server
fix bnc#953771: Release of Portus build requirements to SLE-12 codestream
I had to fix some slim issues that appeared when downgrading to 2.0.2,
as not using "," but " " to separate values in an array, and use
"if-elsif-else" clauses instead of "case-when"

review gem versions to match the ones available in SUSE Enterprise Linux

---

app/controllers/admin/users_controller.rb
app/views/admin/users/index.html.slim
app/views/admin/users/new.html.slim
config/routes.rb
spec/controllers/admin/users_controller_spec.rb

feat: simple user creation form
first steps for #283 and #179

feat: simple user creation form

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.coffee
app/assets/javascripts/teams.coffee
app/assets/stylesheets/application.scss
app/assets/stylesheets/forms.scss
app/controllers/application_controller.rb
app/controllers/teams_controller.rb
app/models/team.rb
app/models/user.rb
app/policies/team_policy.rb
app/policies/team_user_policy.rb
app/views/teams/show.html.slim
config/routes.rb
spec/controllers/teams_controller_spec.rb

Using typeahead when adding users to a team

---

Gemfile.lock

fix bsc#953771 Release of Portus build requirements to SLE-12 codestream

fix sprockets_rails version so that it matches the one in SLES

---

app/assets/javascripts/teams.coffee
app/controllers/namespaces_controller.rb
app/controllers/teams_controller.rb
app/models/team.rb
app/models/team_user.rb
app/policies/namespace_policy.rb
app/views/namespaces/index.html.slim
config/routes.rb
spec/controllers/namespaces_controller_spec.rb
spec/controllers/teams_controller_spec.rb

Using typeahead to autocomplete teams when creating a namespace

---

app/controllers/auth/registrations_controller.rb
app/controllers/auth/sessions_controller.rb
app/helpers/application_helper.rb
app/views/devise/sessions/new.html.slim
config/config.yml
lib/tasks/portus.rake
spec/controllers/auth/registrations_controller_spec.rb
spec/features/auth/login_feature_spec.rb
spec/features/auth/signup_feature_spec.rb
spec/features/forgotten_password_spec.rb
spec/helpers/application_helper_spec.rb

When enabled (default behavior), then any user can access to the signup page.
Otherwise, users are not able to enter the signup form. This is ignored in LDAP
mode.
Note that I've also added the `verify` configurable value. This is supposed to
be implemented in the near future, as described in the related issues.
See issues #179 and #283

Added the `signup` configurable value

---

app/assets/stylesheets/labels.scss
app/views/namespaces/show.html.slim

The team name on the "Belongs to" label is now a link

---

compose-setup.sh

This fixes the setup on environments that already set the DOCKER_HOST
environment variable. Since this variable can be set to something like
"tcp://IP:POR", the final message cleans up everything so only the IP is shown
together with the proper ports.
I've also cleaned up the final message so it's more well-formatted and verbose.

compose: do nothing if the DOCKER_HOST variable is already set

---

lib/portus/ldap.rb
spec/lib/portus/ldap_spec.rb

Don't force error message to just be :invalid_username !

Show real error message on LDAP authentification

---

app/views/devise/sessions/new.html.slim
spec/features/auth/login_feature_spec.rb

This is a fix for a regression in which Portus didn't show the "I forgot my
password" link in the sign in page when the `signup` configurable value was
disabled.

Show the "I forgot my password" link when the signup is disabled

---

CHANGELOG.md
app/assets/javascripts/comments.coffee
app/assets/stylesheets/application.scss
app/assets/stylesheets/comments.scss
app/controllers/comments_controller.rb
app/controllers/repositories_controller.rb
app/models/comment.rb
app/models/repository.rb
app/policies/comment_policy.rb
app/views/comments/_comment.html.slim
app/views/comments/create.js.erb
app/views/comments/destroy.js.erb
app/views/repositories/show.html.slim
config/routes.rb
db/migrate/20151113162311_create_comments.rb
db/migrate/20151113162513_add_author_to_comment.rb
db/migrate/20151124150353_removetitle.rb
db/schema.rb
spec/api/v2/token_spec.rb
spec/controllers/comments_controller_spec.rb
spec/controllers/repositories_controller_spec.rb
spec/factories/comments.rb
spec/jobs/catalog_job_spec.rb
spec/lib/portus/config_spec.rb
spec/lib/portus/jwt_token_spec.rb
spec/models/comment_spec.rb
spec/policies/repository_policy_spec.rb

Added the the ability to add comments on repositories

---

lib/portus/registry_client.rb
spec/lib/portus/registry_client_spec.rb
spec/vcr_cassettes/registry/catalog_lots_of_repos.yml
spec/vcr_cassettes/registry/get_missing_catalog_endpoint.yml
spec/vcr_cassettes/registry/get_registry_catalog.yml

This is the proper way to the pagination, as described in the API
documentation.

lib/portus: use the "link" header when using pagination

---

packaging/suse/bin/portusctl

We have found that under certain circumstances, portusctl fails to run
bundler.
After debugging it, we found out that on our test machine RUBYLIB was
set as
/usr/lib64/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/
which was causing bundler not being able to run, since this is a
different version than the one we have in /srv/Portus/vendor/....
My guess is that this is because of rubygem-bundler being installed on
that system.
This commit sets that environment variable to our bundler directory.
fix issue#612

set RUBYLIB when running bundle in portusctl

---

README.md
_docs/Configuring-Portus.md
_docs/Configuring-the-registry.md
_docs/How-to-setup-secure-registry.md
_docs/how_we_release.md
_features/1_Synchronizing-the-Registry-and-Portus.md
_features/2_LDAP-support.md
_features/3_teams_namespaces_and_users.md
_features/4_audit.md
_features/5_search.md
_features/6_starring.md
_features/7_disabling_users.md
_features/8_locking.md
_features/9_recovering_password.md
_features/disabling_signup.md
_layouts/post.html
_setups/1_rpm_packages.md
_setups/2_appliance.md
_setups/3_nginx_bare_metal.md
_setups/4_portus_and_registry_on_the_same_fqdn.md
documentation.md
features.md

I've also added the `order` header for all pages, to keep a more sane approach to how we list pages. Moreover, I've also extended the documentation on how to setup this branch for development.

Added a page documenting how to create a secure registry

---

app/views/admin/users/index.html.slim

Virtual/hidden teams are no longer counted for the "number of teams"-column under admin/users.
Fixes: #614

The proper number of teams for admin/users

---

config/config.yml

Make it possible to configure the location of the Navalia service.

Add Navalia to the local configuration file

---

app/views/namespaces/index.html.slim
spec/controllers/comments_controller_spec.rb

Move the "create namespace" link
The link has been moved inside of the "Namespaces you have access to" container as opposed to the "Special namespaces" one.
It makes more sense to have the link in there because the new namespaces that can be created are not going to be special ones.

Move create namespace link

---

Gemfile
Gemfile.lock
app/assets/javascripts/registrations.coffee
app/assets/stylesheets/activities.scss
app/assets/stylesheets/variables.scss
app/controllers/api/v2/tokens_controller.rb
app/controllers/application_tokens_controller.rb
app/models/application_token.rb
app/models/user.rb
app/policies/public_activity/activity_policy.rb
app/views/application_tokens/_application_token.html.slim
app/views/application_tokens/create.js.erb
app/views/application_tokens/destroy.js.erb
app/views/devise/registrations/edit.html.slim
app/views/public_activity/application_token/_create.csv.slim
app/views/public_activity/application_token/_create.html.slim
app/views/public_activity/application_token/_destroy.csv.slim
app/views/public_activity/application_token/_destroy.html.slim
config/routes.rb
db/migrate/20151117181723_create_application_tokens.rb
db/schema.rb
spec/api/v2/token_spec.rb
spec/controllers/application_tokens_controller_spec.rb
spec/factories/activities.rb
spec/factories/application_token.rb
spec/features/application_tokens_spec.rb
spec/models/application_token_spec.rb
spec/models/user_spec.rb
spec/policies/public_activity/activity_policy_spec.rb

Right now the Docker client stores the credentials in plain
format on the host. This is really bad from a security point of view,
especially for users using LDAP to authenticated.
This commit introduces the concept of "application tokens". Each user
can have at most 5 application tokens. The tokens are created in a
random secure way by Portus and are stored inside of its database after
being hashed via bcrypt.
The application tokens can be used by all the programs authenticating
against a Docker registry protected by Portus (e.g.: the docker cli
client). They cannot be used to log into Portus' web interface.
The application tokens can be revoked at any time by using a new UI.
Notice a new token has just been created
After the token has been removed:
This user has already 5 tokens, hence …

Introduce application tokens

---

app/assets/stylesheets/activities.scss
app/assets/stylesheets/variables.scss
app/controllers/repositories_controller.rb
app/helpers/repositories_helper.rb
app/views/public_activity/repository/_create.csv.slim
app/views/public_activity/repository/_create.html.slim
app/views/public_activity/repository/_edit.csv.slim
app/views/public_activity/repository/_edit.html.slim
spec/controllers/repositories_controller_spec.rb
spec/helpers/repositories_helper_spec.rb

Track the following events:
* automated repository creation
* edit of `source_url`

Audit: track more events related with repositories

---

Dockerfile
compose-setup.sh
db/migrate/20151215152138_remove_log_from_crono_job.rb
db/schema.rb
docker-compose.yml
docker/crono-supervisord.conf

Before this commit, the crono job kept on adding the log into the `log` column
from the `crono_jobs` table. This is, of course, a bad thing. What I did to fix
this is to simply remove this columns from the DB, and crono is ok with that.
Running crono again with this patch runs in the very same way as it used to be,
but without adding the log all the time.
Moreover, the log is supposed to go to the stdout, as envisioned by the
Twelve-Factor App manifesto: http://12factor.net. Docker follows this too, and
by doing so then the log of this job blends in with docker-compose logs
command. This has two main consequences:
1. The user can decide how to manage logs in an easier way, so there's no way
that we run out of disk (an issue we were having).
2. supervisor is no longer needed. Instead, we …

Fixed the crono job overflowing the `log` column

---

lib/portus/registry_client.rb
spec/lib/portus/registry_client_spec.rb
spec/vcr_cassettes/registry/get_registry_one_fails.yml

Right now, the `RegistryClient#catalog` method can erase the DB of all the
repos. This happens when, for some unexpected reason, the
`RegistryClient#add_tags` method fails at retrieving one repository. In this
case, before this patch this method just returned an empty array. After this
patch, repositories that are not found will simply not be added, but the
method will go on adding tags to other repositories.
See #663

lib/portus: do not remove all the repos if one fails

---

app/controllers/application_controller.rb
app/controllers/auth/registrations_controller.rb
app/controllers/auth/sessions_controller.rb
app/views/devise/passwords/edit.html.slim
app/views/devise/passwords/new.html.slim
app/views/devise/registrations/new.html.slim
app/views/devise/sessions/new.html.slim
app/views/shared/_header.html.slim

The _url methods should only be used when the full path (+ hostname, etc.) is
needed. This is usually only the case for things like emails and views that are
to be accessed from outside the web app. This can usually be workarounded
through NGinx and similar tools, but it's better to have this behavior even
without such tools.
Fixes #677

app: always use _path methods instead of *_url

---

Gemfile
Gemfile.lock
packaging/suse/portusctl/lib/cli.rb
packaging/suse/portusctl/lib/runner.rb

This is one of the points of http://12factor.net/. It turns out to be quite
useful in this case to avoid issues with logs. Basically by spitting into the
stdout we allow deployers to manage logs as they want. For the different
setups:
- docker-compose: it's integrated with docker-compose logs.
- vagrant & rpm: by default saved in /var/log/apache2/error_log.
- NGinx setup: handled by puma.
Fixes #626

Redirect logs to stdout

---

app/models/registry.rb
spec/models/registry_spec.rb

Do not try to be smart when validating a registry connection using SSL.
Let's just provide a generic error and log the exception into the logs.
This is going to help with issues like #504

Change error message on openSSL's errors

---

Dockerfile

Add the phantomjs to the Portus Docker image. Needless to say this image
is used for testing and development purposes, it's not meant for
production usage. Hence it makes sense to have all the tools actually
needed at development time.

Dockerimage: add phantomjs

---

compose/docker-compose.yml.template

This way fixing a regression in which users couldn't login with the compose
setup.

compose: fix a typo on an environment variable

---

lib/portus/registry_notification.rb
spec/lib/portus/registry_notification_spec.rb

Fixed the `relevant?` method for Registry v2.3

---

config/initializers/version.rb

To determine whether "git" is on the system, we used the mkmf library. This has
turned out to not be the best option because then a "mkmf.log" file is always
generated.

config/initializers: don't use mkmf

---

README.md
app/models/registry.rb
bin/client.rb
lib/portus/registry_client.rb
lib/portus/registry_notification.rb
spec/lib/portus/registry_client_spec.rb
spec/models/registry_spec.rb
spec/models/repository_spec.rb
spec/vcr_cassettes/registry/catalog_lots_of_tags.yml
spec/vcr_cassettes/registry/get_registry_catalog.yml
spec/vcr_cassettes/registry/get_registry_one_fails.yml

In the new manifest Version 2, schema 2; some fields are missing. In this case,
the "tag" field is no longer available as of this version. We used that because
the notification from the registry does not provide such information for now
(hopefully there will be a solution for Distribution 2.4). Thus, we pulled the
manifest and extracted the tag from there.
The code now detects the version of the manifest schema. If it's the latest
one, then we will fetch the tags of the given repo and compare them with what
we've got in the database.
Note that this solution could also be applied to the version 2 schema 1, but
fetching the manifest is faster and less prone to possible sync errors (even
though hese errors are not really important if crono is in place).
Moreover, I've added a table on the …

Fixed Registry synchronization with v2 manifests

---

app/controllers/api/v2/tokens_controller.rb
lib/portus/jwt_token.rb
spec/api/v2/token_spec.rb
spec/lib/portus/jwt_token_spec.rb

While testing Portus as an authorisation server for a private docker registry I ran into occasional authentication errors especially when pushing to repositories that don't exist yet.
The error I'm seeing from the docker client is "authentication required" and after re-trying for 1-2 times it always works.
Example:
```
$> docker push 192.168.163.129:5000/busybox
The push refers to a repository [192.168.163.129:5000/busybox]
5f70bf18a086: Preparing
2c84284818d1: Preparing
unauthorized: authentication required
$> docker push 192.168.163.129:5000/busybox
The push refers to a repository [192.168.163.129:5000/busybox]
5f70bf18a086: Pushed
2c84284818d1: Pushed
latest: digest: sha256:9176b113ee7620cb59f5df4c8afa86e990529e3ca328fe15cbc499eeb64bedfd size: 711
5f70bf18a086: Layer already exists …
```

Support multiple scope parameters in a token request

---

db/schema.rb

I think this slipped in by accident. There is no migration for this in the master branch. It seems this has is origins in this commit https://github.com/SUSE/Portus/commit/c822bb0d636cc6088e7804bf78bea0f6eec5b6ae which is part of the hackday_13 branch

remove source_url from schema.rb

---

lib/portus/jwt_token.rb

The fields are [mentioned in the spec](https://github.com/docker/distribution/blob/master/docs/spec/auth/token.md#token-response-fields).
They might be useful for clients that want to cache tokens for reuse.

Add optional fields to token response

---

packaging/suse/Portus.spec.in

we use "hostname" in the portusctl script, and that requires the package
net-tools to be installed.
If you try to run it on a SLES container, net-tools is not there by
default.

[packaging] require net-tools

---

app/assets/stylesheets/activities.scss
app/views/public_activity/application_token/_create.html.slim
app/views/public_activity/application_token/_destroy.html.slim
app/views/public_activity/namespace/_change_namespace_description.html.slim
app/views/public_activity/namespace/_create.html.slim
app/views/public_activity/namespace/_private.html.slim
app/views/public_activity/namespace/_public.html.slim
app/views/public_activity/repository/_push.html.slim
app/views/public_activity/team/_add_member.html.slim
app/views/public_activity/team/_change_member_role.html.slim
app/views/public_activity/team/_change_team_description.html.slim
app/views/public_activity/team/_change_team_name.html.slim
app/views/public_activity/team/_create.html.slim
app/views/public_activity/team/_remove_member.html.slim

Fixes: #487 
Large screen:
Medium screen:
Small screen:
When the namespace, for example, is too large, the div with the description exceeds the Recent Activities div:
So I added `overflow: hidden` for avoid this layout break (see small screenshot). But I think that is better set a max length to these names.
Signed-off-by: Matheus Fernandes <matheus.souza.fernandes@gmail.com>

Activity messages now fill all the horizontal space available

---

packaging/suse/make_spec.sh
packaging/suse/release/.gitignore
packaging/suse/release/README
packaging/suse/release/project.xml.template
packaging/suse/release/release.sh

This commit adds a "release.sh" script that will release portus in the
build service.
It assumes you will have already tagged and update the VERSION file, as
well as updated the CHANGELOG (see http://port.us.org/docs/how_we_release.html)
It includes a small fix in the make_spec.sh that checks for bundler

automate portus release

---

packaging/suse/Portus.spec.in

This is a fix in order to obsolete Portus-20151120162040 that got
accidentally pushed instead of Portus-2.0

rename Portus to portus

---

documentation.md
index.html

I've also re-arranged the buttons from the index page: the first one is the
"Try out Portus" button which just jumps to a section; and the other two are
just fancy links (github and mailing list).

Added links to the new mailing list

---

app/models/registry.rb
spec/models/registry_spec.rb

Since commit afe2bdd1c5194ac85a59adf1fdd14c9da054356e of docker distribution,
the registry now sends a `tag` key inside of `target` on each notification.

Distribution 2.4 now provides the tag on the notification

---

app/controllers/teams_controller.rb
app/views/namespaces/show.html.slim
spec/controllers/teams_controller_spec.rb

The link to the global team is now hidden. If a user tries to access it
anyway, the user is presented with a 404 error.
Fixes #658

Don't allow access to the hidden global team

---

config/application.rb

To avoid the requirement to provide additional flags while using the
builtin rails generators I have added some flags to the application
configuration. Now the generator always uses rspec, slim and
factory_girl by default, and test_unit as a fallback if any generator
doesn't support rspec.
Signed-off-by: Thomas Boerger <tboerger@suse.de>

Set proper rails generator defaults

---

Gemfile
Gemfile.lock
app/models/application_token.rb
app/models/comment.rb
app/models/namespace.rb
app/models/registry.rb
app/models/repository.rb
app/models/star.rb
app/models/tag.rb
app/models/team.rb
app/models/team_user.rb
app/models/user.rb
spec/factories/comments.rb
spec/factories/namespaces.rb
spec/factories/registries.rb
spec/factories/repositories.rb
spec/models/application_token_spec.rb
spec/models/comment_spec.rb
spec/models/namespace_spec.rb
spec/models/registry_spec.rb
spec/models/repository_spec.rb
spec/models/star_spec.rb
spec/models/tag_spec.rb
spec/models/team_spec.rb
spec/models/team_user_spec.rb
spec/models/user_spec.rb

In order to make the start for newbies easier I have added the annotate gem
which adds the available columns including some meta information as
documentation to the top of all models, factories and model specs.
Signed-off-by: Thomas Boerger <tboerger@suse.de>

Annotate the models, factories and specs

---

app/models/registry.rb
app/models/repository.rb
lib/portus/registry_notification.rb
spec/lib/portus/registry_notification_spec.rb
spec/models/repository_spec.rb

Whenever a manifest gets deleted, the registry will send a "delete" event to
Portus. In this commit Portus will be able to react to these events
accordingly: remove specified tag if available, and remove the repository if
it's left empty of tags.

Handle delete events

---

app/models/repository.rb
spec/models/repository_spec.rb

In this commit the CatalogJob task will also update the manifest digests of
the tags that are to be created.
See #822

crono: update digests when creating tags

---

packaging/suse/bin/portus_crono

This way signals sent to bash are properly propagated to crono.
bnc#976113

suse: wrap crono with the exec command

---

app/models/user.rb
spec/models/user_spec.rb

Up until now we allowed users to have the same username as some teams. This is
troublesome because then the private team assigned to this user would clash
with the existing one.
In the future we should figure out a way to better handle these hidden teams
(e.g. by creating one with a random name and the reference it on the user row).
For now, in order to not be too disruptive we will disallow creating users with
the same name as an existing team (note that the other way around is also
disallowed).
Fixes #836

Don't allow usernames to clash with teams

---

Gemfile
Gemfile.lock

The version 4.2.6 of rails crashes on start.

Upgrade rails_stdout_logging to 0.0.5

---

app/models/registry.rb
app/models/repository.rb
app/models/tag.rb
app/views/repositories/show.html.slim
bin/client.rb
db/migrate/20160422075603_add_image_id_to_tag.rb
db/schema.rb
lib/portus/registry_client.rb
lib/tasks/portus.rake
spec/features/repositories_spec.rb
spec/lib/portus/registry_client_spec.rb
spec/models/registry_spec.rb
spec/models/repository_spec.rb
spec/models/tag_spec.rb

This is the same Image ID that is shown in the docker client. In order to do
this, a new column has been added to the `tags` table. The registry client has
also been modified to handle all this more gracefully. The image ID being
shown is truncated in the exact same format as in the Docker client. That being
said, users can hover the mouse over the image ID and they'll get the full
image ID.
Fixes #512

Add the Image ID in the repositories#show page

---

config.ru
config/initializers/config.rb
lib/tasks/info.rake

Hi,
Would you mind to add these changes? Both are falling back gracefully and therefore shouldn't break anything.
First change improves Sub-URI compatibility with non-passenger setups: you just set `RAILS_RELATIVE_URL_ROOT` environment variable to something like `/portus` and app server starts to serve Portus from subdirectory.
Second change adds ability to set custom path to `config-local.yml` file by setting `PORTUS_LOCAL_CONFIG_PATH` environment variable. This is helpful when setting up on Kubernetes where it's not possible to mount just single file to container, but directory.

Better Sub-URI handling & configurable config-local.yml path

---

packaging/suse/release/project.xml.template
packaging/suse/release/release.sh

Projects in obs are now Virtualization:containers:Portus:X.Y
but used to be Virtualization:containers:Portus:X.Y.Z

we have modified the repos in obs thus we needed to adapt this script

---

packaging/suse/release/release.sh

we had this tag
Obsoletes: Portus={%version}
This has no sense, a package can't obsolete himself

fix obsoletes tag in portus.spec

---

app/helpers/application_helper.rb

Multi line code blocks are now displayed correctly.
Fixes #875

fix markdown multi line code

---

app/controllers/application_controller.rb
app/views/errors/500.html.erb
app/views/errors/show.html.erb
config/config.yml
config/initializers/config.rb
config/initializers/mailer_url_options.rb
lib/portus/jwt_token.rb
packaging/suse/portusctl/templates/config-local.yml.erb
spec/controllers/errors_controller_spec.rb
spec/lib/portus/jwt_token_spec.rb

This is something in between to what we have on the `v2.0` branch and the
`master` branch. This way we have the behavior from `master` while not breaking
what we had in previous patch-level releases.
This commit is largely based on 984671662ade8c105f019b1ee108b71ef87a9821 in the
`master` branch.

Allow the FQDN to be specified through config

---

app/views/shared/_notification.html.slim
vendor/assets/javascripts/lifeitup_layout.js

After closing an alert box, it is removed from the DOM, and won't show
unless the page is refreshed. This fix hides the alert box instead of
closing it.

hide alert box instead of closing it

---

spec/integration/client_spec.rb
spec/integration/helper.rb

Now it covers everything that we have implemented in the registry client.
Fixes #846

spec/integration: updated the client_spec file

---

packaging/suse/release/release.sh

set disabled mode to the _service file so that the tarball does not
get updated while we copy it from/to different projects

fix release script

---

app/views/repositories/show.html.slim
spec/features/repositories_spec.rb

There was an exception raised when a tag with either a nil digest or a nil
image_id was to be rendered.

Fix when either the image_id or the digest are nil

---

app/models/repository.rb
app/models/tag.rb
spec/models/repository_spec.rb
spec/models/tag_spec.rb

Apparently trying to delete images and tags in a repository contained inside of
a namespace that is not the global one didn't work. This commit fixes this
while also making sure that this does not happen in many other cases.
Fixes #897

Fixed a bug in which deleting images didn't work

---

app/controllers/namespaces_controller.rb
app/views/public_activity/namespace/_change_team.csv.slim
app/views/public_activity/namespace/_change_team.html.slim
spec/controllers/namespaces_controller_spec.rb

When a namespace is assigned a new team, an activity is created.
Resolves #877

add activity for moving namespaces

---

app/controllers/concerns/change_name_description.rb
spec/controllers/teams_controller_spec.rb

Check whether the update was successful before creating an activity.
This prevents misleading activities.
Fixes #909

create activity on successful action

---

app/controllers/auth/registrations_controller.rb
app/controllers/auth/sessions_controller.rb
app/controllers/concerns/session_flash.rb
app/controllers/dashboard_controller.rb
app/models/namespace.rb
app/models/user.rb
app/views/devise/registrations/edit.html.slim
db/migrate/20160510153011_add_namespace_id_to_users.rb
db/migrate/20160526105216_remove_index_on_ldap_users.rb
db/schema.rb
lib/portus/ldap.rb
lib/tasks/portus.rake
spec/api/v2/token_spec.rb
spec/controllers/auth/registrations_controller_spec.rb
spec/controllers/auth/sessions_controller_spec.rb
spec/controllers/namespaces_controller_spec.rb
spec/features/application_spec.rb
spec/features/auth/signup_feature_spec.rb
spec/features/dashboard_spec.rb
spec/integration/login_spec.rb
spec/lib/portus/ldap_spec.rb
spec/models/namespace_spec.rb
spec/models/registry_spec.rb
spec/models/user_spec.rb

This has been done in two steps:
1. First of all I've introduced the `namespace_id` column to the `users`
table. This means that from now own there is no mapping from users and their
personal namespaces through the `username` column, from now on it's done with
a plain SQL foreign key.
2. From the previous step, we get that restricting the username is no longer
needed. Instead, the format of the username has been greatly relaxed, so the
only concerns are:
- It is unique in the DB.
- We can produce a namespace for it. If the username is not a valid
namespace name, then the resulting namespace will have its name altered
so it can be valid. If it cannot be valid, then user creation will fail
(which is very unlikely: this only happens in cases like "?" or something
like that).
Fixes #732
Fixes …

Removed the usage of ldap_name and relax username

---

_includes/header.html
assets/js/topbar.js
assets/stylesheets/layout.less
gulpfile.js

Hi :)
In this PR I'll propose a new model for the topbar. In the actual format, on small screens, the menu overflow the bar and make the links almost disappear.
Initially, the topbar is transparent and when you scroll down the topbar changes to a solid background a little bit transparent:
Now, the menu is hidden on small screen and is showed when click on sandwich button:

New topbar proposal

---

app/views/shared/_notifications.html.slim

With #781 I added a bug :(
When the user sign up or add a new registry two notifications (one float and one fixed) were triggered.
This PR fixes it :+1:

Fixed double alerts bug

---

_includes/desktop-topics.html
_includes/mobile-topics.html
_layouts/post.html
assets/stylesheets/documentation.less
assets/stylesheets/layout.less

Hi :)
@mssola notify me about one bug on "Created with <3 by the SUSE team" documentation menu: 
Analyzing this problem, I saw other issue: when the screen have a small height (and need not to be too small), the quantity of items on the list overflows the screen, then the user lost a piece of menu.
So I designed a new interface for this documentation menu, with a scrollabe menu and added the "Created with <3 by the SUSE team" at the bottom:
And in small screen I put the menu in a dropdown:
I hope that you enjoy it! :)

New design for documentation menu

---

config/initializers/version.rb

It does not make sense to try to fetch the version from git if the deployer has
removed the `.git` directory too.
Fixes #936

version: don't rely on the `.git` directory

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/search.scss
app/controllers/search_controller.rb
app/helpers/search_helper.rb
app/models/namespace.rb
app/models/team.rb
app/views/search/_desktop_categories.html.slim
app/views/search/_mobile_categories.html.slim
app/views/search/_namespaces.html.slim
app/views/search/_repositories.html.slim
app/views/search/_teams.html.slim
app/views/search/index.html.slim
app/views/shared/_header.html.slim
app/views/shared/_search.html.slim
spec/helpers/search_helper_spec.rb

Fixes: #753 
In this PR I updated the search feature to search through Teams and Namespaces too! So, I added a category menuto filter by repository, team and namespace.
The repository search result table is the same as before, I only added "updated_at" column. Then I show in this print a empty result :)
And in small screens:

Search improvements

---

Gemfile
Gemfile.lock

This change has been done because these are the versions that we have
on OBS, and they should be fine.

Upgrading ethon and typhoeus

---

app/models/webhook.rb
spec/models/webhook_spec.rb

Webhooks should handle delete events just like they do push events since
they are not doing anything special.
Fixes #958

webhooks: handle delete events

---

app/models/repository.rb
spec/models/repository_spec.rb

If an already existing tag is pushed again, the digest is updated.
Fixes #826

update digests when updating tags

---

app/controllers/teams_controller.rb
app/policies/team_policy.rb
app/views/admin/teams/index.html.slim
app/views/namespaces/show.html.slim
app/views/teams/_team.html.slim
spec/controllers/teams_controller_spec.rb

Links to hidden teams are not shown anymore. Furthermore, editing hidden
teams is prohibited by both users and admins.
Fixes #970

hide hidden teams and make them unaccessible

---

lib/tasks/portus.rake

This task allows administrators to update usernames with their previous LDAP
names.

lib/tasks: added the `portus:update_ldap_names` task

---

.rubocop.yml
app/controllers/namespaces_controller.rb
app/helpers/namespaces_helper.rb
app/views/namespaces/_namespace.html.slim
config/config.yml
packaging/suse/portusctl/lib/cli.rb
spec/controllers/namespaces_controller_spec.rb

There is a new option 'user_change_visibility' which allows users to
change the visibility of their personal namespace. If this is option is
disabled, only admins can perform this change. This option is enabled by
default and therefore doesn't change the current behavior.
This commit is part of issue #676.

add option to disable change of visibility

---

lib/portus/config.rb
spec/fixtures/config.yml
spec/lib/portus/config_spec.rb

Allow the use of `enabled?` for nested options in the config file. Nodes
are separated with a period and only work for up to 2 nodes at the
moment.
Example:
`APP_CONFIG.enabled?("foo.bar")` instead of
`APP_CONFIG["foo"]["bar"]["enabled"].eql?(true)`

use `enabled?` for nested options

---

app/controllers/team_users_controller.rb
app/views/team_users/create.js.erb
spec/controllers/team_users_controller_spec.rb
spec/features/teams_spec.rb

This commit forces that whenever a Portus admin gets added into a team, it will
have owner privileges. Moreover, this commit also forbids demoting a Portus
admin from being an owner.
Fixes #977

Portus admins are always team owners

---

.rubocop.yml

As I've realized in Travis CI, there are some inconsistencies on the
Lint/ShadowedException cop across Ruby versions. Because of this, we have to
disable the Lint/UnneededDisable cop.

rubocop: disable the Lint/UnneededDisable cop

---

_layouts/post.html

In my previous PR I unintentionally removed the anchor links from documentation page, they are back!

Fix anchor on documentation page

---

app/policies/webhook_policy.rb
spec/policies/webhook_policy_spec.rb

webhook: don't forbid users to see the webhooks on their personal namespace

---

app/models/namespace.rb
spec/models/namespace_spec.rb

One usual pain point that can be solved in `make_valid` is that lots of times
the problem is with the case. Since upper case is not accepted in namespace
names, then it will be converted weirdly. Because of this, from now on the
first thing that `make_valid` will do if the name doesn't match right away, is
to convert the name to downcase. With this commit then, something like `Miquel`
will be converted to `miquel`, instead of `_iquel`, which makes more sense.
See #965

namespace: convert to downcase first on make_valid

---

.rubocop.yml
config/config.yml
config/cronotab.rb
lib/portus/jwt_token.rb
lib/portus/migrate.rb
spec/lib/portus/migrate_spec.rb

An integer should be provided instead. This is better than just taking a
string from the user an calling eval on it. I've added a module that implements
a compatibility layer so this change won't break current setups. That being
said, administrators will get a warning about its deprecation.

Deprecated the usage of "x.minutes" strings in configuration values

---

.rubocop.yml
config/config.yml
lib/portus/jwt_token.rb
lib/portus/migrate.rb
lib/portus/registry_client.rb
packaging/suse/portusctl/lib/cli.rb
packaging/suse/portusctl/spec/options_spec.rb
packaging/suse/portusctl/templates/config-local.yml.erb
spec/lib/portus/jwt_token_spec.rb
spec/lib/portus/migrate_spec.rb
spec/spec_helper.rb

With this option we will be able to workaround docker/distribution#1854.
Moreover, with this we will allow administrators to further tweak how Portus
interacts with the registry.
Moreover, because of this new addition, I felt like groupping registry-related
configurable options would be a good idea, so now all these options are under
the new `registry` section. We are still providing a compatibility layer in the
Portus::Migrate module.
Fixes #1001

Added the registry.catalog_page option

---

app/controllers/namespaces_controller.rb
app/controllers/teams_controller.rb
app/helpers/namespaces_helper.rb
app/helpers/teams_helper.rb
app/policies/namespace_policy.rb
app/policies/team_policy.rb
app/views/namespaces/index.html.slim
app/views/teams/index.html.slim
app/views/teams/show.html.slim
config/config.yml
packaging/suse/portusctl/lib/cli.rb
packaging/suse/portusctl/spec/options_spec.rb
spec/controllers/namespaces_controller_spec.rb
spec/controllers/teams_controller_spec.rb
spec/spec_helper.rb

Options regarding user permissions can be found under the
`user_permission` node in the config file.
The three options are:
* **change_visibility**
permits the user to change the visibility of namespaces he/she owns
* **modify_team**
permits the user to change team attributes, e.g. name or description,
given that he/she is an owners
* **modify_namespace**
permits the user to change namespace attributes, e.g. name, team, or
description, given that he/she is an owners
Note that the previous user restriction regarding namespace visibility
only applied to a user's personal namespace. This has been extended to
all namespaces the user owns.
Resolves #676

introduce more optional user restrictions

---

app/views/shared/_aside.html.slim

Closes #289 
Just added a link to Portus documentation on side menu:
Signed-off-by: Matheus Fernandes <matheus.souza.fernandes@gmail.com>

Added help section to menu

---

app/policies/namespace_policy.rb
spec/policies/namespace_policy_spec.rb

All logged-in users are able to see protected namespaces regardless of
whether or not they are part of the namespace's team.
Fixes #1013

show protected namespaces to all logged-in users

---

app/models/repository.rb
spec/models/repository_spec.rb

Enable the CatalogJob to update the digest of existing tags.
Resolves #828

CatalogJob: update the digests of tags

---

.travis.yml
Gemfile
Gemfile.lock
lib/man_pages.rb
lib/tasks/man.rake
packaging/suse/portus.spec.in
packaging/suse/portusctl/README.md
packaging/suse/portusctl/lib/cli.rb
packaging/suse/portusctl/man/man1/portusctl-exec.1
packaging/suse/portusctl/man/man1/portusctl-help.1
packaging/suse/portusctl/man/man1/portusctl-logs.1
packaging/suse/portusctl/man/man1/portusctl-make-admin.1
packaging/suse/portusctl/man/man1/portusctl-rake.1
packaging/suse/portusctl/man/man1/portusctl-setup.1
packaging/suse/portusctl/man/man1/portusctl.1
packaging/suse/portusctl/man/markdown/portusctl-exec.md
packaging/suse/portusctl/man/markdown/portusctl-help.md
packaging/suse/portusctl/man/markdown/portusctl-logs.md
packaging/suse/portusctl/man/markdown/portusctl-make-admin.md
packaging/suse/portusctl/man/markdown/portusctl-rake.md
packaging/suse/portusctl/man/markdown/portusctl-setup.md
packaging/suse/portusctl/man/markdown/portusctl.md
packaging/suse/portusctl/spec/man_spec.rb

portusctl: added man pages

---

app/models/repository.rb
app/views/repositories/show.html.slim
spec/helpers/repositories_helper_spec.rb
spec/jobs/catalog_job_spec.rb
spec/models/repository_spec.rb

Now Portus will be able to track better updates on repositories and tags.
Moreover, updates will create activities too, and this will also be the case
for crono updates (whenever it makes sense).
Fixes #553

Better reflect updates

---

Gemfile

bcrypt stop being a hard dependency of rails since this [commit](https://github.com/rails/rails/commit/67790644372ad3a771810f1d6d99687d795789ea), so it's totally required here for application tokens.

bcrypt is not a Rails dependency so it's absolutely required in Gemfile

---

app/controllers/admin/registries_controller.rb
app/models/registry.rb
app/views/admin/registries/edit.html.slim
app/views/admin/registries/new.html.slim
db/migrate/20160519110301_add_external_hostname_to_registries.rb
db/schema.rb
spec/factories/registries.rb
spec/models/registry_spec.rb
spec/models/repository_spec.rb

I haven't actually written anything here, I just rebased @jmahowald's pr #888 onto `master`, but it seems to work fine. I'm willing to pick it up if you think there's anything that needs to be done before this can be merged though.
Here's my use case:
Registry configured at `http://registry.my.host:5000`
Portus configured at `http://registry.my.host:3000/portus`
Apache SSL proxying `https://registry.my.host/portus -> http://registry.my.host:3000/portus` and `https://registry.my.host/v2 -> http://registry.my.host:5000/v2`
So in Portus, I have configured the registry as:

Add a parameter for an external hostname field

---

app/models/user.rb
spec/features/auth/login_feature_spec.rb

Should solve #1040.
The mechanism is easy, the specs are tricky (Rubocop and Travis CI agree). Please, bear with me:
1. Once the user model class is loaded, `devise` configures it by mixing in its modules. In our case it mixes in the `validatable` module that contains the validation for the minimum length of a user's password (See [here](https://github.com/plataformatec/devise/blob/v3.5.1/lib/devise/models/validatable.rb#L35)). We have no way to to get rid of this validation during runtime. 
2. In case of an LDAP setup we want devise to leave out the `validatable` module because its validation of password length might be too strict  (#1040). 
3. In the specs the user model has already been loaded. It is not possible to enable the LDAP setting and _renew_ the class definition without a …

Skip validations of devise's validatable module in LDAP setups

---

config/initializers/smtp.rb

In a minimal docker compose type setting it's useful to have smtp turned on and to let the relay handle all the authentication.  Otherwise, you'll have errors about 
`
portus_1       | Net::SMTPSyntaxError (503 AUTH command used when not advertised
portus_1       | ):
`
if using a basic smtp image like namshi/smtp

Allow us to turn off smtp authentication

---

app/models/registry_event.rb
db/migrate/20160927141850_create_registry_events.rb
db/schema.rb
lib/portus/registry_notification.rb
spec/lib/portus/registry_notification_spec.rb

There were a couple of issues with supporting Docker Distribution 2.5.
Hopefully with this commit Portus can handle events coming from this
version.
I've also added more debug logging, so it's easier to check what's going
on.
Fixes #905

Support Docker Distribution 2.5

---

.travis.yml
Gemfile
Gemfile.lock

Apparently a `gem update --system` is needed in order to install
`binman ~> 5.1.0`. Moreover, I've also specified the exact binman
version that we want just in case.
Finally, I've also taken the chance to update the ruby versions being
tested to their latest patch-level releases. The ruby versions being used
for SLE12 and openSUSE are left untouched.

Fix builds for ruby 2.3.x

---

lib/tasks/portus.rake

The task did not work, since it tried to get the manifest from the
repository name without the namespace.

Fix portus:update_tags task.

---

Dockerfile

as the rails image will soon be deprecated by 2016-12-31
(see https://hub.docker.com/r/library/rails/)
another benefit is that the ruby image is more than 100mb smaller
in size than the rails image
it contains all necessary dependencies but nodejs, which is added
via the Dockerfile
also the version (rails:4.2.2) of the image was lower than the
version that is actually used (4.2.6) from the Gemfile
I have chosen ruby:2.3.1 as it has been the latest in .travis.yml

use ruby:2.3.1 container for the docker compose setup

---

app/controllers/admin/users_controller.rb
app/views/application_tokens/create.js.erb
app/views/application_tokens/destroy.js.erb
app/views/comments/create.js.erb
app/views/comments/destroy.js.erb
app/views/namespaces/create.js.erb
app/views/team_users/create.js.erb
app/views/team_users/destroy.js.erb
app/views/teams/create.js.erb
app/views/webhook_headers/create.js.erb
app/views/webhook_headers/destroy.js.erb
spec/features/admin/users_spec.rb
spec/features/application_tokens_spec.rb
spec/features/namespaces_spec.rb
spec/features/teams_spec.rb

there have been different wordings for some actions like creating or
removing users, comments, tokens, namespaces etc.
fixes #885
supersedes #923 
Signed-off-by: Maximilian Meister <mmeister@suse.de>
NOTE: I am probably still missing the fixes for the unit tests, as I had some trouble with running them, 606 of them failed when run inside the container, which I found a bit strange for a small patch like this, a lot of `Factory not registered` errors etc.
I have also run them on my host, which required me to setup a mysql db like in `.travis.yml`, and I got 132 errors. I guess there is sth wrong with the setup (a lot of permission errors, and missing `phantomjs`)
I have read https://github.com/SUSE/Portus/wiki/How-we-test-Portus but it was not yet clear if I should run the tests on my host …

standardize on notification messages

---

packaging/suse/portus.spec.in

We don't need the rake task for creating the man pages in the RPM.
Otherwise, running the assets precompilation fails because it requires
md2man gem which is in the development group.

RPM: remove man pages rake task from the RPM

---

app/controllers/application_controller.rb
config/initializers/checks.rb
lib/portus/checks.rb
spec/spec_helper.rb

It's not a good idea to perform this checks for *every* request.
Instead, they will be checked only once after booting up.

Runtime checks will only be performed once

---

packaging/suse/make_spec.sh

in order to install this gem, it needs libffi-devel install, since
this is a native gem. Otherwise, it won't build for other archs other
than x86_64.

fix ffi gem installation

---

app/views/webhooks/_detail.html.slim
app/views/webhooks/show.html.slim

webhooks: hide passwords

---

spec/controllers/admin/activities_controller_spec.rb

due to the randomness there is a chance that a number occurs multiple
times, which causes a validation error and the test to fail
Signed-off-by: Maximilian Meister mmeister@suse.de

prevent validation error in the specs

---

Dockerfile
Gemfile
Gemfile.lock

this removes the obs dependency for the deb package and also
enables running local rspec without having to care about providing
phantomjs
Signed-off-by: Maximilian Meister mmeister@suse.de

provide phantomjs via rubygem

---

Gemfile
config/environments/test.rb

now you can just run `bundle exec rake spec:models` after making some change to a model e.g. and the tests run much faster, as the successful activerecord logs aren't written anymore in the test env
you still have to provide the mysql test database and `phantomjs` though...

enhance the way of running local specs

---

app/views/devise/registrations/new.html.slim

This way, both this form and the "admin create user" form follow the
same field order.
Fixes #1115
Signed-off-by: Miquel Sabaté Solà msabate@suse.com

The sign up form now follows a consistent order

---

packaging/suse/portusctl/lib/configurator.rb
packaging/suse/portusctl/lib/registry.rb
packaging/suse/portusctl/lib/runner.rb
packaging/suse/portusctl/spec/man_spec.rb
packaging/suse/portusctl/spec/registry_spec.rb

If the admin is using the `--local-registry` then we can help the admin
to play safer:
1. If the docker-distribution-registry RPM has not been installed, then
the user can decide to install it then.
2. If the RPM exists, then we warn the user about the fact that the
config will be overwritten and ask for permission to proceed.
3. All this can be forced by providing the "PORTUSCTL_FORCE" environment
variable.
Fixes #712
Signed-off-by: Miquel Sabaté Solà msabate@suse.com

portusctl: show a warning if the local registry has not been installed

---

_features/1_Synchronizing-the-Registry-and-Portus.md

Right now if you will click on 'notifications' link on the http://port.us.org/features/1_Synchronizing-the-Registry-and-Portus.html you will get 404 page. This PR will fix it.

Fix notifications url

---

packaging/suse/package_and_push_to_obs.sh
packaging/suse/portus.spec.in

otherwise the resulting Gemfile is different and this causes errors

add gem patches to the rpm

---

app/views/layouts/authentication.html.slim
config/initializers/assets.rb

Removed auth/cover.js from precompilation

---

packaging/suse/portusctl/lib/configurator.rb

Because running portusctl as root, creates some files under tmp/cache
which after will be used by the rails application. Specifically, the
portus-check files. Unless we change the ownership, we'll get a
permission problem

[package] change ownership of tmp/cache after setting up the database

---

packaging/suse/portusctl/lib/configurator.rb

If we reinstall apache2, permissions and ownership of dir
/etc/apache2/ssl.key is reset to root and "read only by user root"
which make user wwwrun not being able to use this key
wwwrun is the user which Portus runs and needs to access to that
certificate
We used to change the ownership and create a symlink, but as stated,
reinstalling apache2 changes the ownership back.
Thus, the solution is to do it the other way around, move the key
outside apache dirs and instead create a symlink

fix permissions on apache2 reinstall

---

packaging/suse/portus.spec.in
packaging/suse/portusctl/lib/configurator.rb

This should be owned by wwwrun:www but if this is an update, it is
owned by root. Thus, we need to force it to be owned by wwwrun:www
This follows up with the fix in 496976

fix ownership for tmp/cache directory

---

packaging/suse/portusctl/lib/cli.rb
packaging/suse/portusctl/spec/options_spec.rb

portusctl: show proper output for unknown flags

---

Gemfile
Gemfile.lock

For now puma was included in the development/test bundle, but in some
deployments it might be more convenient to also use puma for production.
With this commit, you only need to set the `PORTUS_PUMA_DEPLOYMENT` to
"yes" in order to accomplish that.

Optionally add puma in the bundle in production

---

.rubocop.yml
app/helpers/namespaces_helper.rb
app/helpers/teams_helper.rb
app/policies/namespace_policy.rb
app/policies/team_policy.rb
config/config.yml
packaging/suse/portusctl/lib/cli.rb
packaging/suse/portusctl/lib/configurator.rb
packaging/suse/portusctl/man/man1/portusctl-setup.1
packaging/suse/portusctl/man/markdown/portusctl-setup.md
packaging/suse/portusctl/spec/options_spec.rb
spec/controllers/namespaces_controller_spec.rb
spec/controllers/teams_controller_spec.rb
spec/spec_helper.rb

This allows restricting creation of teams or namespaces to admins, while
allowing owners to manage their own teams/namespaces.

Split user permissions between create and manage

---

app/assets/javascripts/application.coffee
app/assets/stylesheets/application.scss

bootstrap-sprockects is the same as bootstrap, but with the files
splitted so it's easier to embed in sprocket's workflow.

assets: removed redundant bootstrap reference

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.coffee
app/assets/javascripts/auth/registrations.coffee
app/assets/javascripts/dashboard.coffee
app/assets/javascripts/namespaces.coffee
app/assets/javascripts/repositories.coffee
app/assets/javascripts/teams.coffee
packaging/suse/patches/0_change_versions.gem.patch

It's causing troubles in situations where assets are served by NGinx or
haproxy, and we are not using it anyways. Moreover, this is a first step
if we want to take a look at other frameworks such as React or Vuejs.
Moreover, I've also updated the packaging patch.

Remove turbolinks

---

config/secrets.yml
lib/portus/checks.rb
packaging/suse/portus.spec.in
packaging/suse/portusctl/lib/configurator.rb
spec/controllers/errors_controller_spec.rb

The secrets.yml file will rely more on environment variables, so it's
easier to deploy on Docker images. Morever, the RPM no longer needs to
remove the database.yml and secrets.yml files

Rely more on environment variables

---

app/views/devise/registrations/new.html.slim

After changing the email to become the second field in order, `autofocus` attribute was left there instead of added to the first field.

Autofocus on registrations/new

---

app/assets/javascripts/teams.coffee

Team description field now being cleared when adding a new team without reloading the page.
If the previous value was left uncleared on purpose, please do not consider this PR. I'm new to the project, just trying to contribute as much as I can. :)

team: description field cleared

---

app/assets/javascripts/namespaces.coffee

Similar to https://github.com/SUSE/Portus/pull/1213 but on namespace's form.

namespace: description and team cleared when form is displayed

---

app/assets/javascripts/application.coffee

As you already know. `#= require bootstrap-sprockets` will include [all bootstrap plugins](https://github.com/twbs/bootstrap-sass/blob/master/assets/javascripts/bootstrap-sprockets.js). As far as I could investigate, Portus is using only 3 (tooltip, popover, tab) of them.
**Update:** this one different from the others has testing failing in all environments, so I probably broke something. :sweat_smile: I'll investigate and get back to this.

Removed unused bootstrap plugins

---

CHANGELOG.md
app/views/namespaces/create.js.erb
app/views/teams/show.html.slim
spec/features/namespaces_spec.rb

Changed icon to fa-plus-circle.
After registering a namespace the icon on action maintains behavior.
Added automatic test to validate the behavior.
Signed-off-by: Ricardo Mateus <rjmateus@gmail.com>

Icon incoherent in teams page on add namespace action button

---

packaging/suse/patches/0_change_versions.gem.patch

in commit
79fb15164f32a3da86b39e7a7b2340588830c8c9
portile was renamed to portile2 in the patch, which broke the
Gemfile.lock after applying such patch

[packaging] fix portile name/version in patch

---

app/controllers/api/v2/tokens_controller.rb
app/models/registry/auth_scope.rb

Otherwise token generation may fail in some cases.

Honor external_hostname in token generation

---

.travis.yml
Gemfile
Gemfile.lock
lib/portus/registry_client.rb
packaging/suse/patches/0_change_versions.gem.patch
spec/lib/portus/registry_client_spec.rb
spec/vcr_cassettes/registry/delete_blob.yml
spec/vcr_cassettes/registry/delete_disabled.yml
spec/vcr_cassettes/registry/delete_missing_blob.yml
spec/vcr_cassettes/registry/get_image_manifest.yml
spec/vcr_cassettes/registry/get_missing_image_manifest.yml
spec/vcr_cassettes/registry/invalid_delete_blob.yml
spec/vcr_cassettes/registry/successful_authentication.yml
spec/vcr_cassettes/registry/wrong_authentication.yml

- The arel and json gems needed to be upgraded, otherwise some pages
were utterly broken.
- VCRs were broken, and previous versions didn't catch that.
- Some gems related to testing had to be upgraded (e.g. vcr)
- I've added a `cache` section in the travis file to speed things up,
and I've updated the rubies being used to the latest stable releases.

Added support for Ruby 2.4

---

Gemfile
lib/tasks/assets.rake
packaging/suse/portus.spec.in

- webpack-rails is also needed at runtime
- Make sure that yarn only operates offline

packaging: some fixes

---

bin/crono

This will help in RPM contexts where portusctl can give use the proper
gem setup.

crono: use portusctl if available

---

app/controllers/api/v2/tokens_controller.rb
app/models/registry.rb
app/models/registry/auth_scope.rb

This method is similar to Registry.find_by(hostname ...) but it also
fall backs to the external hostname column.

models: added the `find_by_hostname` method

---

Vagrantfile

- npm install of yarn, webpack
- yarn install inside /vagrant directory
- running webpack locally on the portus web vm

fix vagrant setup

---

config/application.rb

Portus Currently displays all date/time in UTC, with this change, if the TZ environment variable is present the dates are displayed in this timezone, else they are displayed as UTC.
Signed-off-by: Yann Lopez <l@lonewulf.net>

Portus now reads the TZ env variable to display dates correctly

---

lib/portus/ldap.rb
spec/lib/portus/ldap_spec.rb

When creating users on LDAP, make sure that the email won't clash. If
that was to happen, then set the email to nil so the user has to enter
the email manually.
Fixes #1302

ldap: avoid clashes on emails

---

docker-compose.yml

The name has been changed to a proper one (by taking the official
docker image as a reference), and a `depends_on` has been added, since
the crono service needs the image built in the portus service.
See #1313

compose: Try to fix dependencies on services

---

.travis.yml
Dockerfile
Gemfile
Gemfile.lock
app/assets/javascripts/alert.js
app/assets/javascripts/modules/users/pages/sign-in.js
app/assets/javascripts/modules/users/pages/sign-up.js
package.json
spec/controllers/admin/activities_controller_spec.rb
spec/features/admin/registries_spec.rb
spec/features/admin/users_spec.rb
spec/features/application_spec.rb
spec/features/application_tokens_spec.rb
spec/features/auth/login_feature_spec.rb
spec/features/auth/profile_feature_spec.rb
spec/features/auth/signup_feature_spec.rb
spec/features/dashboard_spec.rb
spec/features/forgotten_password_spec.rb
spec/features/namespaces_spec.rb
spec/features/repositories_spec.rb
spec/features/teams_spec.rb
spec/support/capybara.rb
spec/support/wait_for_events.rb

- Moved from `precise` to `trusty` in travis
- https://blog.travis-ci.com/2017-07-11-trusty-as-default-linux-is-coming
- Updated `.travis.yml`
- Updated `capybara` gem
- Updated `poltergeist` gem
- Removed `phantomjs`gem 
- Removed unnecessary `wait_until`
- Removed unnecessary `wait_for_effect_on`
- Using `have_current_path` matcher instead of `eq`
- Fixed poltergeist js error on sign in/up pages fadeIn
- Fixed two failing tests after capybara update
- Fixed `admin/activities_controller_spec.rb` flaky test
- Many minor enhancements
- Fixed webmock dependency tree 
- It was blocking the tests after .travis.yml changes 
- Also causing `ruby-head` to fail
- Updated `mysql2`gem
-  It was causing conflict in travis for some reason after caching bundle

Improved testing

---

lib/tasks/assets.rake
packaging/suse/package_and_push_to_obs.sh

The node_modules.tar.gz file, even if compressed, is quite heavy and we
don't want to put this burden into our CI process. For this, we will
have to upload the latest yarn.lock file in OBS as well.

packaging: upload the node_modules when needed

---

app/assets/javascripts/modules/repositories/pages/show.js
app/assets/javascripts/shared/components/alert.js
app/helpers/repositories_helper.rb
app/views/tags/show.html.slim
spec/helpers/repositories_helper_spec.rb

- Not showing the flashy message "Unable to fetch newer tags data" for every polling.
- Showing "No vulnerabilities found" on tags#show panel istead of an empty space.

Added latest missing changes from security scanning PR (#1289)

---

bin/crono

In production it might happen that the crono process is started before
the portus process (e.g. a containerized setup with docker-compose or
Kubernetes). In such a case, we have to be sure that the process running
the migration is the main Portus one, because otherwise the `init`
script from portus won't be able to run successfully, and thus it won't
ever run `rake db:seed` on initialization.

crono: don't let crono run the migrations

---

examples/compose/docker-compose.insecure.yml
examples/compose/docker-compose.yml
examples/compose/registry/config.yml

In the compose examples, the registry container defines the storage volume as `/registry_data`. However, the path that is exposed as a volume in the Registry Dockerfile is `/var/lib/registry`
Docker Compose automatically creates an anonymous volume if the `Volume` parameter defined in the Dockerfile is not mounted as a volume. This results in the creation of multiple anonymous empty volumes, and is a general annoyance.
This PR fixes that by changing the registry path to the one that is defined in the registry Dockerfile. Also I've changed the nginx image to use the alpine variant as well to save space.

[Examples] Change storage path for registry container

---

CONTRIBUTING.md
app/jobs/catalog_job.rb
config/environments/production.rb
config/environments/staging.rb

With this commit administrators will be able to set the log level of
their Portus instance through the `PORTUS_LOG_LEVEL`. This will be
possible in production and staging, and it's meant to be used in
exceptional cases (e.g. something is really wrong with the `crono`
process and the administrator wants to restart it with `debug` mode for
a while).

production: make the log level configurable

---

bin/check_db.rb
lib/portus/db.rb
spec/lib/portus/db_spec.rb

This has been extracted both from
https://github.com/openSUSE/docker-containers and #1353, since it will
be useful for #1357 as well.

Added a way to check the DB's status

---

app/controllers/health_controller.rb
config/config.yml
config/routes.rb
lib/portus/db.rb
lib/portus/health.rb
lib/portus/health_checks/clair.rb
lib/portus/health_checks/db.rb
lib/portus/health_checks/registry.rb
packaging/suse/portusctl/lib/cli.rb
packaging/suse/portusctl/man/man1/portusctl-setup.1
packaging/suse/portusctl/man/markdown/portusctl-setup.md
spec/controllers/health_controller_spec.rb
spec/vcr_cassettes/health/clair-bad.yml
spec/vcr_cassettes/health/clair-ok.yml
spec/vcr_cassettes/health/ok.yml

Portus now provides two new endpoints:
- /_ping: used as a simple check. It will always return 200.
- /_health: returns a JSON response containing the status report of the
different configured components.
Fixes #1357 

Implemented health checks for Portus

---

Gemfile.lock

This release includes some fixes that users have already faced.
See #1379
See mssola/cconfig#3

Upgraded cconfig to 1.1.1

---

Gemfile
Gemfile.lock
app/controllers/help_controller.rb
app/views/help/index.slim
app/views/shared/_aside.html.slim
config/initializers/swagger.rb
config/routes.rb
spec/controllers/help_controller_spec.rb
spec/features/help_spec.rb
spec/views/help/index.html.slim_spec.rb

I've done two things in this commit:
1. I've added a Help page, so the "Help" section on the aside is no
longer just a link, but a proper page inside of Portus. For now I've
added a couple of interesting links.
2. In development (and test) environments users will be able to access
to `/api/documentation` which is a page generated by the Grape
Swagger API gem. This way users can test first hand the API.
See #1372

Added a help page with API Documentation

---

app/assets/javascripts/modules/namespaces/components/table.js
app/assets/javascripts/shared/mixins/table-sortable.js
app/assets/javascripts/vue-shared.js
app/views/namespaces/components/_panel.html.slim
app/views/namespaces/components/_table.html.slim
app/views/namespaces/partials/_special_namespaces.html.slim
package.json
spec/features/namespaces_spec.rb
spec/features/teams_spec.rb
yarn.lock

So far the column sorting was possible but user wasn't able
to share the state of it to someone through copying and pasting url.
Now every sorting action the user makes on the namespaces table,
for example, will create a new url state that can be visited and
navigated back and forth.
Fixes #1373

js: added table sortable mixin; namespaces using it

---

app/assets/javascripts/modules/namespaces/components/panel.js
app/assets/javascripts/modules/namespaces/components/table.js
app/assets/javascripts/shared/components/table-pagination.vue
app/assets/javascripts/shared/mixins/table-paginated.js
app/assets/javascripts/shared/mixins/table-sortable.js
app/views/layouts/application.html.slim
app/views/namespaces/components/_panel.html.slim
app/views/namespaces/components/_table.html.slim
app/views/namespaces/partials/_special_namespaces.html.slim
spec/features/namespaces_spec.rb
spec/features/teams_spec.rb

So far the pagination was possible but user wasn't able
to share the state of it with someone by copying and pasting url.
Now every pagination action the user makes on the namespaces table,
for example, will create a new url state that can be visited and
navigated back and forth.
Fixes #1390

js: added table paginated mixin; namespaces using it

---

app/assets/javascripts/modules/namespaces/components/new-form.js
app/assets/javascripts/modules/namespaces/services/namespaces.js
app/assets/javascripts/vue-shared.js
app/assets/stylesheets/includes/forms.scss
app/controllers/namespaces_controller.rb
app/views/layouts/application.html.slim
app/views/namespaces/components/_form.html.slim
package.json
spec/features/namespaces_spec.rb
yarn.lock

The validation so far was fully done on the server side and
the feedback was through the float alert that disappears in 5 seconds.
Not the best experience for the users.
Now, for each field (name and team), we have an inline feedback validation.
User will only see a validation message on the float alert in unexpected
situations.
Fixes #1376

js: added inline validation for namespace's new form

---

app/assets/javascripts/modules/namespaces/components/new-form.js

After the refactoring of namespace's new form, the reset
of the fields were causing an unexpected behavior. Validation
was being fired again and causing ausing unnecessary ajax
requests and also breaking temporarily the name validation.
Fixes #1406

js: fixed after namespace creation behavior

---

app/assets/javascripts/modules/namespaces/services/namespaces.js
app/assets/javascripts/modules/repositories/services/repositories.js
app/assets/javascripts/modules/repositories/services/tags.js
app/assets/javascripts/vue-shared.js
app/views/layouts/application.html.slim

VueResource was not considering any path to be included in
its root url. So when portus was set up using RAILS_RELATIVE_URL_ROOT,
the url requests were wrong and data didn't show up.
To fix this we are now setting VueResource root url based on
rails `root_url` value.
Fixes #1421

js: fixed vue-resource root url based on rails root_url

---

app/models/repository.rb

If a tag will be overwritten its created_at date stays the same. So sorting the tags by this date results in a wrong order. The updated_at date will be changed anytime a tag is overwritten. So such a tag will appear at the top of the tag list if they are sorted by this date.

Sort tags by updated_at date not by created_at

---

app/controllers/application_controller.rb
app/controllers/concerns/headers.rb
app/controllers/explore_controller.rb
examples/compose/nginx/nginx.conf
spec/controllers/dashboard_controller_spec.rb
spec/controllers/explore_controller_spec.rb

For now we are adding the X-UA-Compatible header so it works well for IE
with compatibility mode on.

Added a default_headers method for controllers

---

app/models/namespace.rb
app/models/team.rb
app/models/user.rb
app/policies/namespace_policy.rb
spec/features/admin/users_spec.rb
spec/models/namespace_spec.rb
spec/models/team_spec.rb
spec/models/user_spec.rb
spec/policies/namespace_policy_spec.rb

Currently we have a problem when a user is removed and added back
to Portus. The team and namespace associated with that user are not
removed. So, when an admin tries to create a user or an user tries
to create an account, an error mentioning that there's already a
namespace with that username is shown.
With this patch we avoid that by adding an incremental number to the
end of the name. For example, if username is `brian` and there's
already a namespace/team with that name, `brian0` namespace and team
will be created instead. If `brian` gets removed again, next time it
will be `brian1` for both namespace and team.
Remembering that we should remove this once we implement the
namespace/team removal.
Fixes #1269

Fixed the namespace and team name clashes

---

Dockerfile
examples/development/compose/init

The image being used by the docker-compose dev setup has been reduced
from almost 1GiB to 586MiB. This has been done by:
- Switching from library/ruby:2.3.1 to opensuse/ruby:2.3.
- Removing unneeded clutter that is only needed when building.

Reduced the size of the dev Docker image

---

app/views/devise/sessions/new.html.slim

In app/views/devise/sessions/new.html.slim, the autocomplete attribute was set to false rather than 'off' (like in other files). 
It was also not compliant with W3C standards.

Changed autocomplete from false to off

---

app/assets/javascripts/main.js
app/assets/javascripts/modules/admin/registries/components/form.js
app/assets/javascripts/modules/admin/registries/index.js
app/assets/javascripts/modules/admin/registries/pages/edit.js
app/assets/javascripts/modules/admin/registries/pages/new.js
app/assets/javascripts/modules/admin/registries/service.js
app/assets/stylesheets/pages/registries.scss
app/controllers/admin/registries_controller.rb
app/helpers/registries_helper.rb
app/services/base_validate_service.rb
app/services/registries/validate_service.rb
app/views/admin/registries/components/_form.html.slim
app/views/admin/registries/edit.html.slim
app/views/admin/registries/index.html.slim
app/views/admin/registries/new.html.slim
app/views/shared/_notifications.html.slim
lib/api/v1/registries.rb
package.json
spec/api/grape_api/v1/registries_spec.rb
spec/controllers/admin/registries_controller_spec.rb
spec/features/admin/registries_spec.rb
spec/helpers/registries_helper_spec.rb
spec/services/registries/validate_service_spec.rb
yarn.lock

The registry validation was done completely on the server side. With
this, we bring some validation to the client side to antecipate and improve
the user's experience.
Also adds a hint in the registries#index pages to help the user know if the
registry that was set is reachable or not. The reachable status is cached for
30 minutes unless the user updates the registry.
Fixes #1355

Added some registry validation and status

---

app/assets/javascripts/modules/repositories/components/tags-table.vue
app/assets/javascripts/shared/mixins/table-paginated.js

After implementing the new pagination on other pages, we've
extracted its code to a mixin and forgot to update the tags'
table.
Fixes #1454

Fixed tags table pagination

---

app/models/registry_event.rb

This PR has no impact it just updates model annotation comment to the latest state of the annotation gem. Its quite annoying that the workspace is always dirty without actually doing anything in that particular file.

Fix concise model annotation

---

app/controllers/dashboard_controller.rb
app/policies/public_activity/activity_policy.rb
db/migrate/20171014192702_add_indexes_to_activities.rb
db/schema.rb

We had a performance issue with the recent activities in
the dashboard page.
A new index was added and the queries were also improved
with less JOINs, an order and limit.
Previous query
`
SELECT  DISTINCT `activities`.* FROM ( (SELECT `activities`.* FROM ( (SELECT `activities`.* FROM ( (SELECT `activities`.* FROM ( (SELECT `activities`.* FROM `activities` INNER JOIN teams ON activities.trackable_id = teams.id INNER JOIN team_users ON teams.id = team_users.team_id WHERE (activities.trackable_type = 'Team' AND team_users.user_id = 2)) UNION ALL (SELECT `activities`.* FROM `activities` INNER JOIN namespaces ON activities.trackable_id = namespaces.id INNER JOIN teams ON teams.id = namespaces.team_id INNER JOIN team_users ON teams.id = team_users.team_id WHERE (activities.trackable_type = …

Improved recent activities sql queries performance

---

Gemfile
Gemfile.lock
config/initializers/environment_check.rb

Some environment variables are extremely important when deploying
Portus. This commit makes Portus raise an exception during
initialization process when there's something off about these
environment variables.
Fixes #580

Perform some checks on some environment variables

---

app/models/namespace.rb
config/routes.rb
spec/factories/namespaces.rb
spec/models/namespace_spec.rb

Update Model and Route annotation and make them concise with default ruby annotate_models.
its related to #1324
Signed-off-by: Vadim Bauer <bauer.vadim@gmail.com>

Update Model and Route annotations and make them concise with defaults

---

lib/portus/migrate.rb

Sometimes in some contexts the `minutes` method might return a string.
This has never happened to us, but it's better to be safe than sorry.

Force the integer conversion

---

app/assets/stylesheets/components/layout.scss

I wasn't able to reproduce #939 by just testing with smaller resolutions (chrome stable and firefox 57b). I decreased the width and I was able to have the same result as reported. 
So, I removed the fixed width that was probably the reason why that happened before. I'm not sure why the width was there but I think it was a problem in the past with old browsers but now it's safe to just remove it.
Fixes #939

Removed fixed width of search input

---

Dockerfile

I've tried to build portus image again from master with the docker-compose setup and I got
```
Your Ruby version is 2.3.3, but your Gemfile specified >= 2.4
```
I went to the Dockerfile and saw that there still some `2.3` references. Ruby is now `2.4.x` but the bundler gem installed is `1.10.6`. And now I get
```
Your Ruby version is 2.4.1, but your Gemfile specified >= 2.4
```
We need to package `ruby2.4-rubygem-bundler` with a recent version (1.12.x at least if my research wasn't wrong).

Dockerfile: updated ruby packages to 2.4

---

config/initializers/swagger.rb
lib/api/root_api.rb

In a couple of places (around the API) there was a check for the
PORTUS_CHECK_SSL_USAGE_ENABLED environment variable. Doing this is wrong
because it skips the fact that this is the default behavior as defined
in the main config.yml file. So, the `APP_CONFIG.enabled?` method should
be used instead.

Properly check SSL usage requirements

---

app/models/repository.rb
app/models/tag.rb
app/validators/unique_tag_validator.rb
db/migrate/20171031112721_remove_index_on_tag_name_repository_id.rb
db/schema.rb
spec/controllers/tags_controller_spec.rb
spec/lib/portus/db_spec.rb
spec/models/repository_spec.rb
spec/models/tag_spec.rb
spec/rails_helper.rb

Even if the case sensitivity is set to true when you add a uniqueness
constraint in Ruby on Rails, it happens that in MariaDB/MySQL this is
not correctly handled when this constraint is coupled with another
column. In our case, the uniqueness constraint was between tag name and
repository. In this case, in MariaDB the evaluated key for the
uniqueness index was case insensitive (while in PostgreSQL everything
went as expected). This means that for two tags named "tag" and "TAG"
and inside of the repository "4", the evaluated keys were "tag-4" and
"TAG-4", and in MariaDB they were considered equal, hence it failed.
I've tried multiple solutions, but they all failed:
- Explicitly setting the case_sensitive property on the Rails' side.
- Changing the collation for the table, column, and …

Added custom validator for the uniqueness of tags 

---

app/assets/javascripts/modules/users/components/application-token-panel.js

This was a missing change done while fixing the profile form.

js: prevent app token link to be clickable when disabled

---

app/assets/javascripts/shared/mixins/table-sortable.js

This will prevent an error if no prefix is declared when
using a component.

js: added default prefix value to sortable mixin

---

lib/api/entities.rb
spec/api/grape_api/v1/tags_spec.rb
spec/models/repository_spec.rb

It's not guaranteed from the DB that the author cannot be null.
Moreover, it happened to me that the author of a tag was nil, and so
Portus crashed when requesting this info through the API.
This commit simply sets the author info to null if the author is also
null.

api: fixed crash on null author of a tag

---

lib/api/v1/users.rb

This is already done in other endpoints of the API, but this was weirdly
missing for users.

api: present a user object on create/update

---

app/assets/javascripts/modules/namespaces/components/edit-form.js
app/assets/javascripts/modules/namespaces/components/new-form.js
app/assets/javascripts/modules/namespaces/pages/index.js
app/assets/javascripts/modules/namespaces/pages/show.js
app/assets/javascripts/modules/repositories/components/delete-tag-action.vue
app/assets/javascripts/modules/repositories/pages/show.js
app/assets/javascripts/modules/teams/components/new-form.js
app/assets/javascripts/modules/teams/pages/index.js
app/assets/javascripts/modules/teams/pages/show.js
app/assets/javascripts/plugins/eventbus.js
app/assets/javascripts/utils/eventbus.js
app/assets/javascripts/vue-shared.js

More elegant way of using event bus pattern. This will avoid us to be importing eventbus all the time.
I'll do the same with `Alert`.

js: changed eventbus to plugin

---

_posts/2017-07-19-security-scanning.md
_posts/2017-11-23-portusctl.md
_site/blog/index.html

This new blog post describes why we re-implemented portusctl, and what's
the future for it.

blog post: The new portusctl

---

app/assets/javascripts/modules/teams/components/new-form.js
app/assets/javascripts/modules/teams/service.js
app/assets/javascripts/polyfill.js
app/controllers/teams_controller.rb
app/views/teams/components/_form.html.slim
spec/features/teams_spec.rb

Previously the inline validation was being done only over the scoped
teams current user had access too without their hidden team.
This way when the user tried to create a team with their own hidden name
or another user's name, an error happened.
With this patch the error appears inline as we expect from validation.
I also changed the polyfills syntax import.

js: fixed team name validation behaviour

---

app/controllers/api/v2/events_controller.rb
app/models/registry_event.rb
bin/background.rb
db/migrate/20171213093923_add_status_and_data_to_registry_event.rb
db/migrate/20171213094038_remove_repository_and_tag_from_registry_event.rb
db/schema.rb
lib/portus/background/registry.rb
lib/portus/background/security_scanning.rb
lib/portus/registry_notification.rb
spec/lib/portus/background/registry_spec.rb
spec/lib/portus/background/security_scanning_spec.rb
spec/lib/portus/registry_notification_spec.rb
spec/support/registry_events.rb

From now on, registry notifications (image got pushed, image deleted)
will be handled entirely in the background. Portus itself will only
create the event on the DB, and it will expect for it to be handled
automatically by the background process.
Fixes #940
See #1353 and #1526

background: added registry event handling

---

Gemfile
Gemfile.lock

A first step to fix the packaging breakage is to pin down exactly which
gems we have to support. This commit updates the Gemfile so we pick the
gem versions that we agreed to support.

Updated gem versions to match supported ones

---

Gemfile
packaging/suse/portus.spec.in

Since the very beginning we've added some code blocks in the Gemfile
that run conditionally. This was bad practice but it worked for us. This
is no longer the case: current builds fail because bundle exits with a
non-zero code after checking that the Gemfile.lock produced is not the
same.
Thus, let's do things properly: use groups instead. I've done the
following:
- Removed the `packaging?` method since it's not needed anymore.
- Added an `assets` group that will be excluded when installing gems.
- Explicitely exclude `development` and `tests` instead of doing it on
an ugly `unless` block.
- Removed the conditional on the `puma` gem. People are expected to run
Portus with puma always.

packaging: do not modify the Gemfile file

---

packaging/suse/README.install
packaging/suse/make_spec.sh
packaging/suse/package_and_push_to_obs.sh
packaging/suse/portus.spec.in

This commit is a follow-up of bd383fba329b6256fdd0bb6d1a07fa98b12aeff0,
and it adapts all the packaging scripts on the idea that the Gemfile and
the Gemfile.lock files cannot be touched. After this commit, the portus
RPM builds again and it's cleaner than ever.
First of all, the `make_spec.sh` has been heavily modified, while
polishing some rough edges (e.g. proper debug functions). It will
require a specific bundler version, because now it will be taken from
the gem requirements instead of the `spec.in` file. The biggest change
is to only use `bundler` for anything related to gems. To list the gems
to be added as dependencies we are using now `bundle show`, which has
the knowledge of gem groups as defined in the previous commit. This way,
without modifying the Gemfile.lock file, we can …

packaging: changed how we build dependencies

---

.travis.yml
packaging/suse/package_and_push_to_obs.sh

This is important when generating the spec file and submitting it to
OBS.

ci: explicitely set the bundler version to be used

---

config/initializers/version.rb
packaging/suse/portus.spec.in

This also applies to containerized deployments, because they simply install the RPM.
Fixes #1023

Show the commit even in the RPM

---

config/initializers/draw_def.rb
config/routes.rb
config/routes/admin.rb
config/routes/namespaces.rb
config/routes/registry_api.rb
config/routes/repositories.rb
config/routes/root.rb
config/routes/teams.rb
config/routes/users.rb

In order to clean up the mess in the routes.rb file, we split routes.rb into several modules which ar later loaded via "draw" in the routes.rb file.
With suggested changes from #1563 applied.

Split routes into several files

---

config/environments/development.rb

When running the in container and development mode this message is displayed
```
portus_1      | Cannot render console from 172.18.0.1! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
```
the PR will make sure this message is not displayed and allow also debugging from local networks.
more about the option 
https://github.com/rails/web-console#configweb_consolewhitelisted_ips

Get red of console warnings when running as Container in development

---

packaging/suse/make_spec.sh
packaging/suse/portus.spec.in

To ease up maintenance, we should add a `Provides: bundled(JS) =
VERSION` line for each JS library. This commit uses yarn to list all
dependencies.

packaging: adding bundled for JS libraries

---

lib/portus/registry_client.rb
spec/lib/portus/registry_client_spec.rb
spec/models/registry_spec.rb
spec/vcr_cassettes/health/clair-bad.yml
spec/vcr_cassettes/health/clair-ok.yml
spec/vcr_cassettes/health/ok.yml

Registry Client should probe that the /v2/ path reachable and that we accept 200 responses as well.
fixes #1486
Going straight to the /v2/ allows us to know we are targeting the right Registry.
We could also check for the header
```yml
docker-distribution-api-version:
- registry/2.0
```
to make sure we are really talking to the registry.
makes also https://github.com/SUSE/Portus/tree/master/examples/compose usable again.

Registry Client should probe the /v2/ path and accept more return codes

---

Gemfile.lock

Some development gems needed an upgrade because they were vulnerable and
Github was complaining about it (even if it's totally fine since it's
stuff that we don't care in production...)

Updated vulnerable development gems

---

packaging/suse/rubygem_check.rb

This script will only work if you have previously run `make_spec.sh` and
you are on `packaging/suse`. Then, it will report:
1. Gems which are needed by Portus but are not available as RPMs.
2. RPMs which are on OBS but are not needed by Portus.
This script comes in handy because this project has changed quite a lot
its dependencies, and so some gems are on OBS when they shouldn't, etc.

packaging: added a script for checking gems

---

lib/portus/db.rb
spec/lib/portus/db_spec.rb

In order to check whether there were migrations pending, the db.rb
library called bundle directly, which is not a good idea in some
environments (e.g. production containerized scenario), where the bundle
command is hidden and portusctl should be used instead.

Don't call bundle directly

---

packaging/suse/portus.spec.in

Before this commit we were blindlessly deleting all empty files.
However, it appears that bundler/gem rely on empty files named
"gem.build_complete" to check whether extensions were correctly built.
Before this commit, then, bundler/gem were complaining about extensions
not being available. This commit then fixes the delete command to
exclude these important empty files.
Moreover, this commit also include a couple of cleanups (e.g. removing
the unneeded node_modules.tar.gz heavy file).

packaging: do not remove important files

---

config/config.yml
lib/portus/http_helpers.rb

Hi,
in my environment response for 
`# time curl -i -ks -H "Authorization: Bearer $token" https://example.ref.com/v2/_catalog?n=10000`
takes more than 60s:
```
real    1m18.917s
user    0m0.008s
sys     0m0.000s
```
That is fine for me, but not for Portus's background worker :)
I think it is quite nice idea to have that parameter in config.
Thanks

Add param for read response timeout setting

---

.babelrc
.gitignore
.travis.yml
config/webpack.js
package.json
spec/javascripts/.eslintrc
spec/javascripts/setup.js
spec/javascripts/shared/toggle-link.spec.js
yarn.lock

We are introducing the ability of writing javascript unit tests. Until now,
this wasn't possible.
To achieve that we decided to go with the mocha + webpack approach that
uses the `mocha-webpack` package. As the assertion library we choose
`expect`.
To run the tests you can simply type `yarn test`. And if you want the to check
the coverage, you can type `yarn coverage`.
There still stuff to be improved. The `.vue` files coverage does not work
properly and this is something that needs investigation.

js: introduced unit testing

---

Dockerfile

The ruby image no longer includes bundler, so we have to install it by
hand.

docker: install bundler for the dev image

---

Dockerfile

We were getting the bundler.ruby2.5 binary, but everyone expects
`bundler` instead.

development: update the alternatives for bundler

---

app/helpers/sessions_helper.rb
app/views/devise/sessions/new.html.slim
config/config.yml
packaging/suse/portusctl/lib/cli_oauth.rb
packaging/suse/portusctl/man/man1/portusctl-setup.1
packaging/suse/portusctl/man/markdown/portusctl-setup.md
packaging/suse/portusctl/templates/config-local.yml.erb
spec/features/auth/login_feature_spec.rb
spec/spec_helper.rb

disable login form to enable OAuth only login page

feature: local login form can be disabled

---

app/assets/javascripts/vue-shared.js
app/helpers/application_helper.rb
app/views/layouts/application.html.slim

api: take the relative url root into account

---

app/controllers/webhooks_controller.rb
app/models/webhook.rb
app/views/public_activity/webhook/_update.html.slim
app/views/webhooks/_detail.html.slim
app/views/webhooks/_webhook.html.slim
app/views/webhooks/create.js.erb
app/views/webhooks/index.html.slim
app/views/webhooks/show.html.slim
db/migrate/20180109114124_add_name_to_webhooks.rb
db/schema.rb
spec/controllers/webhooks_controller_spec.rb
spec/factories/webhooks.rb
spec/features/webhooks_spec.rb
spec/models/webhook_spec.rb

Add a name column for webhook and change dashboard messages for webhook activities (e.g updating a webhook or creating a webhook).
Fix #1578 
Fix #1340

Add name column for webhook and change dashboard messages for webhook

---

.travis.yml
packaging/suse/make_spec.sh

The bundler version is determined by the one being used. This is the
ideal situation, but it turns out it's basically impossible to guarantee
that on Travis CI (we were using an ugly hack that does not work anymore
because they've updated stuff...).
So, the idea is that the bundler version being used doesn't matter that
much, and we are already using it on development, so we'll set it
directly when creating the spec file.

packaging: manually set the bundler version

---

Gemfile
Gemfile.lock
packaging/suse/make_spec.sh
packaging/suse/portus.spec.in

Two gems (bootstrap-sass & sass-rails) are only needed for compiling the
assets, so we will include them now in the `assets` group.
Moreover, we need to have the gems from the `assets` group as a
BuildRequires, otherwise the assets compilation might fail. That being
said, this commit also excludes these gems from the final bundle (i.e.
it discards these gems once assets have been compiled).
Finally, I've upgraded the `uglifier` gem to match the one from openSUSE
Factory.

packaging: polishing how asset gems are handled

---

.rubocop.yml
Gemfile
Rakefile
_data/api.yml
_docs/API.md
_includes/swagger-method.html
_layouts/swagger.html
_plugins/definition_extractor.rb
_plugins/sort_by_tag.rb
_plugins/swagger_register.rb
stylesheets/partials/_layout.scss
stylesheets/partials/_swagger.scss
stylesheets/portus.scss

I've created some small Jekyll plugins to overcome some flaws from the liquid
markup language... The code for the API documentation was inspired by
https://github.com/jexhson/jekyll-swagger, but I ultimately changed it so much
that it does not resemble in any way that plugin.
Moreover, because of the creation of these plugins, rubocop was getting noisier,
so I adapted the configuration from the `master` branch into this one.

docs: added documentation for the API

---

lib/api/v1/repositories.rb
lib/api/v1/teams.rb

There were some calls to present which were missing the type context.
This should fix some oddities.

api: added the current type on some calls

---

config/initializers/swagger.rb
doc/REST-API.md

Rename swagger_doc into official naming openapi-spec.
closes #1652
However in feature releases we remove the swagger term in code at other location as well.

Rename swagger_doc into official naming openapi-spec.

---

packaging/suse/portus.spec.in

It will only remove `bundler`, which we need...

packaging: do not run bundle clean

---

app/controllers/admin/registries_controller.rb
app/services/registries/base_service.rb
app/services/registries/create_service.rb
app/services/registries/update_service.rb
lib/api/v1/registries.rb
spec/api/grape_api/v1/registries_spec.rb
spec/controllers/admin/registries_controller_spec.rb

api: added create and update methods to registries

---

app/models/tag.rb
db/migrate/20180207145522_change_vulnerabilities_to_medium_text.rb
db/schema.rb
spec/controllers/tags_controller_spec.rb
spec/models/tag_spec.rb

Some images like `node:8` had so many vulnerabilities that then the
stored JSON was huge. This is a temporary fix because we are about to
release 2.3 and this fix is needed. A more suitable approach is the one
mentioned in #1669.
Fixes #1657

Increased the text storage for vulnerabilities

---

lib/portus/background/security_scanning.rb
spec/lib/portus/background/security_scanning_spec.rb

After a security scanning iteration, some tags might not be in a
:scan_done state. This is possible in situtations like:
- Clair was unavailable for some time because of a hiccup.
- There's an actual bug on the security scanning.
In these cases, we will check in the end of the iteration whether all
tags have been marked as scan. If this is not the case, then we will log
a warning and mark the failed tags as :scan_none (so in the next
iteration they can be picked up and hopefully be scanned properly this
time).
See #1649

background: mark failed scans as re-schedulable

---

lib/api/root_api.rb
lib/api/v1/vulnerabilities.rb
spec/api/grape_api/v1/vulnerabilities_spec.rb

This commit adds two new endpoints: `/vulnerabilities` and
`/vulnerabilities/:id`. Both these endpoints require admin privileges,
and they will simply toggle the `scanned` column of tags so the scanning
task can pick them up.
This commit does not deal with the UI part, it simply provides the
backend code. The frontend code can be delivered later on.
See #1658

api: added endpoints for re-scheduling scanning

---

app/controllers/repositories_controller.rb
app/controllers/tags_controller.rb
app/models/repository.rb
app/models/tag.rb
bin/background.rb
config/config.yml
lib/portus/background/README.md
lib/portus/background/registry.rb
lib/portus/background/security_scanning.rb
lib/portus/background/sync.rb
spec/api/grape_api/v1/vulnerabilities_spec.rb
spec/lib/portus/background/registry_spec.rb
spec/lib/portus/background/security_scanning_spec.rb
spec/lib/portus/background/sync_spec.rb
spec/models/repository_spec.rb
spec/models/tag_spec.rb
spec/spec_helper.rb

This PR includes three commits:
- The first commit cleans up the changes from #1679 (adding tests and rebasing).
- The second commit rolls back any changes from the iteration if in the end it notices registry events (i.e. a push/delete happened while this task was being run). The idea is that this task should not conflict with the `registry` one, which has a higher priority.
- The third commit adds a `sync-strategy` option, which depends on the changes from #1631. This way we allow people to tune this task further. Then, if enabled we will provide four more options, which range from a riskier approach (current behavior), to safer ones. The idea is that this task has given us quite some headaches, so we will default to the safest (and probably the most useful) behavior.

Stabilize the `sync` background task before the 2.3 release

---

config/config.yml
lib/portus/background/sync.rb
spec/lib/portus/background/sync_spec.rb
spec/spec_helper.rb

The `sync` part was redundant since it was already under the `sync`
option.

Renamed from sync-strategy to strategy

---

.github/issue_template.md
.github/pull_request_template.md
.github/stale.yml
CONTRIBUTING.md

This PR includes two commits:
- The first one adds Github templates for issues and PR. This should not only help contributors, but also us since we'll hopefully get more detailed issues and PRs.
- The second commit adds [stale](https://github.com/probot/stale), which it's being used in some repos like Rails, Atom, etc. It marks *old* issues as stale, and it even closes them if there is no further activity. This should help us to detect old issues. Note that it will ignore some labels and issues which are already triaged in our projects.

Updated the documentation for contributors

---

.travis.yml
lib/tasks/test/git-validate.rake

This tool allows us to validate git commit messages. Since
git-validation will reports tons of errors when checking the current git
history, I'm providing a range instead. This range spans from the
previous non-merge commit up to HEAD.

test: added git-validation

---

packaging/suse/portus.spec.in

This is a leftover in which the RPM package tried to copy a (now
non-existant) portusctl to /usr/sbin.

packaging: do not install empty portusctl

---

app/mailers/devise_mailer.rb
config/config.yml
config/initializers/mail.rb

Fixes #1693 .
Make sure that the email settings are not checked and therefore no error is raised, when "reply_to" is empty.

Make reply_to setting optional

---

config/initializers/swagger.rb
lib/api/root_api.rb

This is a fix for https://github.com/SUSE/Portus/pull/1656 The api wasn't still at the right place but the documentation was already updates. Now both the documentation and the the api are available under `/api/openapi-spec`

The OpenAPI should appear under openapi-spec and not swagger_doc

---

app/policies/namespace_policy.rb
config/config.yml
spec/controllers/namespaces_controller_spec.rb
spec/features/namespaces_spec.rb
spec/features/repositories_spec.rb
spec/helpers/repositories_helper_spec.rb
spec/policies/namespace_policy_spec.rb
spec/spec_helper.rb

Implement a environment variable in config.yml, so that only admins can push images.
New version of #1689.
Signed-off-by: Fabian Baumanis <fabian.baumanis@suse.com>

Implement a environment variable in config.yml, so that only admins can push images.

---

bin/ci.sh
config/config.yml
lib/api/helpers.rb
lib/api/helpers/application_tokens.rb
lib/api/helpers/errors.rb
lib/api/helpers/namespaces.rb
lib/api/root_api.rb
lib/api/v1/namespaces.rb
lib/api/v1/repositories.rb
lib/api/v1/teams.rb
lib/api/v1/users.rb
spec/api/grape_api/v1/users_spec.rb

This new endpoint lives inside of the user namespace and its main goal is to
allow people to create the first admin user from the API. This endpoint is only
allowed if the `first_user_admin` option has not been disabled. Another
restriction is that there shouldn't be a user already created. Last but not
least, this method can be called without being authenticated.
In the ideal case, you would call this method when you just started your Portus
instance. Then, you will get the first user created
(same arguments as `POST /api/v1/users`) and it will also get an application
token assigned to it. The reponse will be the `plain_token` from the application
token. Thus, the whole point of this method is to follow this workflow:
1. Portus instance deployed.
2. Admin uses this bootstrap endpoint to …

api: added a bootstrap endpoint

---

bin/test-integration.sh
spec/integration/events.bats
spec/integration/push.bats

From now on we will rely on an image that is known to be always there,
regardless of the environment.

spec: use another image for integration tests

---

app/policies/namespace_policy.rb
config/config.yml
spec/controllers/namespaces_controller_spec.rb
spec/features/namespaces_spec.rb
spec/features/repositories_spec.rb
spec/helpers/repositories_helper_spec.rb
spec/policies/namespace_policy_spec.rb
spec/spec_helper.rb

Before this commit, an administrator was able to disable push control
entirely for regular users. This commit adds a more fine-grained
solution:
1. allow-teams: as usual.
2. allow-personal: team access is restricted: regular users can only
push into their personal namespaces.
3. admin-only: only admins can push.
This should hopefully tackle more work flows inside of Portus.
Fixes #1528
See #1137

policies: added more fine-grained push policies

---

app/middleware/catch_json_parse_errors.rb
app/services/registries/create_service.rb
app/services/registries/update_service.rb
lib/api/entities.rb
lib/api/helpers/application_tokens.rb
lib/api/helpers/errors.rb
lib/api/root_api.rb
lib/api/v1/namespaces.rb
lib/api/v1/registries.rb
lib/api/v1/teams.rb
lib/api/v1/users.rb
spec/api/grape_api/v1/namespaces_spec.rb
spec/api/grape_api/v1/registries_spec.rb
spec/api/grape_api/v1/repositories_spec.rb
spec/api/grape_api/v1/teams_spec.rb
spec/api/grape_api/v1/users_spec.rb

We were using 400 instead of 422 in quite some places. This commit
addresses this trend.

api: use 422 when applicable

---

lib/api/v1/users.rb

api: added failure http codes for bootstrap

---

Gemfile
Gemfile.lock

packaging: upgraded loofah to 2.2.1

---

packaging/suse/make_spec.sh

example:
Provides: bundled(js(foo)) = version
instead of
Provides: bundled(foo) = version
to make it explicit foo is a javascript lib

[packaging] add "js()" to the bundled javascript libs

---

packaging/suse/portus.spec.in

generate the spec file so it is important to keep this in the package
source
Provide a general description of the changes in your pull request. If this pull
request fixes a known issue, please tag it as well (e.g.: `Fixes #1`). Check the
`CONTRIBUTING.md` file for more information.
Thanks for contributing to Portus!

[packaging] add yarn.lock as Source2. yarn.lock is being used to

---

config/config.yml
lib/portus/http_helpers.rb
lib/portus/security_backends/clair.rb
spec/lib/portus/security/clair_spec.rb
spec/spec_helper.rb

Moreover, I've also added a configuration option so the timeouts for the
registry and clair can be configured separately. This has been done
because the Clair timeout by default is 900 seconds, which might be a
bit too high for registries.
Fixes #1751

security: don't crash on clair timeouts

---

lib/portus/background/security_scanning.rb
lib/portus/http_helpers.rb
lib/portus/registry_client.rb
lib/portus/security.rb
spec/lib/portus/security/clair_spec.rb

In order to fetch vulnerabilities, the security scanner first has to
gather the layers to be inspected. In our case, we fetch this
information from the image manifest as given by the Registry.
This commit adds some code so the fetching of this manifest is safer.
For example, it will not freak out if a timeout was reached when
requesting the manifest from the registry.
Fixes #1743

security: fetch the manifest more safely

---

app/assets/javascripts/modules/repositories/services/vulnerabilities-parser.js
app/controllers/tags_controller.rb
app/models/scan_result.rb
app/models/tag.rb
app/models/vulnerability.rb
app/models/webhook.rb
app/views/tags/show.html.slim
db/migrate/20180409142550_create_vulnerabilities.rb
db/migrate/20180409143945_create_scan_results.rb
db/migrate/20180411102022_remove_vulnerabilities_from_tag.rb
db/schema.rb
lib/api/entities.rb
lib/portus/security_backends/clair.rb
spec/controllers/tags_controller_spec.rb
spec/controllers/webhooks_controller_spec.rb
spec/factories/scan_result.rb
spec/factories/vulnerability.rb
spec/factories/webhooks.rb
spec/features/repositories_spec.rb
spec/features/tags_spec.rb
spec/lib/portus/background/security_scanning_spec.rb
spec/models/tag_spec.rb
spec/models/webhook_spec.rb
spec/vcr_cassettes/background/clair.yml
spec/vcr_cassettes/background/node.yml

Before this we were storing vulnerabilities as a serialized column,
which, despite being convenient, had some problems. For example, when
the response from scanners was too large, the insert would fail on this
column.
Fixes #1669

Added a table for vulnerabilities

---

app/models/registry.rb
app/models/repository.rb
app/models/tag.rb
lib/portus/background/sync.rb
lib/portus/errors.rb
lib/portus/registry_client.rb
lib/tasks/portus/tags.rake
spec/api/grape_api/v1/repositories_spec.rb
spec/api/grape_api/v1/tags_spec.rb
spec/models/registry_spec.rb
spec/models/repository_spec.rb
spec/models/tag_spec.rb
spec/services/repositories/destroy_service_spec.rb
spec/services/tags/destroy_service_spec.rb

In the past we have had some problems when it comes to unhandled
exceptions. This commit fixes the opposite problem: having too broad
exceptions. That is, this commit clarifies which exact exceptions might
be raised from the different registry methods and updates the places
where these methods are used.
Some tests had to be corrected because they were abusing some code
paths that were rescuing StandardError.

lib: be explicit on the exceptions to be rescued

---

app/models/repository.rb
lib/portus/background/sync.rb
lib/portus/registry_client.rb
spec/lib/portus/background/sync_spec.rb
spec/lib/portus/registry_client_spec.rb

This commit is more explicit on what to do when a catalog error happens.
In this case, if a plain catalog error happens (fetching the list of
repositories and their manifests), then nothing will be done. If
fetching the catalog worked, and fetching the list of tags then suddenly
fails, before this commit that repo would've get nuked because it
would've get a repository with no tags.
This commit instructs to skip that repository when considering whether
to remove or not some repositories that are found to be dangling.
See #1293
See #1599

sync: do not remove repositories on some errors

---

app/assets/javascripts/modules/repositories/components/tags-table-row.vue
app/assets/javascripts/modules/repositories/components/tags-table.vue
app/helpers/repositories_helper.rb
app/views/repositories/show.html.slim

The tag vulnerabilities link was broken on setups that used
RAILS_RELATIVE_ROOT_URL because the url path was hardcoded.
This patch fixes that by considering the value of
RAILS_RELATIVE_ROOT_URL and concatenating with 'tags' string.
Fixes #1718

Fixed tags url for tags vulnerabilities

---

app/models/registry.rb
lib/api/entities.rb
spec/models/registry_spec.rb

The internal hostname was being referring as the hostname to be copied
to the clipboard when the user clicked on the labeled tags. This patch
fixes that by checking if external hostname is set or not. If set,
external hostname will be used instead of internal hostname.
This change affects the API directly because the repository entity is
now using the #reacheable_hostname method that tried to prioritize the
external hostname if set.
Fixes #1719

Fixed hostname copied to clipboard on tags

---

app/views/admin/registries/index.html.slim

External hostname was not being shown in the registries table. This is a
simple patch that adds a column for the external hostname and show it
whenever present.
Fixes #1711

registries: show external hostname for registries

---

config/initializers/registry.rb

This initializer allows administrators to set some env. variables to
automatically create a registry.
Fixes #655

config: added registry initializer

---

config/initializers/devise/oauth.rb

We didn't need `user`, but just `read:user` and `user:email`.
Fixes #1790

devise: use a more fine-grained scope for Github

---

lib/api/v1/repositories.rb
lib/api/v1/tags.rb

If we don't specify what Grape should do/return when we have an empty
response, an exception is thrown because it's expected something and
it's actually nil.
This was fixed in latest implemented features but there were still
legacy code with this problem.

api: explicitly set 204 status instead of nothing

---

app/policies/webhook_policy.rb
config/config.yml
spec/policies/webhook_policy_spec.rb
spec/spec_helper.rb

Before this commit, permissions on webhooks were coupled with
namespaces, which was not desirable for some users.
Fixes #1109

webhooks: added permissions on webhooks

---

app/assets/javascripts/config.js
app/assets/javascripts/plugins/config.js
app/assets/javascripts/shared/components/table-pagination.vue
app/assets/javascripts/shared/mixins/table-paginated.js
app/assets/javascripts/vue-shared.js
app/helpers/application_helper.rb
app/views/layouts/application.html.slim
app/views/shared/_config.html.slim
config/config.yml
spec/javascripts/modules/repositories/tags-table.spec.js
spec/javascripts/shared/table-pagination.spec.js
spec/spec_helper.rb

So far the pagination and number of shown pages before and after current
page were hard coded and not configurable.
With this the user can now choose from a configuration perspective how
he wants to show their tables.
Fixes #1375

config: added pagination options

---

bin/check_services.rb
bin/integration/integration.rb
bin/test-integration.sh
config/config.yml
examples/compose/docker-compose.ldap.yml
lib/portus/ldap.rb
lib/portus/test.rb
spec/integration/helpers/ldap.rb
spec/integration/ldap/login.bats
spec/integration/profiles/ldap.rb
spec/lib/portus/ldap_spec.rb

This commit fixes a couple of bugs present in both master and 2.3:
1. We didn't implement some options that needed to be passed to the LDAP
backend to fully support SSL connections. This has been addressed
also in the configuration, but without breaking existing
installations (e.g. the `method` attribute from 2.3 has been left
untouched). This will be addressed in later commits of the master
branch (so in 2.4 users should adapt to this change).
2. We were relying on Devise's translations for failures, but some of
them were not available. This has been addressed and improved: the
error message will be more on point and more informative to end
users.
There is still room for improvement, but we can do it in later commits:
let's keep this commit to the point so it can be cherry-picked into …

ldap: fixed a couple of bugs around SSL support

---

config/config.yml
lib/portus/ldap.rb
spec/api/v2/token_spec.rb
spec/lib/portus/ldap_spec.rb
spec/spec_helper.rb

These are two commits that:
1. Adds the option for a connection timeout.
2. Removed the deprecated `method` option.

Ldap improvements

---

app/assets/javascripts/modules/webhooks/components/edit-form.vue
app/assets/javascripts/modules/webhooks/components/info.vue
app/assets/stylesheets/components/webhooks/edit-form.scss
app/controllers/webhooks_controller.rb

The only way of enabling a webhook was through the index page. Now user
can change that while editing other info.

ui: added enabled toggle to webhooks edit form

---

lib/portus/health_checks/registry.rb
lib/portus/request_error.rb
spec/api/grape_api/v1/health_spec.rb
spec/integration/health.bats
spec/lib/portus/request_error_spec.rb

The fact that `RegistryClient.reachable?` might raise an exception is
fine in some situations on the API, but it prevents us from knowing from
other errors, and it also makes things harder in other places of the
code that rely on this check. Hence, let's rescue this exception and
return its value properly.

health: catch all exceptions for registries

---

lib/portus/ldap/authenticatable.rb
lib/portus/ldap/connection.rb
lib/portus/ldap/login.rb
spec/lib/portus/ldap/authenticatable_spec.rb

This PR has two somewhat related commits:
1. A fix for #1832 
2. A re-structure of LDAP tests

Fixed LDAP crash and improved tests

---

bin/check_db.rb
bin/test-integration.sh
docker/Dockerfile
docker/README.md
docker/init
examples/README.md
examples/compose/README.md
examples/development/postgresql/README.md

Having Docker images into another repository disallowed us from having
Docker images from different sources. This is something we needed
because the `development` tag has to be created from this repository.
Fixes #1544

docker: moved production images into this repo

---

app/assets/javascripts/modules/repositories/components/comments/list-item.vue
app/helpers/application_helper.rb
app/models/user.rb
lib/api/entities.rb
spec/helpers/application_helper_spec.rb
spec/models/user_spec.rb

During the refactoring of comments to vue components the user's avatar
was not implemented properly.

ui(comments): fixed regression of user's avatar

---

lib/portus/ldap/authenticatable.rb
lib/portus/ldap/configuration.rb
spec/integration/ldap/login.bats
spec/integration/profiles/ldap.rb
spec/lib/portus/ldap/authenticatable_spec.rb
spec/lib/portus/ldap/configuration_spec.rb

This is a regression that happened after merging #1828.
Fixes #1850

ldap: properly skip the portus user

---

app/assets/javascripts/modules/users/index.js
app/controllers/admin/users_controller.rb
app/models/application_token.rb
app/models/user.rb
app/policies/application_token_policy.rb
app/views/admin/users/edit.html.slim
app/views/admin/users/index.html.slim
app/views/admin/users/new.html.slim
app/views/shared/_notification.html.slim
db/migrate/20180612145708_add_bot_to_user.rb
db/schema.rb
lib/api/entities.rb
lib/api/v1/users.rb
lib/portus/ldap/configuration.rb
lib/portus/ldap/login.rb
spec/api/grape_api/v1/application_tokens_spec.rb
spec/api/grape_api/v1/users_spec.rb
spec/factories/users_factory.rb
spec/features/admin/users_spec.rb
spec/integration/helpers/ldap.rb
spec/integration/ldap/login.bats
spec/integration/profiles/ldap.rb
spec/lib/portus/ldap/authenticatable_spec.rb
spec/lib/portus/ldap/configuration_spec.rb
spec/models/user_spec.rb

This commit introduces a new concept: bots. Bots are regular users that
are created by administrators, but with some subtelties:
1. A bot doesn't own a personal namespace.
2. A bot cannot login via web.
3. A bot can only log in with application tokens (a token is generated
automatically when creating a bot).
This should cover the needs from #517 and #801, except for a couple of
small features that should be added in the near future:
- Bots should be able to be created by mere team owners. These team bots
should be attached to a specific team, but an administrator might be
able to upgrade it to a global bot.
- Team owners should be able to be more granular on repository access
(instead of granting access to all repositories from a given
namespace).
See #517
See #801
Signed-off-by: Miquel …

Adding the possibility to create bots

---

bin/background.rb
config/config.yml
lib/portus/background/garbage_collector.rb
spec/lib/portus/background/garbage_collector_spec.rb
spec/spec_helper.rb

Implemented a new background task: garbage collector. This task will
clean up old tags. It is disabled by default and it can be further
configured under the `delete.garbage_collector` option.
Fixes #1479

background: implemented garbage collector

---

app/views/namespaces/components/_form.html.slim
spec/features/namespaces_spec.rb
spec/features/teams_spec.rb

When user was selecting a team, the field was disappearing from the
screen. Minor regression introduced during the replacement of typeahead
by vue-multiselect.

ui: fixed team field on namespaces#index

---

.travis.yml
Dockerfile
Gemfile
Gemfile.lock
app/assets/javascripts/main.js
app/assets/javascripts/modules/repositories/components/comments/wrapper.vue
app/assets/javascripts/modules/teams/components/panel.vue
app/assets/javascripts/shared/components/toggle-link.vue
app/views/layouts/application.html.slim
spec/features/admin/registries_spec.rb
spec/features/admin/users_spec.rb
spec/features/application_tokens_spec.rb
spec/features/auth/profile_feature_spec.rb
spec/features/help_spec.rb
spec/features/namespaces_spec.rb
spec/features/repositories_comments_spec.rb
spec/features/teams_spec.rb
spec/features/webhooks_spec.rb
spec/rails_helper.rb
spec/support/capybara.rb
spec/support/containers.rb
spec/support/helpers.rb
spec/support/wait_for_events.rb

So far the feature tests with js enabled were running through
poltergeist driver. As we know, PhantomJS was discontinued and
that's bad. PhantomJS was far from perfect and we've had a lot
of flaky issues with it.
Even knowing that most of those flaky issues were our fault, it's
always good to improve our workflow whenever possible. Based on this we
are adding chrome headless as our default js runner for our feature
tests.
Unfortunately we had to keep poltergeist for one scenario that we
couldn't make chrome headless work properly. That scenario is when the
dev runs the feature tests inside of the container. For bare metal and
travis, chrome headless works like a charm.

spec: added chrome headless as default js runner

---

packaging/suse/portusctl/lib/constants.rb

The code determining if Portus is running containerized is broken on Kubernetes because in this case PID 1 doesn't belong to the `docker` cgroup slice.
That causes the code to invoke `hostnamectl`, that tries to access kdbus from within a container. That causes Rails to fail immediately.
fixes #1732

Improve detection of containerized environments - fix issue #1732

---

packaging/suse/make_spec.sh

In particular, when performing sed on NODEJS_BUILD_PROVIDES, it may not
work properly because sometimes it contained slashes in it and
substitution failed.

packaging: fixed an issue with slashes on sed

---

.gitignore
app/assets/javascripts/main.js
app/assets/javascripts/modules/explore/components/result-item.vue
app/assets/javascripts/modules/namespaces/components/table-row.vue
app/assets/javascripts/modules/repositories/components/comments/list-item.vue
app/assets/javascripts/modules/repositories/components/table-row.vue
app/assets/javascripts/modules/repositories/components/tags/tags-table-row.vue
app/assets/javascripts/modules/webhooks/components/deliveries/table-row.vue
app/assets/javascripts/utils/comparator.js
app/assets/javascripts/utils/date.js
config/webpack.js
package.json
spec/javascripts/utils/date.spec.js
yarn.lock

With the migration to webpack 4, the latest uglify plugin stopped
removing comments by default and some unnecessary files were being
included.
- Moment.js was replaced with dayjs
- Webpack bundle analyzed was added to be used when necessary to analyze
bundle content
Unfortunately bundle is still big but that's because vue-multiselect was
introduced and lots of templates were migrated to .vue files.

js: reduced bundle size

---

app/controllers/passwords_controller.rb
app/models/user.rb
config/initializers/portus_user.rb
db/seeds.rb
spec/api/grape_api/v1/users_spec.rb
spec/api/v2/token_spec.rb
spec/controllers/namespaces_controller_spec.rb
spec/features/auth/signup_feature_spec.rb
spec/features/dashboard_spec.rb
spec/features/forgotten_password_spec.rb
spec/integration/profiles/shared.rb
spec/lib/portus/background/garbage_collector_spec.rb
spec/lib/portus/registry_client_spec.rb
spec/models/namespace_spec.rb
spec/models/repository_spec.rb
spec/models/user_spec.rb
spec/support/helpers.rb

This pull request introduces two commits that prevents someone from updating the portus hidden user. This user is not to be used externally (i.e. it's not an explicit admin), but it's used internally for requests performed against the registry. That being said, if an attacker has access to the email being set for this hidden user, then it may be able to reset the password and use it externally too. This is now mitigated:
1. The update on the portus hidden user is no longer allowed (at the model level).
2. An initializer has been introduced that updates the password of this hidden user depending on the password secret. This is useful when the administrator thinks that this secret has been compromised and wants to update it: simply set a new secret and restart portus.
3. The "I forgot my …

Prevent the update of the portus user

---

config/database.yml
config/puma.rb

A bunch of changes required to be more flexible when deploying Portus into a containerized environment.

Make containerized deployment more configurable

---

app/models/user.rb
app/services/registries/create_service.rb
spec/models/user_spec.rb
spec/services/registries/create_service_spec.rb

This commit fixes a regression introduced in the pull request #1896 in
which registries were no longer creatable. This happened because of a
validation error on `portus_user_validation` produced by adding a team
to the portus hidden user.
Fixes #1909

Fixed regression on registries not being created

---

examples/compose/docker-compose.clair-ssl.yml

Improvement of solution for #1714
* uses SSL encryption for registry
* uses SSL encryption for frontend
* uses nginx for serving portus
Signed-off-by: Stefan Weiberg <sweiberg@suse.com>

more secure docker-compose example

---

app/assets/javascripts/modules/repositories/components/tags/tag.vue

Input was being added to the body but not being removed after its
content was copied to the clipboard.

js: remove input after copying to clipboard

---

app/assets/javascripts/bootstrap.js
app/assets/javascripts/main.js
app/assets/javascripts/modules/users/index.js
app/assets/javascripts/modules/users/unauthenticated.js
app/assets/javascripts/plugins/index.js
app/assets/javascripts/unauthenticated.js
app/views/layouts/application.html.slim
app/views/layouts/authentication.html.slim
config/webpack.js
vendor/assets/javascripts/lifeitup_layout.js

Initially we had one single entrypoint that generated one large output
file.
The idea of this patch was to split unecessary code into different
entrypoints (authenticated and unauthenticated) and split vendors files
into a different chunk.
Now it produces smaller bundles and chunks that will be downloaded
asynchronously and increase the speed up of pages the first time.
Also removed unused and uncessary code from lifeitup vendor file.

js: splitted into bundles and chunks

---

app/assets/javascripts/bootstrap.js
app/assets/javascripts/plugins/unauthenticated.js
app/assets/javascripts/shared/components/sign-out-btn.vue
app/assets/javascripts/unauthenticated.js
app/controllers/auth/sessions_controller.rb
app/views/shared/_header.html.slim
app/views/shared/_notification.html.slim
spec/features/application_spec.rb
spec/features/auth/logout_feature_spec.rb

After the removal os jquery-ujs, the sign out button stopped working.
A component to mimic the previous behavior was created and it's called
<sign-out-btn> by default in the shared/components folder.
Fixes #1931

ui: created <sign-out-btn> component

---

app/assets/javascripts/modules/namespaces/components/new-form.vue

ui: clear selected team after namespace creation

---

.github/stale.yml

Documentation issues should never be marked as stale.
See #1833

github: add documentation in the exemptLabels

---

packaging/suse/make_spec.sh
packaging/suse/portus.spec.in

Review of how we package (RPM) portus.
Add gems as sources
Autogenerate autoprovides for js files
Remove mariadb  requirement
Add kubectl requirement

Review packaging bundling of gems js requirements recommends

---

_docs/Configuring-Portus.md
_features/oauth.md

I've also added the missing configuration option `local_login`.
Fixes #1842

Added some more notes on OAuth support

---

docker/Dockerfile

opensuse/amd64 is dead for some time now.
docker build works and starting the image (by itself) works as well.

Use the correct reference for Leap 42.3 in Dockerfile

---

packaging/suse/portus.spec.in

Instead of adding all the gems as sources, we will use the cpio
strategy, which does not need to change the spec file or, more
important, does not need us to add/remove the .gem files into the
package every time there is a change in the Gemfile.lock file.
However, using this strategy the gems are copied on another path, and we
need to fix this.
Then, we will need to adapt the _service file in obs to have this
section
```
<service name="download_url">
<param name="protocol">https</param>
<param name="host">raw.githubusercontent.com</param>
<param name="path">/SUSE/Portus/master/Gemfile</param>
</service>
<service name="download_url">
<param name="protocol">https</param>
<param name="host">raw.githubusercontent.com</param>
<param name="path">/SUSE/Portus/master/Gemfile.lock</param> …
```

[packaging] fix gem packaging

---

packaging/suse/release/release.sh

in commit 556778b9f3aa8cd06f4519a16bafc352b7913c9c we fixed the gem
packaging for master
However, when creating a release branch, all services should be in
disabled mode and we needed to adapt the sed expression to do that.

[packaging] fix the _service file

---

Gemfile.lock

A vulnerability has been found against the version we were using, so
I've upgraded this gem to a version fixing this. That being said, we are
only using on tests, since it's only used by selenium-webdriver. Hence,
it does not affect us, really.
See CVE-2018-1000544
See bsc#1099280

Upgrade rubyzip to 1.2.2

---

app/controllers/passwords_controller.rb
config/config.yml
config/environments/development.rb
config/initializers/mail.rb
lib/portus/mail.rb
spec/controllers/passwords_controller_spec.rb
spec/lib/portus/mail_spec.rb

The current configuration options were missing some important keys for
ActiveMailer on some scenarios.
Fixes #1876

Expanded configuration for the mailer

---

app/controllers/auth/registrations_controller.rb
config/locales/devise.en.yml

Upon password update, users should `docker login` again, otherwise
push/pull command will fail.

Remind users to login again after password update

---

lib/tasks/portus/db.rake

This task should be used when setting up the database instead of the
usual combination. This handles databases with pending migrations, new
databases, etc.
See #1639
See #1712

tasks: added portus:db:configure

---

app/models/tag.rb
spec/models/tag_spec.rb

Deletes of registry objects are referenced by their digest, but in some
situations, we accidentally deleted objects from other places. For
example, if we pushed the same image:tag into multiple namespaces, then
a delete on one of them removed also the others from other namespaces.
This commits restricts this into the given namespace/repository.
Fixes #1125

Restrict deletes into the repository

---

config/config.yml

We have been noticed that the default value for the JWT expiration time
was simply to small. This commit simply raises this value to a hopefully
more suited one.
Fixes #1978

config: raised the value for JWT expiration time

---

app/policies/namespace_policy.rb
app/policies/repository_policy.rb
spec/policies/repository_policy_spec.rb

Repositories and tags that belonged to a global namespace was not being
able to be deleted. The regression was introduced in the 2.4 release.
Fixed #2011

policies: fixed destroy for repositories/tags

---

config/config.yml
lib/portus/ldap/authenticatable.rb
lib/portus/ldap/connection.rb
lib/portus/ldap/login.rb
spec/integration/helpers/ldap.rb
spec/integration/ldap/login.bats
spec/integration/profiles/ldap.rb
spec/lib/portus/ldap/authenticatable_spec.rb
spec/spec_helper.rb

Introduced the new `ldap.admin_base` filter, which allows users to set a
filter for Portus administrators. When a new user logs in, it will
automatically set the `admin` flag depending on whether it was found on
this filter or not. If this configuration option is not set (default),
then this whole workflow will be ignored.
Fixes #1298

ldap: automatically set admin according to filter

---

app/policies/namespace_policy.rb

Standard users were seeing duplicated namespaces entries in the
namespaces#index page.

ui: fixed namespaces duplication

---

app/assets/javascripts/modules/teams/components/new-form.vue
spec/system/teams_spec.rb

When standard user, the UI was sending a parameter through the request
that was supposed to be sent only by admin user. This was preventing
standard users from creating teams.

ui: fixed team creation for standard user

---

app/controllers/admin/users_controller.rb
app/models/user.rb
lib/api/v1/users.rb
lib/portus/ldap/connection.rb
lib/portus/ldap/search.rb
spec/api/grape_api/v1/users_spec.rb
spec/integration/health.bats
spec/integration/helpers/curl.rb
spec/integration/ldap/health.bats
spec/integration/ldap/login.bats
spec/integration/ldap/user.bats
spec/integration/profiles/ldap.rb
spec/lib/portus/ldap/authenticatable_spec.rb
spec/lib/portus/ldap/search_spec.rb
spec/requests/admin/users_controller_spec.rb
spec/requests/webhooks_controller_spec.rb

In some cases, administrators won't have some users on the LDAP server
but they would on the local Portus instance. On these cases, let's allow
LDAP bind failures to fall back to the database.
Fixes #1862 
Fixes #1731

ldap: allow failures to fallback to the DB

---

app/assets/javascripts/modules/namespaces/components/details.vue
app/assets/javascripts/modules/namespaces/components/info.vue
app/assets/javascripts/modules/namespaces/pages/index.vue
app/models/namespace.rb
app/models/namespace/auth_scope.rb
app/models/repository.rb
app/models/team.rb
app/models/user.rb
app/models/webhook.rb
app/policies/namespace_policy.rb
app/views/public_activity/namespace/_create.html.slim
config/initializers/portus_user.rb
lib/api/entities.rb
lib/portus/background/sync.rb
spec/api/v2/token_spec.rb
spec/lib/portus/background/sync_spec.rb
spec/models/namespace/auth_scope_spec.rb
spec/models/namespace_spec.rb
spec/models/repository_spec.rb
spec/vcr_cassettes/registry/get_registry_catalog_namespace_missing.yml

Repositories with unknown namespaces from a pre-existent registry
were being ignored while syncing.
Now, by default, all the repositories will be considered and orphan
namespaces will be created. These namespaces can be transfered to its
respective teams later by any admin.
Fixes #1961

Allow automatic creation of unknown namespaces

---

app/models/scan_result.rb
db/migrate/20181213101302_add_index_scan_results_vulnerability_tag.rb
db/schema.mysql.rb
db/schema.postgresql.rb

In particular, I've added the index on vulnerability_id and tag_id. As
reported on #2053, this index makes the scanning of vulnerability issues
way faster on large amounts of tags.
Fixes #2053

db: added index on scan_result

---

app/controllers/explore_controller.rb
lib/api/entities.rb
spec/api/grape_api/v1/repositories_spec.rb

Tags were being rendered in repositories entity whenever repositories
were fetched. When rendering tags, we fetch vulnerabilities data that
might be too. That was causing slowness in repositories#index page.
We now only render tags when rendering respositories for the explore
page result. There's still room for improvement to fetch asynchronously
the vulnerabilities with its own endpoint.
Fixes #2059

entity (repositories): reduced amount of rendered data

---

Dockerfile
Gemfile
Gemfile.lock

This was deprecated in favor of sassc-rails. I've also upgraded
bootstrap-sass so it uses this dependency instead of the old sass gem.

Removed deprecated sass gem

---

packaging/suse/portus.spec.in

This is needed by the sassc gem.

packaging: pull gcc-c++ as a build require

---

packaging/suse/portus.spec.in

Apparently there is a soft link on a test of public_activity, and OBS
build doesn't quite like them. So, this commit simply nukes the `test`
directory of this gem (which is, for our purposes, is never really
needed).
This has already been tried on OBS directly and it worked.

packaging: fixed wrong link on public_activity

---

bin/integration/integration.rb
bin/test-integration.sh
lib/tasks/test/integration.rake

This is a small optimization targeted towards Travis CI on the master
branch. Before this commit, it always built the development image, and
this is not required on this branch.

ci: don't build the dev image on master

---

.dockerignore
app/models/team.rb
app/models/user.rb
bin/background.rb
bin/test-integration.sh
config/config.yml
db/migrate/20181224123453_add_ldap_group_checked_to_teams.rb
db/migrate/20190103113934_add_checked_at_to_team.rb
db/migrate/20190103124548_add_ldap_group_checked_to_user.rb
db/schema.mysql.rb
db/schema.postgresql.rb
examples/compose/docker-compose.ldap.yml
lib/api/v1/teams.rb
lib/portus/background/ldap.rb
lib/portus/ldap/search.rb
spec/api/grape_api/v1/teams_spec.rb
spec/integration/README.md
spec/integration/helpers/curl.rb
spec/integration/helpers/wait_event_done.rb
spec/integration/helpers/wait_ldap_check.rb
spec/integration/helpers/waiter.rb
spec/integration/ldap/team.bats
spec/integration/profiles/ldap.rb
spec/lib/portus/background/ldap_spec.rb
spec/lib/portus/ldap/search_spec.rb
spec/models/team_spec.rb
spec/models/user_spec.rb
spec/spec_helper.rb

This PR adds LDAP group support into Portus. After all the discussion from #734, I decided to keep it simple, and instead of being a full blown sync job, I've created a background job that acts as a helper: it will add as team members known Portus users that belong to an LDAP group which matches a given team (this situation being because either a new team was created, or because a user logged in for the first time).
Keeping this simple allows us to have something that is useful for most users, and that doesn't have to go over the myriad of corner cases that might spawn from a full sync (we have already suffered a lot from the registry sync job, for example, and that's supposed to be way easier...).
LDAP group support can be disabled in two ways:
1. Config option: there's the new …

Ldap groups

---

app/models/repository.rb
app/models/tag.rb
app/models/webhook.rb
config/config.yml
db/migrate/20190115133935_add_pulled_at_to_tags.rb
db/schema.mysql.rb
db/schema.postgresql.rb
lib/portus/background/garbage_collector.rb
lib/portus/registry_notification.rb
spec/lib/portus/background/garbage_collector_spec.rb
spec/lib/portus/registry_notification_spec.rb
spec/models/repository_spec.rb
spec/models/tag_spec.rb
spec/support/registry_events.rb

So far the garbage collector only had one simple option that was to
delete images older than X days.
In this patch we are introducing a new option and a new behavior. User
will now be able to keep the latest N images through `keep_latest`
option. And the images won't be deleted even if older than X days if
they were pulled in the latest X days.

config: improved garbage collector options

---

CHANGELOG.md
README.md

Update changelog and README

---

config/initializers/filter_parameter_logging.rb
lib/portus/ldap/login.rb
spec/lib/portus/ldap/authenticatable_spec.rb

After some review, only the login.rb file had poor debug messages.
Moreover, the `guess_email` method was also missing a needed rescue that
would, for example, make Portus crash for connection issues.
Furthermore, I've also added some more parameters to filter when
logging.
Fixes #1988

ldap: improved logger messages

---

spec/system/admin/users_spec.rb
spec/system/application_tokens_spec.rb
spec/system/namespaces_spec.rb
spec/system/teams_spec.rb

Some buttons have changed its name and specs failed. This commit is to
simply fix those failed caused by the previous commit.

specs: fixed failures after wording

---

app/assets/stylesheets/components/layout.scss
app/helpers/application_helper.rb
app/views/shared/_aside.html.slim
vendor/assets/stylesheets/lifeitup/layout.scss

Previously the highlight was only happening when hovering and when the
`#index` pages where selected. When the user selected a page or were
navigating in a sub-page (e.g. /repositories/1), the highlight
disappeared.
With this patch we are enforcing the highlight in every single page the
user visits. This will give more context for the user.
Fixes #2114

ui: improved sidebar highlight

---

app/policies/namespace_policy.rb
spec/api/v2/token_spec.rb
spec/policies/namespace_policy_spec.rb

Before this commit, the all? policy from namespaces was an alias to
push?, but doing that was ignoring various rules we have in regards to
how delete works depending on the configuration. The same thing can be
applied to the new delete? method.
Fixes #2123

Fixed all? and delete? namespace policies

---

app/views/public_activity/namespace/_change_visibility.html.slim
app/views/public_activity/namespace/_create.csv.slim
app/views/public_activity/repository/_delete.csv.slim
app/views/public_activity/repository/_push.csv.slim

There still some nil pointer exception that were not handled properly
when resources were destroyed.
This time was related to namespace (html) and repositories (csv).
Fixes #2124

ui: fixed nil exceptions for activities

---

app/views/devise/sessions/new.html.slim

When LDAP auth is enabled the 'Explore' link on the login page will never show even when anonymous browsing is enabled.
This change makes the explore link show when LDAP is enabled and also makes the login button text just 'Login' regardless of LDAP being enabled or not as Portus now supports running local users along side LDAP auth.
On a side note maybe the signup and forgot password options should be available when LDAP auth is enabled if local logins are also enabled. 
Signed-off-by: Ross Dougherty <ross@inomial.com>

show explore link on login page when ldap auth is enabled

---

app/views/devise/passwords/edit.html.slim
app/views/devise/passwords/new.html.slim

This fixes:
- Button font didn't match login page on both the reset and change password pages.
- 'Go back to login page' text color was wrong on change password page.
Signed-off-by: Ross Dougherty <ross@inomial.com>

fix style inconsistencies on password reset pages

---

app/models/tag.rb
db/migrate/20190314173309_change_tag_size.rb
db/schema.mysql.rb
db/schema.postgresql.rb
spec/models/tag_spec.rb

Previously its type was integer and it was limited to 4 bytes which the
maximum values would be 2GB in bytes. Since there are images above that
size we need to support it to avoid failure.
Fixes #2159

db: changed tag size column type to bigint

---

packaging/suse/package_and_push_to_obs.sh

Funnily enough, this makes Travis CI to fail because the log gets too long.

packaging: don't be verbose when compressing node_modules
