Gemfile, Gemfile.lock, app/controllers/api/v2/tokens_controller.rb, app/models/jwt_token.rb, app/serializers/jwt_token_serializer.rb, config/initializers/active_model_serializers.rb, config/initializers/secure_random_base58.rb, config/secrets.yml, spec/api/v2/token_spec.rb, spec/classes/jwt_token_spec.rb
Please review the following changes:
* dcbc358 Connect generated token to controller
* d928398 Install all the rpms and gems required by portus
=> [Review] Request from 'kalabiyau' @ 'SUSE/Portus/review_150414_token_issue'

CONTRIBUTING.md, LICENSE, README.md
Added LICENSE details plus contributors' requirements.
=> Add licensing details

app/assets/stylesheets/vendor/layout.css.less, app/views/shared/_header.html.slim
=> Fix the style of the user link on the top navigation bar

app/models/team.rb, spec/factories/teams_factory.rb, spec/models/team_spec.rb
=> Downcase the name of teams on creation

app/models/team.rb, app/models/team_user.rb, app/models/user.rb, app/policies/namespace_policy.rb, db/migrate/20150426115313_create_team_users.rb, db/schema.rb, spec/models/user_spec.rb, spec/policies/namespace_policy_spec.rb
=> Allow teams to have many users

Vagrantfile, db/migrate/20150427092952_add_admin_to_users.rb, db/schema.rb, db/seeds.rb
=> Add the concept of admin users

app/models/team.rb, app/models/user.rb, db/migrate/20150428081205_add_owner_to_team_users.rb, db/migrate/20150428081530_remove_owner_id_from_teams.rb, db/schema.rb, spec/factories/teams_factory.rb, spec/models/team_spec.rb, spec/models/user_spec.rb, spec/policies/namespace_policy_spec.rb
=> Allow many owners to own a team

app/views/devise/registrations/new.html.slim, app/views/devise/sessions/new.html.slim
=> Added the 'required' input attribute where needed

app/policies/namespace_policy.rb, db/migrate/20150429185051_add_public_to_namespace.rb, db/schema.rb, spec/policies/namespace_policy_spec.rb
=> Make possible to allow RO access to users that are not members of the team

app/models/registry.rb, app/models/team_user.rb
=> Moved duplicated code into its own method

app/controllers/teams_controller.rb, app/views/teams/create.js.erb
=> Don't set the same flashy message twice

app/assets/stylesheets/vendor/layout.css.less, app/views/layouts/authentication.html.slim
=> Center both the "Sign up" and the "Sign in" pages

app/assets/stylesheets/vendor/layout.css.less
=> Fixed regression on the centering of the "Sign up" and the "Sign in" pages

app/assets/javascripts/application.js.coffee, app/views/shared/_notifications.html.slim
=> Let bootstrap handle the closing of flashy messages

app/models/repository.rb, app/models/tag.rb, app/views/repositories/show.html.slim, db/migrate/20150515111638_add_author_to_tag.rb, db/schema.rb, spec/models/repository_spec.rb
Track and show the author of a push event.
=> Track author of docker push events

app/views/admin/registries/new.html.slim
=> Autofocus on the first text field of the form to create a new registry

.travis.yml, .travis_mariadb.sh, Gemfile, Gemfile.lock, app/controllers/search_controller.rb, app/models/repository.rb, app/policies/repository_policy.rb, app/views/search/index.html.slim, app/views/shared/_header.html.slim, config/routes.rb, db/migrate/20150521145620_add_fulltext_indexes_on_repositories_namespaces.rb, db/schema.rb, spec/controllers/search_controller_spec.rb, spec/policies/repository_policy_spec.rb
Added a simple search feature that allows to find repositories.
How it works:
* user enters a string inside of the search box
* a fulltext search is performed against both the repositories.name and the namespaces.name columns using the OR operator
* results are shown inside of the new 'search' page
Mandatory s
creenshot
=> Initial version of the search feature

.gitignore, .travis.yml, README.md, config/environments/production.rb, packaging/suse/.gitignore, packaging/suse/Portus.spec.in, packaging/suse/README.md, packaging/suse/conf/etc.apache2.vhosts.d.portus.conf, packaging/suse/make_spec.sh, packaging/suse/package_and_push_to_obs.sh
We will have to set jenkins project configuration as well (and unset it for this branch).
=> Add packaging scripts

db/seeds.rb
This data is for testing the appliance
=> add integration test data

.gitignore, app/views/shared/_header.html.slim, config/config.yml, config/initializers/config.rb, spec/features/gravatar_spec.rb
This commit also introduces the config.yml file. This file is ignored by git,
and if the admin hasn't configured it yet, this application will take some
defaults automatically.
Fixes #76
=> Make possible to disable Gravatar

app/controllers/auth/registrations_controller.rb, app/views/devise/registrations/edit.html.slim, spec/controllers/auth/registrations_controller_spec.rb
=> Don't allow users to remove their account

app/views/admin/dashboard/index.html.slim
=> admin: fixed inconsistency in the string of number of registries

app/controllers/auth/sessions_controller.rb, spec/features/auth/login_feature_spec.rb, spec/features/auth/logout_feature_spec.rb
=> Avoid showing the redundant "Signed in/out" flashy messages

app/controllers/admin/users_controller.rb, app/views/admin/users/index.html.slim, spec/controllers/admin/users_controller_spec.rb
=> Don't allow an admin user to remove admin privileges from itself

app/assets/javascripts/portus_layout.js, app/views/shared/_header.html.slim
=> Don't search if the user has not typed anything

app/views/shared/_aside.html.slim, spec/features/auth/login_feature_spec.rb, spec/features/auth/signup_feature_spec.rb
=> Renamed the Dashboard tab to Activities

app/controllers/auth/registrations_controller.rb, spec/features/auth/update_password_feature_spec.rb
=> Don't logout a user after it has changed its password

app/controllers/auth/registrations_controller.rb, app/views/shared/_notification.html.slim, app/views/shared/_notifications.html.slim, spec/features/auth/signup_feature_spec.rb
=> Fixed some issues around flashy messages

app/assets/javascripts/portus_layout.coffee
=> Fixed regression on opening the search form

packaging/suse/Portus.spec.in, public/landing.html.in
This works without having to modify the apache2 configuration. @flavio : good idea :) !
=> add stylesheet information to landing page

app/views/team_users/update.js.erb, app/views/teams/create.js.erb
=> Fix issue on changing permissions of a team member

packaging/suse/Portus.spec.in
fix a typo in variable substitution...
=> fix landing page stylesheet

public/landing.html.in
=> Fixed the style for the landing page

app/assets/javascripts/application.coffee, app/assets/javascripts/teams.coffee
These issues have been reported by the CoffeeScript engine of the new tool
from CodeClimate: https://github.com/codeclimate/codeclimate
=> Fixed some code style issues in the CoffeeScript code

app/assets/javascripts/teams.coffee, app/controllers/namespaces_controller.rb, app/views/namespaces/create.js.erb, app/views/namespaces/index.html.slim
=> Add the possibility to create namespaces from the Namespaces tab

.rubocop.yml, app/models/registry.rb, app/models/repository.rb, app/models/user.rb
I've basically splitted the original handle_push_event so all the actions where
performed by the responsible models. This way the handling of push events is
way more simple and understandable.
=> Re-factored the way we handle push events from the Registry

app/assets/javascripts/teams.coffee
=> teams: fixed regression where namespaces could not be created from team page

app/models/repository.rb, spec/models/repository_spec.rb
=> repository: allow the same repo be repeated across namespaces

README.md
=> Fix release steps list formatting

app/controllers/namespaces_controller.rb, db/migrate/20150629080516_change_registry_id_from_namespace.rb, db/schema.rb, spec/factories/namespaces.rb
=> namespaces: set the registry_id column as not nullable

app/views/namespaces/index.html.slim, app/views/teams/show.html.slim
=> namespaces: don't show any UI tool when there's no registry in the system

db/migrate/20150629080516_change_registry_id_from_namespace.rb
=> db/migrate: fixed an execption from a migration

README.md
See: https://github.com/SUSE/Portus/wiki/How-we-create-new-releases
See: https://github.com/SUSE/Portus/wiki/How-we-test-Portus
=> Moved some parts of the README to the Wiki

packaging/suse/appliance-test/README.md, packaging/suse/appliance-test/test-appliance.sh
We run this tests in a jenkins job against an appliance that has already
been launched on an openstack cloud.
=> add appliance tests

index.html
Adding two additional sections 
* Try Portus
* Feedback, comments, contributions?
=> Adds the "Try Portus" and "Feedback, comments, contributions?" sections.

.dockerignore, .gitignore, app/views/namespaces/_namespace.html.slim, app/views/namespaces/index.html.slim
=> Show namespace creation date

app/views/team_users/_team_user.html.slim
- Fixes #214 
- Fixed some slim codestyle.
=> ISSUE-214: removed useless tag in team page to align role edit select and button.

app/views/admin/dashboard/index.html.slim, app/views/admin/registries/new.html.slim, app/views/devise/registrations/edit.html.slim, app/views/namespaces/_namespace.html.slim, app/views/repositories/index.html.slim, app/views/repositories/show.html.slim, app/views/search/index.html.slim, app/views/team_users/_team_user.html.slim, app/views/teams/_team.html.slim, app/views/teams/show.html.slim
=> ISSUE-110: Fixed slim styling issues

app/models/team.rb, spec/models/team_spec.rb
=> ISSUE-234: namespaces name validation now also adds an error to the model now to fix #234

app/views/teams/show.html.slim
This is a regression that appeared after merging the PR #229
=> teams: add the "Created at" column in the table

Dockerfile, docker/compose-common.yml
=> Fix docker-compose build

compose-setup.sh
Hi guys, here are the changes we were doing on my machine in case you want to merge them into master.
Thanks again for the help!
=> Remove containers when configuring the DB

config/database.yml, config/secrets.yml, deploy/before_migrate.rb
this can help in easy creation of an AWS opsworks rails app.
=> setting machine fqdn as env variable

app/models/concerns/http_helpers.rb, app/models/namespace/auth_scope.rb, app/models/registry_client.rb, app/policies/namespace_policy.rb, docker/registry/config.yml.template, spec/classes/registry_client_spec.rb, spec/jobs/catalog_job_spec.rb, spec/models/namespace/auth_scope_spec.rb, spec/vcr_cassettes/registry/delete_blob.yml, spec/vcr_cassettes/registry/delete_disabled.yml, spec/vcr_cassettes/registry/delete_missing_blob.yml, spec/vcr_cassettes/registry/get_image_manifest.yml, vagrant/conf/registry-config.yml
This feature is still experimental and I want to further investigate about it.
That's why for now I'm just implementing this as a RegistryClient method
instead of also adding this functionality to Portus' itself.
=> Implemented the delete of image blobs in the RegistryClient class

bin/client.rb
This script is quite handy when debugging the RegistryClient class.
=> bin: added the `client.rb` script

config/environments/production.rb
We had the log level as debug. This was by mistake
=> fix log level in production

CNAME
=> Added a CNAME file

packaging/suse/make_spec.sh
=> [packaging] we do not need to make explicit the required libraries

packaging/suse/Portus.spec.in, packaging/suse/conf/portus_crono.service, packaging/suse/scripts/configure_all.sh, packaging/suse/scripts/configure_crono.sh, packaging/suse/scripts/portus_crono
=> add crono systemd scripts

app/models/user.rb, config/initializers/devise.rb, db/migrate/20150915130327_add_lockable_to_users.rb, db/schema.rb, spec/features/auth/login_feature_spec.rb
=> Lock users' accounts if they have failed too many times on login

config/environments/production.rb
check if APP_CONFIG is defined, since it is not when running
"rake assets:precompile"
and thus was failing
=> fix assets:precompile task

config/locales/devise.en.yml, lib/portus/ldap.rb, spec/lib/portus/ldap_spec.rb
=> More specific error-messages for the implementation of ldap

app/views/devise/registrations/new.html.slim
=> Added the autocomplete attribute to the signup-form and turned it off.

app/controllers/api/v2/tokens_controller.rb, lib/portus/jwt_token.rb, spec/lib/portus/jwt_token_spec.rb
=> Cleanud up the JwtToken class

app/assets/stylesheets/layout.scss, app/assets/stylesheets/variables.scss
=> Including sass-rails image-url-helper for the usage of the asset pipeline.

packaging/suse/scripts/portus-firstboot
Improve/fix how we handle hostname when installing Portus' RPM
=> Appliance hostname

packaging/suse/scripts/portus-firstboot
=> [packaging] restart services after re-running the portus-firstboot

public/landing.html.in
=> [packaging] fix certificate paths in landing page

config/config.yml, config/environments/development.rb, config/environments/production.rb, config/initializers/smtp.rb, packaging/suse/portusctl/lib/cli.rb, packaging/suse/portusctl/templates/config-local.yml.erb
=> Allow SMTP to be properly configured inside the config.yml file

packaging/suse/portusctl/lib/configurator.rb, packaging/suse/portusctl/lib/constants.rb
=> portusctl: use the proper hostname command

app/models/repository.rb, spec/models/repository_spec.rb
=> catalog_job: set the "portus" user as the author of the tags being created

vendor/assets/javascripts/lifeitup_layout.js
=> lifeitup: fixed an infinite loop when loading the signup form

app/models/concerns/name_validator.rb, app/models/tag.rb, spec/models/namespace_spec.rb, spec/models/tag_spec.rb
=> Abide to Docker's naming rules for namespaces, repositories and tags

packaging/suse/portusctl/lib/configurator.rb, packaging/suse/portusctl/templates/apache2_portus.conf.erb
=> portusctl: use right certificate

Dockerfile, docker-compose.yml, docker/crono-supervisord.conf
Run crono also when using the docker-compose setup.
This fixes issue #418
=> compose setup: add crono

compose-setup.sh
Thanks to @gbisheimer for coming up with this solution!
Fixes #417
=> compose: pick the DOCKER_HOST from the docker0 interface

app/views/admin/registries/new.html.slim
=> Be more explicit on common pitfalls when creating the new registry

app/controllers/application_controller.rb, spec/controllers/admin/activities_controller_spec.rb, spec/controllers/admin/dashboard_controller_spec.rb, spec/controllers/admin/namespaces_controller_spec.rb, spec/controllers/admin/teams_controller_spec.rb, spec/controllers/admin/users_controller_spec.rb, spec/controllers/dashboard_controller_spec.rb, spec/controllers/namespaces_controller_spec.rb, spec/features/admin/registries_spec.rb
This is the last filter that will be applied.
=> Redirect an admin to registries#new if no registry has been created yet

app/controllers/admin/registries_controller.rb
=> registries: show an error when the registry could not be created

app/controllers/application_controller.rb, public/401.html
=> Created a static "Access Denied" page, instead of rendering text

app/models/registry.rb
We are also more verbose now when something went wrong but we don't know
exactly why.
=> registry: handle timeout errors when creating the registry

spec/features/errors_spec.rb, spec/features/forgotten_password_spec.rb
=> spec/features: fixed tests failures introduced by the last UI iteration

app/models/user.rb, spec/models/user_spec.rb
=> if LDAP is enabled, user should be found by ldap_name

config/environments/production.rb
=> production: compile assets

config/database.yml, config/environments/staging.rb, config/secrets.yml
It has the same environment config as production, but the database and the
secrets files are based on development. This is a convenient mix between
development and production.
=> config: added the staging environment

compose-setup.sh
Portus will offen fail connecting database, if operating immediately
after mariadb container starting. So it's better adding some seconds
for waiting.
Signed-off-by: depay <depay19@163.com>
=> Add sleep time before configuring db first time

app/controllers/team_users_controller.rb, app/models/team_user.rb, app/policies/team_user_policy.rb, app/views/team_users/destroy.js.erb, app/views/team_users/update.js.erb, spec/controllers/team_users_controller_spec.rb, spec/models/team_user_spec.rb
The code of this class was a real mess. I've fixed it.
=> Refactored the TeamUsersController

app/controllers/repositories_controller.rb, app/policies/public_activity/activity_policy.rb, app/policies/repository_policy.rb, spec/controllers/repositories_controller_spec.rb, spec/controllers/teams_controller_spec.rb, spec/policies/public_activity/activity_policy_spec.rb, spec/policies/repository_policy_spec.rb
=> Added policy checks to the repositories_controller and modified the activities policy.

app/views/admin/users/index.html.slim
=> admin: fixed the layout of the users#index page

app/views/admin/registries/edit.html.slim
=> registries: use the proper style for the registries#edit page

CHANGELOG.md
=> Updated the changelog file

app/views/devise/sessions/new.html.slim
=> Set the first_user_admin warning with the proper color

app/views/teams/_team.html.slim, spec/features/teams_spec.rb
=> teams: do not count disabled users as team members

app/helpers/teams_helper.rb, app/views/team_users/update.js.erb, spec/helpers/teams_helper_spec.rb
fix #522 
update team user icon when role got changed
=> update team user icon when role changes

Dockerfile
mergeable variant of #428. 
fixes #427
=> improve dockerfile

app/views/admin/activities/index.html.slim
=> fix: activities pagination style

compose-setup.sh
```
rake db:setup # Create the database, load the schema, and initialize with the seed data (use db:reset to also drop the database first)
```
=> refa: use rake db:setup

Gemfile.lock, app/assets/javascripts/teams.coffee, app/assets/stylesheets/forms.scss, app/models/registry.rb, app/models/user.rb
=> Added default descriptions for global and personal namespaces

app/controllers/namespaces_controller.rb, spec/controllers/namespaces_controller_spec.rb
=> Added an error message for an unauthorized creation of a namespace.

Gemfile, Gemfile.lock, app/helpers/application_helper.rb, app/views/teams/show.html.slim, app/views/teams/update.js.erb, spec/helpers/application_helper_spec.rb
=> Added the usage of markdown for team description

app/models/repository.rb
found the implementation a bit hard to read.
=> refa: improve create_and_update!-Repository readability

app/views/namespaces/show.html.slim, app/views/namespaces/update.js.erb
=> Added the usage of markdown for the team and namespace description

app/helpers/repositories_helper.rb, app/jobs/catalog_job.rb, app/models/tag.rb, app/views/public_activity/repository/_push.html.slim, spec/helpers/repositories_helper_spec.rb, spec/jobs/catalog_job_spec.rb
Now we take into account more possible failures when rendering it (e.g. the
repository has been removed).
Fixes #476
=> Greatly improved the rendering of push notifications

app/models/repository.rb, spec/models/repository_spec.rb
=> fix: only remove associated tags

app/models/repository.rb, db/migrate/20151112003047_add_digest_to_tags.rb, db/schema.rb, spec/factories/registry_raw_event.rb, spec/models/repository_spec.rb
=> feat: track tag digest

_docs/Configuring-Portus.md
=> docs: added the jwt_expiration_time configurable value

_docs/how_we_release.md
=> docs: fixed release branch

app/views/admin/registries/new.html.slim, config/config.yml, packaging/suse/portusctl/templates/config-local.yml.erb, public/landing.html.in
=> Replaced any references to old wiki pages to the proper documentation page

CONTRIBUTING.md, README.md
This reflects the latests changes on the documentation
=> Updated both the README and the CONTRIBUTING files

app/jobs/catalog_job.rb, spec/jobs/catalog_job_spec.rb
=> refa: use Array.delete instead of Array.delete_if

app/assets/javascripts/teams.coffee
=> Fix typeahead re-initialization

lib/tasks/portus.rake
=> lib/tasks: added a task to create users

app/models/registry.rb, spec/models/registry_spec.rb
could be helpful for issues like #560
=> refa: distinguish timeout and connection refused

app/jobs/catalog_job.rb, spec/jobs/catalog_job_spec.rb
for these kind of repo, tags will be nil
=> Fix bug --- deal with upload not finished repo

bin/client.rb, lib/portus/registry_client.rb, spec/lib/portus/registry_client_spec.rb, spec/vcr_cassettes/registry/catalog_lots_of_repos.yml, spec/vcr_cassettes/registry/get_missing_catalog_endpoint.yml
This way we avoid a bug in distribution.
See docker/distribution#1190
=> client: fetch repositories page by page

app/views/team_users/update.js.erb
=> Update the title of the icon when changing the role of a team member

index.html
=> Fixed the links on the "Try Portus section"

config/config.yml
The verification process has been discarded
See #179 and #283.
=> config: updated the "signup" config

_setups/1_rpm_packages.md
=> setups: improved the documentation on the RPM package setup

app/assets/stylesheets/forms.scss, app/views/namespaces/index.html.slim, app/views/namespaces/show.html.slim, app/views/repositories/show.html.slim, app/views/teams/index.html.slim
=> All textareas have now a max/min width/height.

README.md
=> Added the "Self-hosted" section on the README

README.md
=> Fixed the path to Gulp in the README

app/controllers/repositories_controller.rb, app/helpers/repositories_helper.rb, app/jobs/catalog_job.rb, app/policies/namespace_policy.rb, app/policies/repository_policy.rb, app/views/namespaces/show.html.slim, app/views/repositories/edit.html.slim, app/views/repositories/new.html.slim, app/views/repositories/show.html.slim, config/routes.rb, db/migrate/20151207153613_add_source_url_to_repositories.rb, db/schema.rb, spec/controllers/repositories_controller_spec.rb, spec/helpers/repositories_helper_spec.rb, spec/jobs/catalog_job_spec.rb, spec/policies/namespace_policy_spec.rb
Automated repositories are built from a Dockerfile stored inside of a
remote repository (e.g. a Git repo).
=> Introduce automated repositories

app/views/admin/registries/new.html.slim
=> registries: fixed missmatched span tag

bin/navalia.rb, lib/portus/navalia_client.rb, spec/lib/portus/navalia_client_spec.rb
return types
look for errors on api calls
add method documentation
fix rubocop issues
fix ping (do not use token in ping, meaning set nil as default value for
token)
=> review navalia client

_setups/1_rpm_packages.md
=> setups: added some common pitfalls on installing the RPM on openSUSE

.rubocop.yml, config/config.yml, lib/portus/ldap.rb, packaging/suse/portusctl/lib/configurator.rb, spec/lib/portus/ldap_spec.rb
=> ldap: allow the admin to provide extra filter options

app/views/devise/sessions/new.html.slim, spec/features/auth/login_feature_spec.rb
=> ldap: don't show the "I forgot my password" link

config/environments/production.rb, config/environments/staging.rb, config/initializers/smtp.rb
=> config: fix smtp setup

_setups/3_nginx_bare_metal.md
=> setups: use $http_host for the forwarded host

app/controllers/application_controller.rb, app/views/errors/500.html.erb, app/views/errors/show.html.erb, config/config.yml, config/initializers/mailer_url_options.rb, config/secrets.yml, lib/portus/jwt_token.rb, packaging/suse/portusctl/templates/config-local.yml.erb, packaging/suse/portusctl/templates/secrets.yml.erb, spec/controllers/errors_controller_spec.rb, spec/lib/portus/jwt_token_spec.rb, spec/spec_helper.rb
The machine FQDN is no secret. The fact that this info is legacy code from when
we didn't have a proper config setup
=> Moved the machine FQDN from secrets.yml to config.yml

lib/portus/ldap.rb
=> lib/portus: fixed an issue raised by CodeClimate

app/assets/javascripts/registrations.coffee, app/views/application_tokens/create.js.erb, app/views/devise/registrations/edit.html.slim, spec/features/application_tokens_spec.rb
=> Fixed some minor UX issues on the application tokens form

_docs/Configuring-Portus.md
=> docs: added some missing configurable values

bin/crono, compose-setup.sh, compose/docker-compose.yml.template
Wrapped crono in a script so we can properly wait for the DB to be setup.
Fixes #675
=> compose: fixed crono

_features/application_tokens.md
=> features: added an alert on the page of Application tokens

.travis.yml, packaging/suse/portusctl/lib/cli.rb, packaging/suse/portusctl/lib/constants.rb, packaging/suse/portusctl/spec/options_spec.rb, packaging/suse/portusctl/spec/spec_helper.rb, packaging/suse/portusctl/templates/config-local.yml.erb
Moreover, I've created a small test to check that the config.yml file and
portusctl are always in sync in this regard.
=> portusctl: added missing options

compose/docker-compose.yml.template
The actual ports configuration is a few lines down.
=> removed duplicate ports item from config template

packaging/suse/README.install
=> packaging/suse: fixed typo on post_install message

app/views/layouts/application.html.slim, config/initializers/version.rb
Hi, I've seen this requested as a feature, I put together a small patch that should do the trick.
It displays the git branch/commit if the git command and the .git directory are present on the system.
Signed-off-by: Yann Lopez <l@lonewulf.net>
=> Display the git branch/commit when possible

README.md
=> Added the v2.0 build status in the README.md file

index.html
=> Removed old link referencing the appliance setup

app/jobs/catalog_job.rb, spec/jobs/catalog_job_spec.rb, spec/vcr_cassettes/registry/get_registry_catalog_namespace_missing.yml
=> jobs: fixed crono job when a repository could not be found

_docs/versions.md
=> docs: added a page for the supported Docker versions

app/controllers/application_controller.rb, app/controllers/auth/registrations_controller.rb, app/controllers/passwords_controller.rb, spec/controllers/passwords_controller_spec.rb, spec/features/auth/login_feature_spec.rb
=> Redirect back to accessed page on successful login

app/assets/stylesheets/buttons.scss, app/assets/stylesheets/layout.scss, app/views/layouts/application.html.slim, app/views/shared/_header.html.slim, app/views/shared/_search.html.slim, vendor/assets/stylesheets/lifeitup/buttons.scss
Fixes: #772
Screenshot in a large screen:
Screenshot in a small screen:
Signed-off-by: Matheus Fernandes <matheus.souza.fernandes@gmail.com>
=> Logout button and search repository are now appearing in small devices

_docs/how_we_release.md
=> docs: updated the release procedure

README.md
=> Updated the README about supported docker versions

CONTRIBUTING.md, README.md
More specifically, I've updated the CONTRIBUTING.md and the README.md files.
=> Added notes on the new mailing list

CHANGELOG.md, CONTRIBUTING.md, lib/portus/config.rb, lib/portus/hash_utils.rb, lib/tasks/info.rake, spec/fixtures/config.yml, spec/lib/portus/config_spec.rb, spec/models/registry_spec.rb
For now it shows the version and the evaluated config.
=> Added a rake task showing general info

app/assets/stylesheets/application.scss, app/assets/stylesheets/repositories.scss, app/controllers/repositories_controller.rb, app/models/repository.rb, app/views/repositories/show.html.slim, spec/models/repository_spec.rb
This should come in handy whenever we want to implement removing tags.
Fixes #674
=> Group tags by digest

bin/client.rb, lib/portus/http_helpers.rb, lib/portus/registry_client.rb
=> lib/portus: we can now remove image manifests

app/models/application_token.rb, app/models/comment.rb, app/models/namespace.rb, app/models/registry.rb, app/models/repository.rb, app/models/star.rb, app/models/tag.rb, app/models/team.rb, app/models/team_user.rb, app/models/user.rb, lib/tasks/annotate.rake, spec/factories/comments.rb, spec/factories/namespaces.rb, spec/factories/registries.rb, spec/factories/repositories.rb, spec/models/application_token_spec.rb, spec/models/comment_spec.rb, spec/models/namespace_spec.rb, spec/models/registry_spec.rb, spec/models/repository_spec.rb, spec/models/star_spec.rb, spec/models/tag_spec.rb, spec/models/team_spec.rb, spec/models/team_user_spec.rb, spec/models/user_spec.rb
I have enable the automated annotation, now the annotations are getting
updated on every migrate command within development environment. Beside
that we are listing the indices now as well.
Signed-off-by: Thomas Boerger <tboerger@suse.de>
=> Enable automated annotation

Gemfile, Gemfile.lock, Guardfile, lib/tasks/brakeman.rake
In order to make the testing while writing code easier I have integrated
guard which watches for file changes and executes the responsible specs
to get feedback from the test suite as soon as possible.
Additionally to that I have also integrated breakman checks to detect
possible security issues and I have also added rubocop to guard to keep
the code style clean.
=> Integrated guard into development environment

packaging/suse/portusctl/lib/cli.rb
=> portusctl: use the proper make_admin task

app/views/repositories/show.html.slim, spec/features/repositories_spec.rb
=> render tags with empty digests in different rows

lib/tasks/portus.rake
=> Added a rake task to update the digest of tags

packaging/suse/portusctl/lib/configurator.rb
=> portusctl: don't configure mysql in docker

app/assets/stylesheets/labels.scss
=> Fixed regression in which <a> inside of a label is blue

app/models/user.rb
=> user: be more explicit on the allowed name format

app/validators/namespace_validator.rb
=> namespace: don't be so cryptic on the format

app/controllers/admin/users_controller.rb, app/views/admin/users/edit.html.slim, app/views/admin/users/index.html.slim, config/routes.rb, spec/controllers/admin/users_controller_spec.rb, spec/features/admin/users_spec.rb
=> Allow admins to edit users

Gemfile, bin/generate_test_data.rb
=> Provide a runner capable of feeding some dev data

README.md
=> Added more information on testing

app/assets/javascripts/teams.coffee, app/controllers/concerns/change_name_description.rb, app/controllers/namespaces_controller.rb, app/controllers/teams_controller.rb, app/policies/namespace_policy.rb, app/views/namespaces/show.html.slim, app/views/namespaces/update.js.erb, app/views/teams/show.html.slim, config/routes.rb, spec/controllers/namespaces_controller_spec.rb, spec/controllers/teams_controller_spec.rb, spec/features/namespaces_spec.rb
=> Admins can now change the ownership of a namespace

packaging/suse/release/release.sh
since we have already properly fixed the spec file on v2.0 branch
=> remove the "hack" for fixing the spec file

.travis.yml
Always trigger an automatic RPM build on OBS for all the changes made to the v2.0 branch.
=> Trigger automatic RPM builds for the v2.0 branch

blog/index.html, feed.xml
=> blog: added RSS

app/assets/stylesheets/images.scss, app/helpers/application_helper.rb
=> helper modified to create a <i> instead of <img> . Fix# 312

README.md
=> Add link to the blog on the readme

app/views/admin/dashboard/index.html.slim
=> Refactored admin dashboard on small screens

_docs/Configuring-Portus.md
=> docs: added the "delete" feature and some notes

app/views/namespaces/update.js.erb
=> fix link to team's page

_docs/first-steps.md, documentation.md
=> Added a page for newcomers

packaging/suse/make_spec.sh
=> packaging: change - for ~ in the 2.1.0-dev version

packaging/suse/make_spec.sh
=> packaging: Added libcurl as a dependency

README.md
Signed-off-by: chuck-knox <charles.m.knox@gmail.com>
Low hanging fruit. A spelling error in the first line of a README.md was bugging me, so I wanted to fix it. Thanks!
=> minor: Fix spelling error in readme.md

_features/removing_images.md
=> Added a clarification on the delete feature

app/controllers/repositories_controller.rb, app/controllers/tags_controller.rb, app/helpers/repositories_helper.rb, app/policies/repository_policy.rb, app/policies/tag_policy.rb, app/views/repositories/show.html.slim, spec/controllers/auth/sessions_controller_spec.rb, spec/features/repositories_spec.rb, spec/policies/repository_policy_spec.rb
=> Don't allow non-administrators to remove images

_docs/How-to-setup-secure-registry.md
=> docs: updated the machine_fqdn location

lib/tasks/migrate.rake, lib/tasks/portus.rake, spec/lib/portus/jwt_token_spec.rb, spec/lib/tasks/migrate_rake_spec.rb
=> Added a test for the rake task dealing with the personal namespace migration

app/controllers/admin/namespaces_controller.rb, app/controllers/namespaces_controller.rb, app/models/namespace.rb, spec/controllers/admin/namespaces_controller_spec.rb, spec/controllers/namespaces_controller_spec.rb, spec/models/namespace_spec.rb
=> Don't show the namespace of the portus user

app/controllers/errors_controller.rb, app/views/errors/500.csv.slim, app/views/public_activity/webhook/_create.csv.slim, app/views/public_activity/webhook/_destroy.csv.slim
I'm also adding a template for 500 status code for CSV.
Fixes #994
=> Fix crash on webhooks create/destroy CSV activities

.rubocop.yml, bin/bundle, bin/client.rb, bin/generate_test_data.rb, bin/rails, bin/rake, bin/setup, bin/spring, config/environments/production.rb, config/environments/staging.rb, config/initializers/assets.rb, config/initializers/backtrace_silencers.rb, config/initializers/devise.rb, config/initializers/mailer_url_options.rb, config/initializers/version.rb
=> Add more directories under rubocop's control

_posts/2016-07-26-webhooks.md
=> post: introducing webhooks

app/views/public_activity/application_token/_create.html.slim, app/views/public_activity/application_token/_destroy.html.slim
=> Fixed inconsistency on the activities of application tokens

spec/features/repositories_spec.rb, spec/helpers/repositories_helper_spec.rb
=> Fixed flaky tests

config/initializers/mailer_url_options.rb
This doesn't really fix #755, but this issued was already fixed by another
commit.
Fixes #755
=> Update documentation on PORTUS_USE_SSL

spec/helpers/repositories_helper_spec.rb
=> spec: fixed another flaky test

bin/generate_test_data.rb
=> bin: fixed test data generator

_setups/1_rpm_packages.md
=> setups: clarify one aspect of the local-registry flag

app/models/repository.rb, spec/models/repository_spec.rb
=> Update the image ID when a tag has been pushed

lib/tasks/portus.rake
Moreover, the portus:create_user taks has now a check preventing to create
users if there is no registry.
Fixes #1036
=> lib/tasks: added the portus:create_registry task

config/config.yml
=> config: added some references to the documentation

app/controllers/admin/activities_controller.rb, spec/controllers/admin/activities_controller_spec.rb
=> Discard pagination for CSV activities

_docs/Configuring-Portus.md, _docs/portusctl.md
=> docs: updated documentation before the 2.1 release

README.md
=> Clarify the distribution versions

app/assets/stylesheets/repositories.scss
=> style: added missing stylesheet

_docs/upgrading-portus.md, _docs/versions.md
=> docs: documented how to upgrade from 2.0 to 2.1

app/controllers/admin/users_controller.rb
=> admin: always order users by username

app/controllers/api/v2/tokens_controller.rb, spec/api/v2/token_spec.rb
=> Fixed handling of "*" action

app/assets/stylesheets/application.scss, config/initializers/assets.rb
Precompiling everything can lead into problems. Instead, since
everything is bundled inside of the application.{css,js} files, then it
should be fine.
=> config: don't precompile everything blindly

config/initializers/assets.rb
=> config/initializers: precompile auth/cover.js

_docs/FAQ.html, _docs/release-schedule.md, _posts/2016-10-18-portus-2.1.1-and-planning-for-2.2.md, _site/blog/index.html
=> Added blog post and page for the release schedule of Portus 2.2

compose-setup.sh, compose/docker-compose.yml.template, compose/registry/config.yml.template
In my use cases, I needed to run registry with port custom.
With this commit we can set registry port on compose-setup.sh
=> Add registry port cmd

app/views/errors/500.html.erb
=> Fixed the error message for the portus password

lib/tasks/man.rake
=> lib/tasks: only allow the man.rake file in development and testing

app/views/layouts/errors.html.slim
Fixes #1107
Signed-off-by: Miquel Sabaté Solà msabate@suse.com
=> Removed reference to a missing stylesheet

Gemfile.lock
=> Updated the puma gem

packaging/suse/gem_patches/01_downgrade_redcarpet.gem.patch, packaging/suse/gem_patches/02_downgrade_rails.gem.patch, packaging/suse/gem_patches/03_downgrade_json.gem.patch, packaging/suse/gem_patches/README, packaging/suse/make_spec.sh, packaging/suse/package_and_push_to_obs.sh, packaging/suse/portus.spec.in, packaging/suse/rpm_patches/README, packaging/suse/rpm_patches/update.patch
We need to add some patch management because otherwise we add the
patches later in the build service but then, if we rerun the script,
those patches are erased
=> add patch management for making the spec file

packaging/suse/gem_patches/01_downgrade_redcarpet.gem.patch, packaging/suse/gem_patches/02_downgrade_rails.gem.patch
Otherwise it will create Gemfile.orig and Gemfile.lock.orig because
lines to do no match
=> update gem patches

_setups/4_portus_and_registry_on_the_same_fqdn.md
See https://github.com/SUSE/Portus/issues/644#issuecomment-220260388
=> setups: Added tip on mod_header

_docs/Configuring-Portus.md, _site/blog/index.html
=> Documented sub-URI handling and the configuration for the path of config-local

app/views/devise/sessions/new.html.slim, spec/features/admin/dashboard_spec.rb, spec/features/admin/registries_spec.rb, spec/features/application_spec.rb, spec/features/auth/login_feature_spec.rb, spec/features/auth/logout_feature_spec.rb, spec/features/auth/profile_feature_spec.rb, spec/features/dashboard_spec.rb, spec/features/forgotten_password_spec.rb, spec/features/gravatar_spec.rb, spec/features/repositories_spec.rb, spec/features/teams_spec.rb
On my machine, this change saves us 5 minutes.
=> Speed up some tests

_docs/release-schedule.md, _docs/upgrading-portus.md, _posts/2017-01-31-portus-2.2.md, _site/blog/index.html
=> blog: post about the 2.2.0 release

app/views/public_activity/webhook/_create.html.slim, app/views/public_activity/webhook/_enabled.csv.slim, app/views/public_activity/webhook/_enabled.html.slim, spec/views/public_activity/webhook/_create.csv.slim_spec.rb, spec/views/public_activity/webhook/_create.html.slim_spec.rb, spec/views/public_activity/webhook/_enabled.csv.slim_spec.rb, spec/views/public_activity/webhook/_enabled.html.slim_spec.rb
I've also taken the opportunity to introduce some view tests.
=> Fixed some crashes for webhook activities

packaging/suse/portusctl/lib/configurator.rb
following up on #1166 there has been introduced a small syntax error
=> packaging: fix syntax error

packaging/suse/make_spec.sh
=> fix mysql lib requirement

app/controllers/admin/namespaces_controller.rb, app/controllers/namespaces_controller.rb, spec/controllers/admin/namespaces_controller_spec.rb
=> Fixed the UI of paginated namespaces

packaging/suse/README.md, packaging/suse/make_spec.sh, packaging/suse/package_and_push_to_obs.sh, packaging/suse/release/release.sh
providing the package name as an argument enables reusage for similar
projects
=> packaging: a more generic make_spec.sh

config/puma.rb
This config file is meant to be used either for development purposes, or
production environments (e.g. inside of a Docker container).
=> config: added a puma config file

Gemfile, config/puma.rb
=> Fixed rubocop complains

packaging/suse/patches/4_downgrade_puma.patch
=> packaging: downgrade puma on sle

packaging/suse/patches/0_change_versions.gem.patch
=> packaging: updated patch on gemfile

packaging/suse/patches/0_change_versions.gem.patch
=> packaging: Updated the patch for gem versions

packaging/suse/portus.spec.in
=> packaging: fixed key-base new env. variable name

app/assets/javascripts/includes/set_typehead.coffee, app/assets/stylesheets/components/typeahead.scss
Minor tweaks to give the user the experience of using an autocomplete component.
=> typeahead: tweak on hint/highlight to improve ux

app/assets/javascripts/alert.js, app/assets/javascripts/bootstrap.js, app/assets/javascripts/dashboard.js
This commit removes some leftovers from the Coffeescript -> Javascript
move.
=> javascripts: polishing some leftovers

packaging/suse/portus.spec.in
=> packaging: fixed small build error

docker-compose.yml
=> docker: fixed compose dev environment

.eslintrc, .travis.yml, Gemfile, Gemfile.lock, app/assets/javascripts/alert.js, app/assets/javascripts/application.js, app/assets/javascripts/includes/open_close_icon.js, app/assets/javascripts/includes/set_typehead.js, app/assets/stylesheets/application.scss, app/views/layouts/application.html.slim, app/views/layouts/authentication.html.slim, app/views/layouts/errors.html.slim, config/application.rb, config/webpack.js, lib/tasks/assets.rake, package.json, packaging/suse/README.md, packaging/suse/patches/0_change_versions.gem.patch, packaging/suse/portus.spec.in, vendor/assets/javascripts/bootstrap-typeahead.js, vendor/assets/javascripts/lifeitup_layout.js, vendor/assets/stylesheets/bootstrap-typeahead.css, yarn.lock
=> Use webpack for building the assets

lib/tasks/assets.rake
=> assets: only run yarn on offline mode when packaging

lib/tasks/assets.rake, packaging/suse/portus.spec.in
=> packaging: small simplification of JS packaging

packaging/suse/patches/0_change_versions.gem.patch, packaging/suse/portus.spec.in
=> packaging: updated a patch and removing orig files

.travis.yml
=> travis: removed caching since this produces some errors

app/assets/javascripts/teams.js, app/views/teams/update.js.erb, spec/features/teams_spec.rb
Also added alert notification and removed unused variables.
=> Quick fix and improvement on team#update

package.json
Just added local webpack: no global webpack need anymore, just
```
yarn
yarn run webpack
```
=> Add local webpack for building

config/initializers/devise.rb
Relevant documentation:
http://port.us.org/features/8_locking.html
Signed-off-by: Hart Simha <hart.simha@suse.com>
=> Adjust user lock time to match docs. Fixes #1257

app/assets/javascripts/application.js, config/webpack.js, spec/support/wait_for_events.rb
=> es2015: replace 'require' with 'import' syntax

_setups/2_containerized.md, documentation.md
=> Added containerized setup

docker-compose.yml, examples/development/compose/bootstrap-webpack
=> compose: Properly bootstrap the webpack container

packaging/suse/patches/0_change_versions.gem.patch
=> packaging: fixed 0_change_versions.gem.patch

packaging/suse/patches/0_change_versions.gem.patch
=> packaging: fixed some gem versions

.travis.yml
=> travis: fixed credentials being used

app/helpers/comments_helper.rb, app/views/comments/_comment.html.slim, spec/features/repositories_comments_spec.rb, spec/helpers/comments_helper_spec.rb
Also included a quick enhancement by only showing
"Delete comment" to authorized user.
=> spec: added repository's comments feature specs

_features/6_security_scanning.md, _posts/2017-07-19-security-scanning.md, _site/blog/index.html
Added a blog post about the newly merged security scanning support. I've
also fixed a typo from the documentation of this feature.
=> post: security scanning

Gemfile.lock
=> packaging: downgraded mysql gem to match OBS

packaging/suse/patches/0_change_versions.gem.patch
=> packaging: updated patch

packaging/suse/patches/1_update.rpm.patch
=> packaging: updated patch so it applies

Vagrantfile
recently vagrant files were moved under
examples/development/vagrant
=> fixed path for vagrant files

app/assets/javascripts/main.js, app/assets/javascripts/modules/webhooks/components/edit-webhook-form.js, app/assets/javascripts/modules/webhooks/components/new-webhook-form.js, app/assets/javascripts/modules/webhooks/components/webhook-details.js, app/assets/javascripts/modules/webhooks/components/webhooks-panel.js, app/assets/javascripts/modules/webhooks/index.js, app/assets/javascripts/modules/webhooks/pages/index.js, app/assets/javascripts/modules/webhooks/pages/show.js, app/assets/javascripts/teams.js, app/views/webhooks/_webhook.html.slim, app/views/webhooks/create.js.erb, app/views/webhooks/destroy.js.erb, app/views/webhooks/index.html.slim, app/views/webhooks/show.html.slim, app/views/webhooks/toggle_enabled.js.erb, app/views/webhooks/update.js.erb, spec/features/webhooks_spec.rb
Lemme know if I've missed any use case so I can write more tests.
=> js: webhooks module refactoring

Gemfile.lock, packaging/suse/patches/0_change_versions.gem.patch
=> packaging: fixed globalid version

packaging/suse/patches/0_change_versions.gem.patch
=> packaging: rails-html-sanitizer has been upgraded

packaging/suse/portus.spec.in
=> packaging: don't remove some needed files

_docs/release-schedule.md
=> docs: specified the release schedule for 2.3

_docs/versions.md
=> Updated the versions page

_docs/Configuring-Portus.md, _features/6_security_scanning.md, _features/health.md
=> Added documentation for health checks

app/views/search/index.html.slim, spec/views/search/index.html.slim_spec.rb
I've also provided a view spec test.
Fixes #1398
=> Fixed a render error on the search/index page

Gemfile, Gemfile.lock
=> Upgrade some gems that are available in OBS

Gemfile.lock
=> Updated grape-swagger gems

Gemfile, Gemfile.lock, config/application.rb
=> Added rack-cors to prevent AJAX CORS attacks

app/controllers/namespaces_controller.rb, app/controllers/teams_controller.rb, spec/controllers/namespaces_controller_spec.rb
Thanks Ricardo Sánchez for reporting!
=> Mitigate a possible XSS attack on typeahead

config/config.yml, lib/portus/http_helpers.rb, packaging/suse/portusctl/lib/cli.rb, packaging/suse/portusctl/man/man1/portusctl-setup.1, packaging/suse/portusctl/man/markdown/portusctl-setup.md, spec/spec_helper.rb
=> Implemented timeout for requests targetting the registry

app/assets/javascripts/modules/repositories/components/table-row.js, app/assets/javascripts/modules/repositories/components/table.js, app/assets/javascripts/modules/repositories/index.js, app/assets/javascripts/modules/repositories/pages/index.js, app/assets/javascripts/shared/mixins/table-paginated.js, app/controllers/repositories_controller.rb, app/views/repositories/components/_table.html.slim, app/views/repositories/components/_table_row.html.slim, app/views/repositories/index.html.slim, app/views/shared/_aside.html.slim, lib/api/entities.rb, spec/features/namespaces_spec.rb, spec/features/repositories_spec.rb, spec/features/teams_spec.rb
The default pagination limit was also changed to `10`.
Fixes #1420
=> repositories: migrated to vue and exposed on menu

app/assets/javascripts/modules/namespaces/components/new-form.js, app/assets/javascripts/modules/namespaces/services/namespaces.js, app/controllers/namespaces_controller.rb, app/views/namespaces/components/_form.html.slim, app/views/teams/components/_form.html.slim, lib/api/entities.rb, lib/api/root_api.rb, lib/api/v1/namespaces.rb, lib/api/v1/registries.rb, spec/api/grape_api/v1/namespaces_spec.rb, spec/api/grape_api/v1/registries_spec.rb
=> api: added a validate endpoint 

README.md
~~The video being shown is quite old, and it confused people because some
of the statements are no longer valid.~~
=> Updated the README about how to deploy Portus

lib/portus/security_backends/clair.rb, spec/lib/portus/security/clair_spec.rb, spec/vcr_cassettes/security/clair_features_nil.yml
Fixes #1351
Signed-off-by: James Maidment james@maidment.org
=> Avoid iterating on nil key.

examples/compose/docker-compose.insecure.yml, examples/compose/docker-compose.yml
Signed-off-by: Thorsten Schifferdecker <ts@systs.org>
=> Fix #1465, correct the docker-compose files

lib/portus/deprecation_error.rb, lib/portus/migrate.rb, spec/lib/portus/deprecation_error_spec.rb, spec/lib/portus/jwt_token_spec.rb, spec/lib/portus/migrate_spec.rb
saw issue #1470 and found `lib/portus/migrate.rb` a bit hard to follow. 
Hope you don't mind the refactoring.
=> refa: reduce usage of send

config/initializers/environment_check.rb
@mssola hope this was meant with #1473.
=> feat: raise DeprecationError for old Database Configuration

lib/portus/migrate.rb
Reverts SUSE/Portus#1478
Fixes #1483
=> Revert "Force the integer conversion"

app/assets/javascripts/main.js, app/assets/javascripts/polyfill.js, app/views/layouts/application.html.slim, package.json, yarn.lock
=> feat: offline polyfills

app/assets/javascripts/utils/date.js
=> js: fixed moment parse deprecation warning

app/assets/javascripts/modules/users/components/profile-form.js, spec/features/application_tokens_spec.rb, spec/features/auth/profile_feature_spec.rb, spec/support/helpers.rb
Also improved specs and removed unnecessary `disabled?` helper.
Fixes #1491
=> js: fixed validation of profile form update button

Gemfile, Gemfile.lock
The ruby statement in the Gemfile brings more problems than it solves...
Fixes #1498
Fixes #1501
=> Removed ruby constraint from the Gemfile

app/assets/javascripts/modules/namespaces/components/edit-form.js, app/assets/javascripts/modules/namespaces/components/new-form.js, app/assets/javascripts/modules/namespaces/components/visibility.js, app/assets/javascripts/modules/repositories/components/tag.vue, app/assets/javascripts/modules/repositories/pages/show.js, app/assets/javascripts/modules/teams/components/new-form.js, app/assets/javascripts/plugins/alert.js, app/assets/javascripts/shared/components/alert.js, app/assets/javascripts/vue-shared.js
Same idea of #1517. In this case you are still able to use the `Alert` itself but not recommended.
=> js: added alert plugin

app/views/help/index.slim, config/routes.rb, lib/api/root_api.rb, spec/api/grape_api/v1/root_spec.rb, spec/api/grape_api/v1/users_spec.rb, spec/features/help_spec.rb
Depends on #1522, so merge that one first :)
=> api: route unknown routes as 404

config/initializers/version.rb, lib/api/root_api.rb, lib/api/version.rb, spec/api/grape_api/v1/version_spec.rb
Depends on #1523 and #1522. So merge those before this one.
=> api: added /version endpoint

app/assets/javascripts/modules/repositories/components/tags-table-row.vue, app/controllers/tags_controller.rb, app/helpers/repositories_helper.rb, app/models/repository.rb, app/models/tag.rb, bin/background.rb, config/puma.rb, db/migrate/20171130095821_add_scanned_and_vulns_to_tag.rb, db/schema.rb, docker-compose.yml, examples/compose/docker-compose.insecure.yml, examples/compose/docker-compose.yml, examples/development/compose/clair.yml, examples/development/postgresql/docker-compose.yml, lib/api/entities.rb, lib/portus/background/security_scanning.rb, lib/portus/db.rb, lib/portus/security.rb, lib/portus/security_backends/clair.rb, lib/portus/security_backends/dummy.rb, lib/portus/security_backends/zypper.rb, spec/controllers/tags_controller_spec.rb, spec/helpers/repositories_helper_spec.rb, spec/lib/portus/background/security_scanning_spec.rb, spec/lib/portus/security/clair_spec.rb, spec/lib/portus/security_spec.rb, spec/models/tag_spec.rb, spec/vcr_cassettes/background/clair.yml
This pull request is a set of commits which include several fixes in regards to Clair support. Most notably, I've separated the scanning part in another process (similarly as in #1353). The approach is pretty generic and my aim would be in the near future integrate #1353 into this new `bin/background.rb` process as well.
Besides this big change, I've also provided several fixes for small issues here and there.
=> Fixing issues with Clair support

config/config.yml
=> config: be more specific on the supported Clair version

_features/6_security_scanning.md
=> scanning: added note on Clair version

README.md
=> Improved the documentation on deployment options

_setups/2_containerized.md
=> setups: polishing the containerized page

_posts/2017-12-19-container-diff.md, _site/blog/index.html
Note: I prefer to avoid line breaks in text files as the diffs for changes are easier to brain-parse.
Signed-off-by: Valentin Rothberg <vrothberg@suse.com>
=> add blog post for the RPM support of container-diff

app/assets/javascripts/modules/admin/registries/components/form.js, app/controllers/passwords_controller.rb, config/initializers/mail.rb, lib/portus/errors.rb, lib/portus/health_checks/clair.rb, lib/portus/http_helpers.rb, lib/portus/request_error.rb, lib/portus/security_backends/clair.rb, spec/controllers/admin/registries_controller_spec.rb, spec/controllers/passwords_controller_spec.rb, spec/factories/registries.rb, spec/features/admin/registries_spec.rb, spec/features/forgotten_password_spec.rb, spec/helpers/repositories_helper_spec.rb, spec/jobs/catalog_job_spec.rb, spec/lib/portus/registry_notification_spec.rb, spec/lib/portus/request_error_spec.rb, spec/models/registry_spec.rb
=> Improved error detection for mailers

docker-compose.yml
Add "PORTUS" as CCONFIG_PREFIX
=> Add new CCONFIG_PREFIX

examples/compose/docker-compose.insecure.yml, examples/compose/docker-compose.yml, packaging/suse/bin/portusctl, packaging/suse/portus.spec.in
- This fixes a regression in which the init command was not properly set for the background process.
- It also clears out a couple of things on the packaging side.
=> Packaging changes and regression fix

config/initializers/ruby.rb, packaging/suse/portus.spec.in
=> Added checks for the ruby version

_docs/background.md, _features/1_Synchronizing-the-Registry-and-Portus.md
=> Documented the background process

_docs/Configuring-Portus.md
=> docs: added missing configurable options

packaging/suse/bin/portusctl
=> packaging: update ruby paths to 2.5.0

packaging/suse/release/project.xml.template, packaging/suse/release/projectconfig.txt, packaging/suse/release/release.sh
This anticipates the 2.3 release. Moreover, I've also updated some ruby
paths.
=> packaging: updated the project configuration

CHANGELOG.md, examples/compose/docker-compose.yml
=> Updated the changelog to 2.3

Gemfile, Gemfile.lock
=> packaging: updated gems to match openSUSE factory

examples/compose/docker-compose.yml
=> examples: updated secure deployment

.travis.yml, Dockerfile, Gemfile.lock, packaging/suse/make_spec.sh
=> Upgraded bundler to 1.16.0

.babelrc, app/assets/javascripts/main.js, app/assets/javascripts/utils/typeahead.js, app/views/layouts/application.html.slim, app/views/layouts/authentication.html.slim, app/views/layouts/errors.html.slim, config/initializers/assets.rb, config/webpack.js, package.json, vendor/assets/javascripts/jquery.js, vendor/assets/javascripts/typeahead.js, vendor/assets/javascripts/unmanaged.js, yarn.lock
Unfortunately I wasn't able to make it work while using webpack, so I moved both `jquery` and `typeahead` to the vendor directory.
=> js: upgraded jquery to the latest 3.x

Gemfile
=> packaging: some assets gems could not be excluded

app/assets/javascripts/modules/namespaces/services/namespaces.js, app/helpers/application_helper.rb
=> api/js: removed slash duplication from ajax calls

_features/health.md
=> features: updated health endpoints

README.md
=> Updated README file to new versions

packaging/suse/README.md
=> packaging: fixed readme note on portusctl

lib/api/entities.rb, lib/api/v1/health.rb, lib/api/v1/namespaces.rb, lib/api/v1/registries.rb, lib/api/v1/repositories.rb, lib/api/v1/tags.rb, lib/api/v1/teams.rb, lib/api/v1/users.rb, lib/api/version.rb
The version and the health endpoints needed an entity, so they could be
better documented. Moreover, I've adapted some strings (e.g. removing
dots), so it's better suited for efforts like #1645.
=> api: fixed small documentation issues

app/views/help/index.slim
=> help: point to the API documentation on production

config/initializers/swagger.rb, docker-compose.yml
=> compose: fixed swagger's documentation URL

Gemfile, config/application.rb, packaging/suse/portus.spec.in
This also clarifies some issues that we had with asset-related gems.
See kubic-project/velum#432
Fixes #1655
=> packaging: add DB-related gems into the bundle

lib/portus/health_checks/clair.rb, spec/api/grape_api/v1/health_spec.rb
=> health: don't panic on malformed clair url

bin/background.rb, config/config.yml, lib/portus/background/registry.rb, lib/portus/background/security_scanning.rb, lib/portus/background/sync.rb
=> add the possibility to disable background tasks

examples/README.md
=> examples: clarified support for older versions

lib/api/entities.rb, lib/api/v1/namespaces.rb, lib/api/v1/registries.rb, lib/api/v1/teams.rb
=> api: fixed semantic errors

Dockerfile, lib/tasks/test/git-validate.rake
I also fixed a small typo on the git-validate.rake file.
=> test: added git-validation in the dev Dockerfile

_posts/2018-03-02-portus-2.3.md
=> posts: added 2.3 blog post

README.md
I've removed outdated info, and duplicated stuff from the
official documentation.
=> Updated README so it's more concise

lib/tasks/test/integration.rake
I've defined different run options for the integration.rake task, so
integration tests do not take too long.
=> travis: do not run all integration cases on CI

_posts/2018-04-04-portus-2.3-x.md
=> posts: explain 2.3.1 and 2.3.2

docker-compose.yml
=> dev: updated docker-compose images

_docs/Configuring-Portus.md, _features/6_security_scanning.md
=> docs: added the new clair timeout option

README.md
=> Updated last stable release in readme file

app/models/vulnerability.rb, db/migrate/20180412140442_add_description_to_vulnerabilities.rb, db/schema.rb, spec/lib/portus/background/security_scanning_spec.rb
=> Added description into the vulnerabilities table

app/models/repository.rb
This is a small optimization on the repository model, where the portus
user could be re-used in multiple places instead of performing a query
to the database.
=> Re-use the portus user object

lib/api/v1/namespaces.rb, lib/api/v1/teams.rb
=> api: fixed typo

_data/api.yml
=> data: update API documentation with latest changes

_docs/migrate-from-rpm.md, _docs/upgrading-portus.md, _includes/desktop-topics.html
=> docs: added instruction from rpm to container

_docs/migrate-from-rpm.md
Provide a general description of the changes in your pull request. If this pull
request fixes a known issue, please tag it as well (e.g.: `Fixes #1`). Check the
`CONTRIBUTING.md` file for more information.
Thanks for contributing to Portus!
=> [docs] add stopping and removing the rpm as migration steps

_features/1_Synchronizing-the-Registry-and-Portus.md
=> Typo fix: synchonization -> synchronization

app/assets/javascripts/modules/repositories/components/panel.vue, app/assets/javascripts/modules/repositories/pages/index.js, app/views/repositories/components/_table.html.slim, app/views/repositories/index.html.slim
It's a simple basic component that wraps the repositories table
component.
=> js: created repositories panel component

app/assets/javascripts/modules/namespaces/components/info.vue, lib/api/entities.rb
=> ui: do not show hidden team link on namespace#show

Gemfile.lock
=> packaging: update nokogori to its latest version

_posts/2018-05-31-portus-2.3.3.md
=> posts: 2.3.3 released

CHANGELOG.md, README.md
I've also updated the version on the README.md file.
=> Updated CHANGELOG.md file to 2.3.3

_docs/deploy.md, _docs/how_we_release.md
=> docs: update the link from the docker image

_docs/migrate-from-rpm.md
=> docs: added alternative docker command

app/assets/javascripts/modules/repositories/components/tags/tags-table-row.vue
=> ui: display tag pushed date in local time

Gemfile, Gemfile.lock
update sprockets to fix cve-2018-3760
=> update sprockets to fix cve-2018-3760

app/policies/namespace_policy.rb
=> search: fixed for admin users

docker-compose.yml
See openSUSE/docker-containers#104
Fixes #1892
=> dev: update the webpack image to be used

_docs/deploy.md, _docs/secrets.md
=> docs: added note on how the update portus password

app/controllers/passwords_controller.rb, app/models/user.rb, config/initializers/portus_user.rb, db/seeds.rb, spec/api/grape_api/v1/users_spec.rb, spec/api/v2/token_spec.rb, spec/controllers/admin/namespaces_controller_spec.rb, spec/controllers/namespaces_controller_spec.rb, spec/features/admin/dashboard_spec.rb, spec/features/auth/signup_feature_spec.rb, spec/features/forgotten_password_spec.rb, spec/lib/portus/registry_client_spec.rb, spec/models/namespace_spec.rb, spec/models/repository_spec.rb, spec/models/user_spec.rb, spec/support/helpers.rb
Cherry pick of #1896 into the `v2.3` branch.
=> v2.3: Prevent the update of the portus user

app/assets/javascripts/modules/repositories/components/tags/panel.vue
=> ui: fixed tag's vulnerabilities link

_docs/database.md, _docs/deploy.md
The pull request #1880 introduced two new environment variables. This
commit updates the documentation explaining both of them.
=> docs: updated the documentation for #1880

app/controllers/auth/omniauth_callbacks_controller.rb, spec/controllers/auth/omniauth_callbacks_controller_spec.rb, spec/vcr_cassettes/api_github_orgs.yml, spec/vcr_cassettes/api_github_teams.yml, spec/vcr_cassettes/api_gitlab_groups.yml
This allow
* to use a private gitlab instance
* to use paginated group results (actually only the first 20 groups are searched, other are ignored.)
=> Fix gitlab

app/assets/javascripts/modules/repositories/components/tags/panel.vue, app/assets/javascripts/modules/repositories/components/tags/tags-table-row.vue, app/assets/javascripts/modules/repositories/components/tags/tags-table.vue
During one of the refactoring a regression was introduced and the
copying to the clipboard stopped working.
Fixes #1912
=> ui: fixed copy pull command to clipboard

app/assets/javascripts/modules/repositories/components/table.vue
=> ui: fixed repositories table header in namespace#show

CHANGELOG.md, README.md
=> Updated changelog and readme for 2.3.4

_posts/2018-07-30-portus-2.3.4.md, blog/index.html
=> post: release 2.3.4

examples/README.md, examples/compose/README.md, examples/compose/nginx/nginx.conf
Let's be explicit about the `examples` to avoid confusion.
=> examples: updated some wording on the README files

lib/tasks/test/git-validate.rake
=> test: fixed git-validation in travis 

app/assets/javascripts/modules/teams/components/new-form.vue, app/assets/javascripts/modules/users/components/new-form.vue, app/assets/javascripts/modules/webhooks/components/edit-form.vue, app/assets/javascripts/modules/webhooks/components/headers/form.vue, app/assets/javascripts/modules/webhooks/components/new-form.vue
Whenever a form is open, autofocus on its first element.
=> ui: fixed auto focus when opening form

spec/features/admin/users_spec.rb, spec/features/application_tokens_spec.rb, spec/features/gravatar_spec.rb, spec/features/namespaces_spec.rb, spec/features/repositories_comments_spec.rb, spec/features/repositories_spec.rb, spec/features/teams_spec.rb, spec/features/webhooks_spec.rb, spec/support/helpers.rb, spec/support/wait_for_events.rb
=> specs: minor cleaning and removed wait for ajax

_docs/Configuring-Portus.md, _features/removing_images.md
=> Added documentation on Garbage collector

_docs/first-steps.md
=> docs: improved the "First steps" page

_docs/Configuring-Portus.md
=> Extended documentation for the mailer

.rubocop.yml, lib/tasks/portus/db.rake
In particular two helpers have been added for development purposes.
=> tasks: added more tasks for DB operations

spec/features/namespaces_spec.rb, spec/features/repositories_spec.rb, spec/features/teams_spec.rb, spec/javascripts/modules/teams/form.spec.js, spec/support/helpers.rb, spec/vcr_cassettes/registry/get_image_manifest_tags.yml
Besides the readability improvements, new tests were added and other
moved as js unit tests.
=> specs: general improvements on readbility

CHANGELOG.md
=> Updated changelog file for the 2.4 release

_data/api.yml
=> data: updated api.yml file

_docs/release-schedule.md, _posts/2018-10-04-portus-2.4.md
=> blog: Portus 2.4 release

app/assets/javascripts/modules/users/components/new-form.vue, spec/features/admin/users_spec.rb
=> ui: properly show the token for bots

Gemfile.lock
=> Upgrade cconfig

_docs/Configuring-Portus.md, _posts/2018-03-02-portus-2.3.md
=> docs: updated configuration

_docs/deploy.md
=> docs: being more clear on docker tags

lib/tasks/test/git-validate.rake
This should cover pretty much all cases in Travis, and it will simplify
what we've been doing so far.
=> lib: use TRAVIS_COMMIT_RANGE for git-validation

examples/compose/README.md
I always forget the command to generate self-signed certificates, so I'm happy if README.md teaches me it.
=> add how to generate self-signed certificates

lib/api/helpers.rb, lib/api/helpers/ordering.rb, lib/api/helpers/pagination.rb, lib/api/root_api.rb, lib/api/v1/ordering_params.rb, lib/api/v1/pagination_params.rb, lib/api/v1/repositories.rb, spec/api/grape_api/v1/repositories_spec.rb
=> api: added pagination/ordering to repositories

index.md
=> Fix a typo in the index

_docs/Configuring-Portus.md
=> docs: updated pagination configuration

_docs/Configuring-Portus.md
=> docs: added `ldap.admin_base`

app/helpers/namespaces_helper.rb, app/models/team.rb, app/models/team_user.rb, app/policies/team_policy.rb, app/services/teams/destroy_service.rb, app/services/teams/migration_service.rb, app/views/public_activity/namespace/_create.html.slim, app/views/public_activity/registry/_remove_team.csv.slim, app/views/public_activity/registry/_remove_team.html.slim, app/views/public_activity/team/_add_member.html.slim, app/views/public_activity/team/_create.html.slim, app/views/public_activity/team/_migration.html.slim, lib/api/v1/teams.rb, spec/api/grape_api/v1/teams_spec.rb, spec/helpers/namespaces_helper_spec.rb, spec/services/teams/destroy_service_spec.rb, spec/services/teams/migration_service_spec.rb
=> api: implemented team removal endpoint

packaging/suse/portus.spec.in
=> packaging: fixed some issues found on portus.spec

app/assets/javascripts/modules/namespaces/components/transfer-modal.vue, app/assets/javascripts/modules/namespaces/pages/index.vue, spec/system/namespaces_spec.rb
=> ui: remaining namespace transfer improvements

app/assets/javascripts/modules/repositories/components/tags/delete-tag-action.vue, app/assets/javascripts/modules/repositories/components/tags/tags-table-row.vue, app/assets/javascripts/modules/repositories/components/tags/tags-table.vue, app/assets/javascripts/modules/repositories/components/tags/vulnerabilities-preview.vue, app/assets/javascripts/modules/repositories/services/vulnerabilities-parser.js, app/assets/javascripts/shared/components/checkbox.vue, app/assets/stylesheets/includes/forms.scss, app/assets/stylesheets/includes/labels.scss, lib/api/entities.rb, spec/javascripts/modules/repositories/tags-table-row.spec.js, spec/javascripts/modules/repositories/tags-table.spec.js, spec/javascripts/modules/repositories/vulnerabilities-parser.spec.js, spec/javascripts/modules/repositories/vulnerabilities-preview.spec.js, spec/javascripts/setup.js, spec/system/repositories_spec.rb, vendor/assets/stylesheets/lifeitup/table.scss
A few improvements were done regarding the tag's row. See below:
- Present vulnerabilities in a more friendly way (highlight # of high or if it's free of vulnerabilities)
- Rename Pushed at to Last modified
- Humanize Last modified at column
- Tooltip with full date when hovering Last modified
- Style checkbox
Fixes #2071
=> ui: improved tag's row content

app/views/public_activity/team/_add_member.html.slim, app/views/public_activity/team/_remove_member.csv.slim, app/views/public_activity/team/_remove_member.html.slim, spec/views/public_activity/team/_remove_member.csv.slim_spec.rb, spec/views/public_activity/team/_remove_member.html.slim_spec.rb
=> ui: fixed team member deletion when user removed

app/assets/javascripts/modules/repositories/components/tags/tags-table-row.vue, app/assets/javascripts/modules/repositories/components/tags/tags-table.vue, app/models/registry.rb, app/models/repository.rb, app/models/tag.rb, db/migrate/20190109112643_add_size_to_tags.rb, db/schema.mysql.rb, db/schema.postgresql.rb, lib/api/entities.rb, lib/api/v1/repositories.rb, lib/portus/registry_client.rb, lib/portus/security.rb, spec/helpers/repositories_helper_spec.rb, spec/integration/helpers/delete.rb, spec/javascripts/modules/repositories/tags-table-row.spec.js, spec/lib/portus/background/sync_spec.rb, spec/lib/portus/registry_client_spec.rb, spec/models/registry_spec.rb, spec/models/repository_spec.rb, spec/models/tag_spec.rb, spec/vcr_cassettes/registry/get_image_manifest.yml, spec/vcr_cassettes/registry/get_image_manifest_another_webhook.yml, spec/vcr_cassettes/registry/get_image_manifest_namespaced_webhook.yml, spec/vcr_cassettes/registry/get_image_manifest_webhook.yml, spec/views/public_activity/registry/_delete.csv.slim_spec.rb, spec/views/public_activity/registry/_delete.html.slim_spec.rb
=> tags: added size column

_posts/2019-01-16-portus-2.3.7-and-2.4.1.md
=> posts: created post for 2.3.7 and 2.4.1

_docs/Configuring-Portus.md, _features/removing_images.md
=> docs: updated garbage collector new option and behavior

CHANGELOG.md
=> Updated changelog from previous releases

Dockerfile
=> updated Dockerfile for development

_docs/upgrading-portus.md
A section that explains why the UI goes into a broken state when
upgrading using docker compose with nginx container from our examples.
Also shows a solution for the issue.
=> docs: added upgrading w/ compose section

examples/compose/README.md
=> examples/compose: added clarification on volumes

app/assets/javascripts/modules/namespaces/components/new-form.vue, app/assets/javascripts/modules/namespaces/pages/index.vue, app/assets/javascripts/modules/repositories/pages/index.vue, app/assets/javascripts/modules/teams/components/new-form.vue, app/assets/javascripts/modules/teams/components/table.vue, app/assets/javascripts/modules/users/components/application-tokens/form.vue, app/assets/javascripts/modules/users/components/application-tokens/panel.vue, app/assets/javascripts/modules/users/components/new-form.vue, app/assets/javascripts/modules/users/components/panel.vue
Mostly on forms and panel titles.
Fixes #2113
=> ui: improved wording

app/helpers/activities_helper.rb, app/helpers/repositories_helper.rb, app/views/public_activity/team/_add_member.csv.slim, app/views/public_activity/team/_add_member.html.slim, app/views/public_activity/team/_remove_member.csv.slim, app/views/public_activity/team/_remove_member.html.slim, spec/helpers/repositories_helper_spec.rb
Some activities are created due to a portus action and from time to time
people get confused about them. The idea was to highlight that portus actions
automatically happen via the sync job.
=> ui: improved activities wording

_docs/versions.md
=> docs: updated the notes on distribution support

README.md
=> Updated README.md with the latest stable release

lib/portus/ldap/configuration.rb
Fixes #2136
Signed-off-by: Ross Dougherty <ross@inomial.com>
=> fix ldap auth failure on second login

lib/portus/ldap/configuration.rb
=> ldap: added a small clarification comment

Dockerfile
=> Fixed Dockerfile for development

README.md
=> Update README with the latest stable release

.travis.yml, packaging/suse/portus.spec.in
I've also added an environment variable on the .travis.yml file so codeclimate
is happy with our builds.
=> packaging: fixed gem commands on the build stage

.travis.yml
=> ci: updated ruby version and OBS credentials

packaging/suse/portus.spec.in
There were several issues for the spec file (e.g. ruby 2.5 -> 2.6 transition,
minor issues around declaring packaged files, etc.). This commit addresses all
these issues.
=> packaging: fixed spec file

packaging/suse/release/project.xml.template, packaging/suse/release/projectconfig.txt
=> packaging/suse: updated the templates for the release script

app/assets/javascripts/modules/users/components/new-form.vue
Fixes #2198 
Signed-off-by: David Le Borgne <dleborgne@coheris.com>
=> Fixed email field placeholder
